/* tslint:disable */
/* eslint-disable */
/**
 * SaaS Data Plane API
 * Per-deployment data plane API. One vhost per Deployment under *.saas.omarss.net.
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AuditEventListResponse } from '../models';
// @ts-ignore
import type { AuditEventResponse } from '../models';
// @ts-ignore
import type { ExportAuditEventsRequest } from '../models';
// @ts-ignore
import type { Problem } from '../models';
/**
 * AuditApi - axios parameter creator
 */
export const AuditApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Synchronous export bounded to ExportSyncBudget (1 MiB). Larger exports return 413; the async export path (background worker + signed URL) lands with the v1 Files module. 
         * @summary Export filtered audit events as JSON or CSV.
         * @param {ExportAuditEventsRequest} exportAuditEventsRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        exportAuditEvents: async (exportAuditEventsRequest: ExportAuditEventsRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'exportAuditEventsRequest' is not null or undefined
            assertParamExists('exportAuditEvents', 'exportAuditEventsRequest', exportAuditEventsRequest)
            const localVarPath = `/v1/audit-events/export`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication apiKeyAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json,text/csv,application/problem+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(exportAuditEventsRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Fetch a single audit event by id.
         * @param {string} auditEventId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAuditEvent: async (auditEventId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'auditEventId' is not null or undefined
            assertParamExists('getAuditEvent', 'auditEventId', auditEventId)
            const localVarPath = `/v1/audit-events/{audit_event_id}`
                .replace('{audit_event_id}', encodeURIComponent(String(auditEventId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication apiKeyAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json,application/problem+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns audit events ordered by occurred_at DESC. MVP gates this endpoint with AssertTenant only; the audit.read permission lands with the v1 RBAC hardening pass (ADR 012). 
         * @summary List audit events for a tenant.
         * @param {string} tenantId 
         * @param {number} [limit] Max items to return (default 25, max 200).
         * @param {string} [cursor] Opaque pagination cursor; obtained from a previous response.
         * @param {string} [action] 
         * @param {string} [resourceType] 
         * @param {string} [resourceId] 
         * @param {string} [actorId] 
         * @param {string} [occurredAfter] 
         * @param {string} [occurredBefore] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listAuditEvents: async (tenantId: string, limit?: number, cursor?: string, action?: string, resourceType?: string, resourceId?: string, actorId?: string, occurredAfter?: string, occurredBefore?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('listAuditEvents', 'tenantId', tenantId)
            const localVarPath = `/v1/tenants/{tenant_id}/audit-events`
                .replace('{tenant_id}', encodeURIComponent(String(tenantId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication apiKeyAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (cursor !== undefined) {
                localVarQueryParameter['cursor'] = cursor;
            }

            if (action !== undefined) {
                localVarQueryParameter['action'] = action;
            }

            if (resourceType !== undefined) {
                localVarQueryParameter['resource_type'] = resourceType;
            }

            if (resourceId !== undefined) {
                localVarQueryParameter['resource_id'] = resourceId;
            }

            if (actorId !== undefined) {
                localVarQueryParameter['actor_id'] = actorId;
            }

            if (occurredAfter !== undefined) {
                localVarQueryParameter['occurred_after'] = (occurredAfter as any instanceof Date) ?
                    (occurredAfter as any).toISOString() :
                    occurredAfter;
            }

            if (occurredBefore !== undefined) {
                localVarQueryParameter['occurred_before'] = (occurredBefore as any instanceof Date) ?
                    (occurredBefore as any).toISOString() :
                    occurredBefore;
            }

            localVarHeaderParameter['Accept'] = 'application/json,application/problem+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuditApi - functional programming interface
 */
export const AuditApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuditApiAxiosParamCreator(configuration)
    return {
        /**
         * Synchronous export bounded to ExportSyncBudget (1 MiB). Larger exports return 413; the async export path (background worker + signed URL) lands with the v1 Files module. 
         * @summary Export filtered audit events as JSON or CSV.
         * @param {ExportAuditEventsRequest} exportAuditEventsRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async exportAuditEvents(exportAuditEventsRequest: ExportAuditEventsRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AuditEventListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.exportAuditEvents(exportAuditEventsRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuditApi.exportAuditEvents']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Fetch a single audit event by id.
         * @param {string} auditEventId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getAuditEvent(auditEventId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AuditEventResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAuditEvent(auditEventId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuditApi.getAuditEvent']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns audit events ordered by occurred_at DESC. MVP gates this endpoint with AssertTenant only; the audit.read permission lands with the v1 RBAC hardening pass (ADR 012). 
         * @summary List audit events for a tenant.
         * @param {string} tenantId 
         * @param {number} [limit] Max items to return (default 25, max 200).
         * @param {string} [cursor] Opaque pagination cursor; obtained from a previous response.
         * @param {string} [action] 
         * @param {string} [resourceType] 
         * @param {string} [resourceId] 
         * @param {string} [actorId] 
         * @param {string} [occurredAfter] 
         * @param {string} [occurredBefore] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listAuditEvents(tenantId: string, limit?: number, cursor?: string, action?: string, resourceType?: string, resourceId?: string, actorId?: string, occurredAfter?: string, occurredBefore?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<AuditEventListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listAuditEvents(tenantId, limit, cursor, action, resourceType, resourceId, actorId, occurredAfter, occurredBefore, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AuditApi.listAuditEvents']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AuditApi - factory interface
 */
export const AuditApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuditApiFp(configuration)
    return {
        /**
         * Synchronous export bounded to ExportSyncBudget (1 MiB). Larger exports return 413; the async export path (background worker + signed URL) lands with the v1 Files module. 
         * @summary Export filtered audit events as JSON or CSV.
         * @param {ExportAuditEventsRequest} exportAuditEventsRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        exportAuditEvents(exportAuditEventsRequest: ExportAuditEventsRequest, options?: RawAxiosRequestConfig): AxiosPromise<AuditEventListResponse> {
            return localVarFp.exportAuditEvents(exportAuditEventsRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Fetch a single audit event by id.
         * @param {string} auditEventId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getAuditEvent(auditEventId: string, options?: RawAxiosRequestConfig): AxiosPromise<AuditEventResponse> {
            return localVarFp.getAuditEvent(auditEventId, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns audit events ordered by occurred_at DESC. MVP gates this endpoint with AssertTenant only; the audit.read permission lands with the v1 RBAC hardening pass (ADR 012). 
         * @summary List audit events for a tenant.
         * @param {string} tenantId 
         * @param {number} [limit] Max items to return (default 25, max 200).
         * @param {string} [cursor] Opaque pagination cursor; obtained from a previous response.
         * @param {string} [action] 
         * @param {string} [resourceType] 
         * @param {string} [resourceId] 
         * @param {string} [actorId] 
         * @param {string} [occurredAfter] 
         * @param {string} [occurredBefore] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listAuditEvents(tenantId: string, limit?: number, cursor?: string, action?: string, resourceType?: string, resourceId?: string, actorId?: string, occurredAfter?: string, occurredBefore?: string, options?: RawAxiosRequestConfig): AxiosPromise<AuditEventListResponse> {
            return localVarFp.listAuditEvents(tenantId, limit, cursor, action, resourceType, resourceId, actorId, occurredAfter, occurredBefore, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * AuditApi - interface
 */
export interface AuditApiInterface {
    /**
     * Synchronous export bounded to ExportSyncBudget (1 MiB). Larger exports return 413; the async export path (background worker + signed URL) lands with the v1 Files module. 
     * @summary Export filtered audit events as JSON or CSV.
     * @param {ExportAuditEventsRequest} exportAuditEventsRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    exportAuditEvents(exportAuditEventsRequest: ExportAuditEventsRequest, options?: RawAxiosRequestConfig): AxiosPromise<AuditEventListResponse>;

    /**
     * 
     * @summary Fetch a single audit event by id.
     * @param {string} auditEventId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getAuditEvent(auditEventId: string, options?: RawAxiosRequestConfig): AxiosPromise<AuditEventResponse>;

    /**
     * Returns audit events ordered by occurred_at DESC. MVP gates this endpoint with AssertTenant only; the audit.read permission lands with the v1 RBAC hardening pass (ADR 012). 
     * @summary List audit events for a tenant.
     * @param {string} tenantId 
     * @param {number} [limit] Max items to return (default 25, max 200).
     * @param {string} [cursor] Opaque pagination cursor; obtained from a previous response.
     * @param {string} [action] 
     * @param {string} [resourceType] 
     * @param {string} [resourceId] 
     * @param {string} [actorId] 
     * @param {string} [occurredAfter] 
     * @param {string} [occurredBefore] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listAuditEvents(tenantId: string, limit?: number, cursor?: string, action?: string, resourceType?: string, resourceId?: string, actorId?: string, occurredAfter?: string, occurredBefore?: string, options?: RawAxiosRequestConfig): AxiosPromise<AuditEventListResponse>;

}

/**
 * AuditApi - object-oriented interface
 */
export class AuditApi extends BaseAPI implements AuditApiInterface {
    /**
     * Synchronous export bounded to ExportSyncBudget (1 MiB). Larger exports return 413; the async export path (background worker + signed URL) lands with the v1 Files module. 
     * @summary Export filtered audit events as JSON or CSV.
     * @param {ExportAuditEventsRequest} exportAuditEventsRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public exportAuditEvents(exportAuditEventsRequest: ExportAuditEventsRequest, options?: RawAxiosRequestConfig) {
        return AuditApiFp(this.configuration).exportAuditEvents(exportAuditEventsRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Fetch a single audit event by id.
     * @param {string} auditEventId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getAuditEvent(auditEventId: string, options?: RawAxiosRequestConfig) {
        return AuditApiFp(this.configuration).getAuditEvent(auditEventId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns audit events ordered by occurred_at DESC. MVP gates this endpoint with AssertTenant only; the audit.read permission lands with the v1 RBAC hardening pass (ADR 012). 
     * @summary List audit events for a tenant.
     * @param {string} tenantId 
     * @param {number} [limit] Max items to return (default 25, max 200).
     * @param {string} [cursor] Opaque pagination cursor; obtained from a previous response.
     * @param {string} [action] 
     * @param {string} [resourceType] 
     * @param {string} [resourceId] 
     * @param {string} [actorId] 
     * @param {string} [occurredAfter] 
     * @param {string} [occurredBefore] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listAuditEvents(tenantId: string, limit?: number, cursor?: string, action?: string, resourceType?: string, resourceId?: string, actorId?: string, occurredAfter?: string, occurredBefore?: string, options?: RawAxiosRequestConfig) {
        return AuditApiFp(this.configuration).listAuditEvents(tenantId, limit, cursor, action, resourceType, resourceId, actorId, occurredAfter, occurredBefore, options).then((request) => request(this.axios, this.basePath));
    }
}

