/* tslint:disable */
/* eslint-disable */
/**
 * SaaS Data Plane API
 * Per-deployment data plane API. One vhost per Deployment under *.saas.omarss.net.
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreateNotificationChannelRequest } from '../models';
// @ts-ignore
import type { NotificationChannelListResponse } from '../models';
// @ts-ignore
import type { NotificationChannelResponse } from '../models';
// @ts-ignore
import type { Problem } from '../models';
// @ts-ignore
import type { RotateChannelCredentialsRequest } from '../models';
// @ts-ignore
import type { UpdateNotificationChannelRequest } from '../models';
/**
 * NotificationChannelsApi - axios parameter creator
 */
export const NotificationChannelsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Idempotent. Per ADR 017 credentials in the body are envelope-encrypted before the row is inserted and the persisted plaintext is zeroed immediately. The response NEVER echoes credentials — only a credentials_present flag and last_rotated_at timestamp. 
         * @summary Create a BYOK notification channel.
         * @param {string} idempotencyKey 24-hour idempotency key (idem_&lt;ulid&gt;).
         * @param {CreateNotificationChannelRequest} createNotificationChannelRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createNotificationChannel: async (idempotencyKey: string, createNotificationChannelRequest: CreateNotificationChannelRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'idempotencyKey' is not null or undefined
            assertParamExists('createNotificationChannel', 'idempotencyKey', idempotencyKey)
            // verify required parameter 'createNotificationChannelRequest' is not null or undefined
            assertParamExists('createNotificationChannel', 'createNotificationChannelRequest', createNotificationChannelRequest)
            const localVarPath = `/v1/notification-channels`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication apiKeyAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json,application/problem+json';

            if (idempotencyKey != null) {
                localVarHeaderParameter['Idempotency-Key'] = String(idempotencyKey);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createNotificationChannelRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Soft-delete a notification channel.
         * @param {string} ifMatch Weak ETag from a prior GET; rejects on mismatch with 412.
         * @param {string} channelId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteNotificationChannel: async (ifMatch: string, channelId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ifMatch' is not null or undefined
            assertParamExists('deleteNotificationChannel', 'ifMatch', ifMatch)
            // verify required parameter 'channelId' is not null or undefined
            assertParamExists('deleteNotificationChannel', 'channelId', channelId)
            const localVarPath = `/v1/notification-channels/{channel_id}`
                .replace('{channel_id}', encodeURIComponent(String(channelId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication apiKeyAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/problem+json';

            if (ifMatch != null) {
                localVarHeaderParameter['If-Match'] = String(ifMatch);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Fetch a notification channel by id.
         * @param {string} channelId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNotificationChannel: async (channelId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'channelId' is not null or undefined
            assertParamExists('getNotificationChannel', 'channelId', channelId)
            const localVarPath = `/v1/notification-channels/{channel_id}`
                .replace('{channel_id}', encodeURIComponent(String(channelId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication apiKeyAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json,application/problem+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List BYOK notification channels in the caller\'s tenant.
         * @param {number} [limit] Max items to return (default 25, max 200).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listNotificationChannels: async (limit?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/notification-channels`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication apiKeyAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            localVarHeaderParameter['Accept'] = 'application/json,application/problem+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * ADR 017: rotation is the only verb that accepts new credentials. Bumps row_seq and stamps last_rotated_at; emits the notification_channel.rotated audit event. 
         * @summary Rotate a channel\'s BYOK credentials.
         * @param {string} idempotencyKey 24-hour idempotency key (idem_&lt;ulid&gt;).
         * @param {string} channelId 
         * @param {RotateChannelCredentialsRequest} rotateChannelCredentialsRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        rotateNotificationChannelCredentials: async (idempotencyKey: string, channelId: string, rotateChannelCredentialsRequest: RotateChannelCredentialsRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'idempotencyKey' is not null or undefined
            assertParamExists('rotateNotificationChannelCredentials', 'idempotencyKey', idempotencyKey)
            // verify required parameter 'channelId' is not null or undefined
            assertParamExists('rotateNotificationChannelCredentials', 'channelId', channelId)
            // verify required parameter 'rotateChannelCredentialsRequest' is not null or undefined
            assertParamExists('rotateNotificationChannelCredentials', 'rotateChannelCredentialsRequest', rotateChannelCredentialsRequest)
            const localVarPath = `/v1/notification-channels/{channel_id}/rotate-credentials`
                .replace('{channel_id}', encodeURIComponent(String(channelId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication apiKeyAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json,application/problem+json';

            if (idempotencyKey != null) {
                localVarHeaderParameter['Idempotency-Key'] = String(idempotencyKey);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(rotateChannelCredentialsRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Per ADR 017 PATCH never accepts credentials. Use the dedicated rotate-credentials endpoint to change secrets. 
         * @summary Update a notification channel (metadata only).
         * @param {string} ifMatch Weak ETag from a prior GET; rejects on mismatch with 412.
         * @param {string} idempotencyKey 24-hour idempotency key (idem_&lt;ulid&gt;).
         * @param {string} channelId 
         * @param {UpdateNotificationChannelRequest} updateNotificationChannelRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateNotificationChannel: async (ifMatch: string, idempotencyKey: string, channelId: string, updateNotificationChannelRequest: UpdateNotificationChannelRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ifMatch' is not null or undefined
            assertParamExists('updateNotificationChannel', 'ifMatch', ifMatch)
            // verify required parameter 'idempotencyKey' is not null or undefined
            assertParamExists('updateNotificationChannel', 'idempotencyKey', idempotencyKey)
            // verify required parameter 'channelId' is not null or undefined
            assertParamExists('updateNotificationChannel', 'channelId', channelId)
            // verify required parameter 'updateNotificationChannelRequest' is not null or undefined
            assertParamExists('updateNotificationChannel', 'updateNotificationChannelRequest', updateNotificationChannelRequest)
            const localVarPath = `/v1/notification-channels/{channel_id}`
                .replace('{channel_id}', encodeURIComponent(String(channelId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication apiKeyAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json,application/problem+json';

            if (ifMatch != null) {
                localVarHeaderParameter['If-Match'] = String(ifMatch);
            }
            if (idempotencyKey != null) {
                localVarHeaderParameter['Idempotency-Key'] = String(idempotencyKey);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateNotificationChannelRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * NotificationChannelsApi - functional programming interface
 */
export const NotificationChannelsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = NotificationChannelsApiAxiosParamCreator(configuration)
    return {
        /**
         * Idempotent. Per ADR 017 credentials in the body are envelope-encrypted before the row is inserted and the persisted plaintext is zeroed immediately. The response NEVER echoes credentials — only a credentials_present flag and last_rotated_at timestamp. 
         * @summary Create a BYOK notification channel.
         * @param {string} idempotencyKey 24-hour idempotency key (idem_&lt;ulid&gt;).
         * @param {CreateNotificationChannelRequest} createNotificationChannelRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createNotificationChannel(idempotencyKey: string, createNotificationChannelRequest: CreateNotificationChannelRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<NotificationChannelResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createNotificationChannel(idempotencyKey, createNotificationChannelRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NotificationChannelsApi.createNotificationChannel']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Soft-delete a notification channel.
         * @param {string} ifMatch Weak ETag from a prior GET; rejects on mismatch with 412.
         * @param {string} channelId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteNotificationChannel(ifMatch: string, channelId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteNotificationChannel(ifMatch, channelId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NotificationChannelsApi.deleteNotificationChannel']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Fetch a notification channel by id.
         * @param {string} channelId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getNotificationChannel(channelId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<NotificationChannelResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getNotificationChannel(channelId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NotificationChannelsApi.getNotificationChannel']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List BYOK notification channels in the caller\'s tenant.
         * @param {number} [limit] Max items to return (default 25, max 200).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listNotificationChannels(limit?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<NotificationChannelListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listNotificationChannels(limit, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NotificationChannelsApi.listNotificationChannels']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * ADR 017: rotation is the only verb that accepts new credentials. Bumps row_seq and stamps last_rotated_at; emits the notification_channel.rotated audit event. 
         * @summary Rotate a channel\'s BYOK credentials.
         * @param {string} idempotencyKey 24-hour idempotency key (idem_&lt;ulid&gt;).
         * @param {string} channelId 
         * @param {RotateChannelCredentialsRequest} rotateChannelCredentialsRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async rotateNotificationChannelCredentials(idempotencyKey: string, channelId: string, rotateChannelCredentialsRequest: RotateChannelCredentialsRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<NotificationChannelResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.rotateNotificationChannelCredentials(idempotencyKey, channelId, rotateChannelCredentialsRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NotificationChannelsApi.rotateNotificationChannelCredentials']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Per ADR 017 PATCH never accepts credentials. Use the dedicated rotate-credentials endpoint to change secrets. 
         * @summary Update a notification channel (metadata only).
         * @param {string} ifMatch Weak ETag from a prior GET; rejects on mismatch with 412.
         * @param {string} idempotencyKey 24-hour idempotency key (idem_&lt;ulid&gt;).
         * @param {string} channelId 
         * @param {UpdateNotificationChannelRequest} updateNotificationChannelRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateNotificationChannel(ifMatch: string, idempotencyKey: string, channelId: string, updateNotificationChannelRequest: UpdateNotificationChannelRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<NotificationChannelResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateNotificationChannel(ifMatch, idempotencyKey, channelId, updateNotificationChannelRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['NotificationChannelsApi.updateNotificationChannel']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * NotificationChannelsApi - factory interface
 */
export const NotificationChannelsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = NotificationChannelsApiFp(configuration)
    return {
        /**
         * Idempotent. Per ADR 017 credentials in the body are envelope-encrypted before the row is inserted and the persisted plaintext is zeroed immediately. The response NEVER echoes credentials — only a credentials_present flag and last_rotated_at timestamp. 
         * @summary Create a BYOK notification channel.
         * @param {string} idempotencyKey 24-hour idempotency key (idem_&lt;ulid&gt;).
         * @param {CreateNotificationChannelRequest} createNotificationChannelRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createNotificationChannel(idempotencyKey: string, createNotificationChannelRequest: CreateNotificationChannelRequest, options?: RawAxiosRequestConfig): AxiosPromise<NotificationChannelResponse> {
            return localVarFp.createNotificationChannel(idempotencyKey, createNotificationChannelRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Soft-delete a notification channel.
         * @param {string} ifMatch Weak ETag from a prior GET; rejects on mismatch with 412.
         * @param {string} channelId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteNotificationChannel(ifMatch: string, channelId: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteNotificationChannel(ifMatch, channelId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Fetch a notification channel by id.
         * @param {string} channelId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getNotificationChannel(channelId: string, options?: RawAxiosRequestConfig): AxiosPromise<NotificationChannelResponse> {
            return localVarFp.getNotificationChannel(channelId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List BYOK notification channels in the caller\'s tenant.
         * @param {number} [limit] Max items to return (default 25, max 200).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listNotificationChannels(limit?: number, options?: RawAxiosRequestConfig): AxiosPromise<NotificationChannelListResponse> {
            return localVarFp.listNotificationChannels(limit, options).then((request) => request(axios, basePath));
        },
        /**
         * ADR 017: rotation is the only verb that accepts new credentials. Bumps row_seq and stamps last_rotated_at; emits the notification_channel.rotated audit event. 
         * @summary Rotate a channel\'s BYOK credentials.
         * @param {string} idempotencyKey 24-hour idempotency key (idem_&lt;ulid&gt;).
         * @param {string} channelId 
         * @param {RotateChannelCredentialsRequest} rotateChannelCredentialsRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        rotateNotificationChannelCredentials(idempotencyKey: string, channelId: string, rotateChannelCredentialsRequest: RotateChannelCredentialsRequest, options?: RawAxiosRequestConfig): AxiosPromise<NotificationChannelResponse> {
            return localVarFp.rotateNotificationChannelCredentials(idempotencyKey, channelId, rotateChannelCredentialsRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * Per ADR 017 PATCH never accepts credentials. Use the dedicated rotate-credentials endpoint to change secrets. 
         * @summary Update a notification channel (metadata only).
         * @param {string} ifMatch Weak ETag from a prior GET; rejects on mismatch with 412.
         * @param {string} idempotencyKey 24-hour idempotency key (idem_&lt;ulid&gt;).
         * @param {string} channelId 
         * @param {UpdateNotificationChannelRequest} updateNotificationChannelRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateNotificationChannel(ifMatch: string, idempotencyKey: string, channelId: string, updateNotificationChannelRequest: UpdateNotificationChannelRequest, options?: RawAxiosRequestConfig): AxiosPromise<NotificationChannelResponse> {
            return localVarFp.updateNotificationChannel(ifMatch, idempotencyKey, channelId, updateNotificationChannelRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * NotificationChannelsApi - interface
 */
export interface NotificationChannelsApiInterface {
    /**
     * Idempotent. Per ADR 017 credentials in the body are envelope-encrypted before the row is inserted and the persisted plaintext is zeroed immediately. The response NEVER echoes credentials — only a credentials_present flag and last_rotated_at timestamp. 
     * @summary Create a BYOK notification channel.
     * @param {string} idempotencyKey 24-hour idempotency key (idem_&lt;ulid&gt;).
     * @param {CreateNotificationChannelRequest} createNotificationChannelRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createNotificationChannel(idempotencyKey: string, createNotificationChannelRequest: CreateNotificationChannelRequest, options?: RawAxiosRequestConfig): AxiosPromise<NotificationChannelResponse>;

    /**
     * 
     * @summary Soft-delete a notification channel.
     * @param {string} ifMatch Weak ETag from a prior GET; rejects on mismatch with 412.
     * @param {string} channelId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteNotificationChannel(ifMatch: string, channelId: string, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Fetch a notification channel by id.
     * @param {string} channelId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getNotificationChannel(channelId: string, options?: RawAxiosRequestConfig): AxiosPromise<NotificationChannelResponse>;

    /**
     * 
     * @summary List BYOK notification channels in the caller\'s tenant.
     * @param {number} [limit] Max items to return (default 25, max 200).
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listNotificationChannels(limit?: number, options?: RawAxiosRequestConfig): AxiosPromise<NotificationChannelListResponse>;

    /**
     * ADR 017: rotation is the only verb that accepts new credentials. Bumps row_seq and stamps last_rotated_at; emits the notification_channel.rotated audit event. 
     * @summary Rotate a channel\'s BYOK credentials.
     * @param {string} idempotencyKey 24-hour idempotency key (idem_&lt;ulid&gt;).
     * @param {string} channelId 
     * @param {RotateChannelCredentialsRequest} rotateChannelCredentialsRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    rotateNotificationChannelCredentials(idempotencyKey: string, channelId: string, rotateChannelCredentialsRequest: RotateChannelCredentialsRequest, options?: RawAxiosRequestConfig): AxiosPromise<NotificationChannelResponse>;

    /**
     * Per ADR 017 PATCH never accepts credentials. Use the dedicated rotate-credentials endpoint to change secrets. 
     * @summary Update a notification channel (metadata only).
     * @param {string} ifMatch Weak ETag from a prior GET; rejects on mismatch with 412.
     * @param {string} idempotencyKey 24-hour idempotency key (idem_&lt;ulid&gt;).
     * @param {string} channelId 
     * @param {UpdateNotificationChannelRequest} updateNotificationChannelRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateNotificationChannel(ifMatch: string, idempotencyKey: string, channelId: string, updateNotificationChannelRequest: UpdateNotificationChannelRequest, options?: RawAxiosRequestConfig): AxiosPromise<NotificationChannelResponse>;

}

/**
 * NotificationChannelsApi - object-oriented interface
 */
export class NotificationChannelsApi extends BaseAPI implements NotificationChannelsApiInterface {
    /**
     * Idempotent. Per ADR 017 credentials in the body are envelope-encrypted before the row is inserted and the persisted plaintext is zeroed immediately. The response NEVER echoes credentials — only a credentials_present flag and last_rotated_at timestamp. 
     * @summary Create a BYOK notification channel.
     * @param {string} idempotencyKey 24-hour idempotency key (idem_&lt;ulid&gt;).
     * @param {CreateNotificationChannelRequest} createNotificationChannelRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createNotificationChannel(idempotencyKey: string, createNotificationChannelRequest: CreateNotificationChannelRequest, options?: RawAxiosRequestConfig) {
        return NotificationChannelsApiFp(this.configuration).createNotificationChannel(idempotencyKey, createNotificationChannelRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Soft-delete a notification channel.
     * @param {string} ifMatch Weak ETag from a prior GET; rejects on mismatch with 412.
     * @param {string} channelId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteNotificationChannel(ifMatch: string, channelId: string, options?: RawAxiosRequestConfig) {
        return NotificationChannelsApiFp(this.configuration).deleteNotificationChannel(ifMatch, channelId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Fetch a notification channel by id.
     * @param {string} channelId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getNotificationChannel(channelId: string, options?: RawAxiosRequestConfig) {
        return NotificationChannelsApiFp(this.configuration).getNotificationChannel(channelId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List BYOK notification channels in the caller\'s tenant.
     * @param {number} [limit] Max items to return (default 25, max 200).
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listNotificationChannels(limit?: number, options?: RawAxiosRequestConfig) {
        return NotificationChannelsApiFp(this.configuration).listNotificationChannels(limit, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * ADR 017: rotation is the only verb that accepts new credentials. Bumps row_seq and stamps last_rotated_at; emits the notification_channel.rotated audit event. 
     * @summary Rotate a channel\'s BYOK credentials.
     * @param {string} idempotencyKey 24-hour idempotency key (idem_&lt;ulid&gt;).
     * @param {string} channelId 
     * @param {RotateChannelCredentialsRequest} rotateChannelCredentialsRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public rotateNotificationChannelCredentials(idempotencyKey: string, channelId: string, rotateChannelCredentialsRequest: RotateChannelCredentialsRequest, options?: RawAxiosRequestConfig) {
        return NotificationChannelsApiFp(this.configuration).rotateNotificationChannelCredentials(idempotencyKey, channelId, rotateChannelCredentialsRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Per ADR 017 PATCH never accepts credentials. Use the dedicated rotate-credentials endpoint to change secrets. 
     * @summary Update a notification channel (metadata only).
     * @param {string} ifMatch Weak ETag from a prior GET; rejects on mismatch with 412.
     * @param {string} idempotencyKey 24-hour idempotency key (idem_&lt;ulid&gt;).
     * @param {string} channelId 
     * @param {UpdateNotificationChannelRequest} updateNotificationChannelRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateNotificationChannel(ifMatch: string, idempotencyKey: string, channelId: string, updateNotificationChannelRequest: UpdateNotificationChannelRequest, options?: RawAxiosRequestConfig) {
        return NotificationChannelsApiFp(this.configuration).updateNotificationChannel(ifMatch, idempotencyKey, channelId, updateNotificationChannelRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

