/* tslint:disable */
/* eslint-disable */
/**
 * SaaS Data Plane API
 * Per-deployment data plane API. One vhost per Deployment under *.saas.omarss.net.
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreateOrganizationRequest } from '../models';
// @ts-ignore
import type { OrganizationListResponse } from '../models';
// @ts-ignore
import type { OrganizationResponse } from '../models';
// @ts-ignore
import type { Problem } from '../models';
// @ts-ignore
import type { UpdateOrganizationRequest } from '../models';
/**
 * OrganizationsApi - axios parameter creator
 */
export const OrganizationsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Creating extra organizations requires `tenant.metadata.multi_org=true`. The default organization is auto-created on tenant.create and cannot be created via this endpoint. 
         * @summary Create a new organization in a tenant (multi_org required).
         * @param {string} idempotencyKey 24-hour idempotency key (idem_&lt;ulid&gt;).
         * @param {string} tenantId 
         * @param {CreateOrganizationRequest} createOrganizationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createOrganization: async (idempotencyKey: string, tenantId: string, createOrganizationRequest: CreateOrganizationRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'idempotencyKey' is not null or undefined
            assertParamExists('createOrganization', 'idempotencyKey', idempotencyKey)
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('createOrganization', 'tenantId', tenantId)
            // verify required parameter 'createOrganizationRequest' is not null or undefined
            assertParamExists('createOrganization', 'createOrganizationRequest', createOrganizationRequest)
            const localVarPath = `/v1/tenants/{tenant_id}/organizations`
                .replace('{tenant_id}', encodeURIComponent(String(tenantId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication apiKeyAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json,application/problem+json';

            if (idempotencyKey != null) {
                localVarHeaderParameter['Idempotency-Key'] = String(idempotencyKey);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createOrganizationRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Soft-delete an organization. Refuses while active members remain.
         * @param {string} ifMatch Weak ETag from a prior GET; rejects on mismatch with 412.
         * @param {string} organizationId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteOrganization: async (ifMatch: string, organizationId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ifMatch' is not null or undefined
            assertParamExists('deleteOrganization', 'ifMatch', ifMatch)
            // verify required parameter 'organizationId' is not null or undefined
            assertParamExists('deleteOrganization', 'organizationId', organizationId)
            const localVarPath = `/v1/organizations/{organization_id}`
                .replace('{organization_id}', encodeURIComponent(String(organizationId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication apiKeyAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/problem+json';

            if (ifMatch != null) {
                localVarHeaderParameter['If-Match'] = String(ifMatch);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Fetch an organization by id.
         * @param {string} organizationId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOrganization: async (organizationId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'organizationId' is not null or undefined
            assertParamExists('getOrganization', 'organizationId', organizationId)
            const localVarPath = `/v1/organizations/{organization_id}`
                .replace('{organization_id}', encodeURIComponent(String(organizationId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication apiKeyAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json,application/problem+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List organizations in a tenant.
         * @param {string} tenantId 
         * @param {number} [limit] Max items to return (default 25, max 200).
         * @param {string} [cursor] Opaque pagination cursor; obtained from a previous response.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listOrganizations: async (tenantId: string, limit?: number, cursor?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'tenantId' is not null or undefined
            assertParamExists('listOrganizations', 'tenantId', tenantId)
            const localVarPath = `/v1/tenants/{tenant_id}/organizations`
                .replace('{tenant_id}', encodeURIComponent(String(tenantId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication apiKeyAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (cursor !== undefined) {
                localVarQueryParameter['cursor'] = cursor;
            }

            localVarHeaderParameter['Accept'] = 'application/json,application/problem+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update an organization.
         * @param {string} ifMatch Weak ETag from a prior GET; rejects on mismatch with 412.
         * @param {string} idempotencyKey 24-hour idempotency key (idem_&lt;ulid&gt;).
         * @param {string} organizationId 
         * @param {UpdateOrganizationRequest} updateOrganizationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateOrganization: async (ifMatch: string, idempotencyKey: string, organizationId: string, updateOrganizationRequest: UpdateOrganizationRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ifMatch' is not null or undefined
            assertParamExists('updateOrganization', 'ifMatch', ifMatch)
            // verify required parameter 'idempotencyKey' is not null or undefined
            assertParamExists('updateOrganization', 'idempotencyKey', idempotencyKey)
            // verify required parameter 'organizationId' is not null or undefined
            assertParamExists('updateOrganization', 'organizationId', organizationId)
            // verify required parameter 'updateOrganizationRequest' is not null or undefined
            assertParamExists('updateOrganization', 'updateOrganizationRequest', updateOrganizationRequest)
            const localVarPath = `/v1/organizations/{organization_id}`
                .replace('{organization_id}', encodeURIComponent(String(organizationId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication apiKeyAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json,application/problem+json';

            if (ifMatch != null) {
                localVarHeaderParameter['If-Match'] = String(ifMatch);
            }
            if (idempotencyKey != null) {
                localVarHeaderParameter['Idempotency-Key'] = String(idempotencyKey);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateOrganizationRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * OrganizationsApi - functional programming interface
 */
export const OrganizationsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = OrganizationsApiAxiosParamCreator(configuration)
    return {
        /**
         * Creating extra organizations requires `tenant.metadata.multi_org=true`. The default organization is auto-created on tenant.create and cannot be created via this endpoint. 
         * @summary Create a new organization in a tenant (multi_org required).
         * @param {string} idempotencyKey 24-hour idempotency key (idem_&lt;ulid&gt;).
         * @param {string} tenantId 
         * @param {CreateOrganizationRequest} createOrganizationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createOrganization(idempotencyKey: string, tenantId: string, createOrganizationRequest: CreateOrganizationRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<OrganizationResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createOrganization(idempotencyKey, tenantId, createOrganizationRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OrganizationsApi.createOrganization']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Soft-delete an organization. Refuses while active members remain.
         * @param {string} ifMatch Weak ETag from a prior GET; rejects on mismatch with 412.
         * @param {string} organizationId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteOrganization(ifMatch: string, organizationId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteOrganization(ifMatch, organizationId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OrganizationsApi.deleteOrganization']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Fetch an organization by id.
         * @param {string} organizationId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getOrganization(organizationId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<OrganizationResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getOrganization(organizationId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OrganizationsApi.getOrganization']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List organizations in a tenant.
         * @param {string} tenantId 
         * @param {number} [limit] Max items to return (default 25, max 200).
         * @param {string} [cursor] Opaque pagination cursor; obtained from a previous response.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listOrganizations(tenantId: string, limit?: number, cursor?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<OrganizationListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listOrganizations(tenantId, limit, cursor, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OrganizationsApi.listOrganizations']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update an organization.
         * @param {string} ifMatch Weak ETag from a prior GET; rejects on mismatch with 412.
         * @param {string} idempotencyKey 24-hour idempotency key (idem_&lt;ulid&gt;).
         * @param {string} organizationId 
         * @param {UpdateOrganizationRequest} updateOrganizationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateOrganization(ifMatch: string, idempotencyKey: string, organizationId: string, updateOrganizationRequest: UpdateOrganizationRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<OrganizationResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateOrganization(ifMatch, idempotencyKey, organizationId, updateOrganizationRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OrganizationsApi.updateOrganization']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * OrganizationsApi - factory interface
 */
export const OrganizationsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = OrganizationsApiFp(configuration)
    return {
        /**
         * Creating extra organizations requires `tenant.metadata.multi_org=true`. The default organization is auto-created on tenant.create and cannot be created via this endpoint. 
         * @summary Create a new organization in a tenant (multi_org required).
         * @param {string} idempotencyKey 24-hour idempotency key (idem_&lt;ulid&gt;).
         * @param {string} tenantId 
         * @param {CreateOrganizationRequest} createOrganizationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createOrganization(idempotencyKey: string, tenantId: string, createOrganizationRequest: CreateOrganizationRequest, options?: RawAxiosRequestConfig): AxiosPromise<OrganizationResponse> {
            return localVarFp.createOrganization(idempotencyKey, tenantId, createOrganizationRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Soft-delete an organization. Refuses while active members remain.
         * @param {string} ifMatch Weak ETag from a prior GET; rejects on mismatch with 412.
         * @param {string} organizationId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteOrganization(ifMatch: string, organizationId: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteOrganization(ifMatch, organizationId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Fetch an organization by id.
         * @param {string} organizationId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getOrganization(organizationId: string, options?: RawAxiosRequestConfig): AxiosPromise<OrganizationResponse> {
            return localVarFp.getOrganization(organizationId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List organizations in a tenant.
         * @param {string} tenantId 
         * @param {number} [limit] Max items to return (default 25, max 200).
         * @param {string} [cursor] Opaque pagination cursor; obtained from a previous response.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listOrganizations(tenantId: string, limit?: number, cursor?: string, options?: RawAxiosRequestConfig): AxiosPromise<OrganizationListResponse> {
            return localVarFp.listOrganizations(tenantId, limit, cursor, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update an organization.
         * @param {string} ifMatch Weak ETag from a prior GET; rejects on mismatch with 412.
         * @param {string} idempotencyKey 24-hour idempotency key (idem_&lt;ulid&gt;).
         * @param {string} organizationId 
         * @param {UpdateOrganizationRequest} updateOrganizationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateOrganization(ifMatch: string, idempotencyKey: string, organizationId: string, updateOrganizationRequest: UpdateOrganizationRequest, options?: RawAxiosRequestConfig): AxiosPromise<OrganizationResponse> {
            return localVarFp.updateOrganization(ifMatch, idempotencyKey, organizationId, updateOrganizationRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * OrganizationsApi - interface
 */
export interface OrganizationsApiInterface {
    /**
     * Creating extra organizations requires `tenant.metadata.multi_org=true`. The default organization is auto-created on tenant.create and cannot be created via this endpoint. 
     * @summary Create a new organization in a tenant (multi_org required).
     * @param {string} idempotencyKey 24-hour idempotency key (idem_&lt;ulid&gt;).
     * @param {string} tenantId 
     * @param {CreateOrganizationRequest} createOrganizationRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createOrganization(idempotencyKey: string, tenantId: string, createOrganizationRequest: CreateOrganizationRequest, options?: RawAxiosRequestConfig): AxiosPromise<OrganizationResponse>;

    /**
     * 
     * @summary Soft-delete an organization. Refuses while active members remain.
     * @param {string} ifMatch Weak ETag from a prior GET; rejects on mismatch with 412.
     * @param {string} organizationId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteOrganization(ifMatch: string, organizationId: string, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Fetch an organization by id.
     * @param {string} organizationId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getOrganization(organizationId: string, options?: RawAxiosRequestConfig): AxiosPromise<OrganizationResponse>;

    /**
     * 
     * @summary List organizations in a tenant.
     * @param {string} tenantId 
     * @param {number} [limit] Max items to return (default 25, max 200).
     * @param {string} [cursor] Opaque pagination cursor; obtained from a previous response.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listOrganizations(tenantId: string, limit?: number, cursor?: string, options?: RawAxiosRequestConfig): AxiosPromise<OrganizationListResponse>;

    /**
     * 
     * @summary Update an organization.
     * @param {string} ifMatch Weak ETag from a prior GET; rejects on mismatch with 412.
     * @param {string} idempotencyKey 24-hour idempotency key (idem_&lt;ulid&gt;).
     * @param {string} organizationId 
     * @param {UpdateOrganizationRequest} updateOrganizationRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateOrganization(ifMatch: string, idempotencyKey: string, organizationId: string, updateOrganizationRequest: UpdateOrganizationRequest, options?: RawAxiosRequestConfig): AxiosPromise<OrganizationResponse>;

}

/**
 * OrganizationsApi - object-oriented interface
 */
export class OrganizationsApi extends BaseAPI implements OrganizationsApiInterface {
    /**
     * Creating extra organizations requires `tenant.metadata.multi_org=true`. The default organization is auto-created on tenant.create and cannot be created via this endpoint. 
     * @summary Create a new organization in a tenant (multi_org required).
     * @param {string} idempotencyKey 24-hour idempotency key (idem_&lt;ulid&gt;).
     * @param {string} tenantId 
     * @param {CreateOrganizationRequest} createOrganizationRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createOrganization(idempotencyKey: string, tenantId: string, createOrganizationRequest: CreateOrganizationRequest, options?: RawAxiosRequestConfig) {
        return OrganizationsApiFp(this.configuration).createOrganization(idempotencyKey, tenantId, createOrganizationRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Soft-delete an organization. Refuses while active members remain.
     * @param {string} ifMatch Weak ETag from a prior GET; rejects on mismatch with 412.
     * @param {string} organizationId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteOrganization(ifMatch: string, organizationId: string, options?: RawAxiosRequestConfig) {
        return OrganizationsApiFp(this.configuration).deleteOrganization(ifMatch, organizationId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Fetch an organization by id.
     * @param {string} organizationId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getOrganization(organizationId: string, options?: RawAxiosRequestConfig) {
        return OrganizationsApiFp(this.configuration).getOrganization(organizationId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List organizations in a tenant.
     * @param {string} tenantId 
     * @param {number} [limit] Max items to return (default 25, max 200).
     * @param {string} [cursor] Opaque pagination cursor; obtained from a previous response.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listOrganizations(tenantId: string, limit?: number, cursor?: string, options?: RawAxiosRequestConfig) {
        return OrganizationsApiFp(this.configuration).listOrganizations(tenantId, limit, cursor, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update an organization.
     * @param {string} ifMatch Weak ETag from a prior GET; rejects on mismatch with 412.
     * @param {string} idempotencyKey 24-hour idempotency key (idem_&lt;ulid&gt;).
     * @param {string} organizationId 
     * @param {UpdateOrganizationRequest} updateOrganizationRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateOrganization(ifMatch: string, idempotencyKey: string, organizationId: string, updateOrganizationRequest: UpdateOrganizationRequest, options?: RawAxiosRequestConfig) {
        return OrganizationsApiFp(this.configuration).updateOrganization(ifMatch, idempotencyKey, organizationId, updateOrganizationRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

