/* tslint:disable */
/* eslint-disable */
/**
 * SaaS Data Plane API
 * Per-deployment data plane API. One vhost per Deployment under *.saas.omarss.net.
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { LinkSocialProviderRequest } from '../models';
// @ts-ignore
import type { LinkSocialProviderResponse } from '../models';
// @ts-ignore
import type { Problem } from '../models';
// @ts-ignore
import type { SocialProviderListResponse } from '../models';
/**
 * SocialProvidersApi - axios parameter creator
 */
export const SocialProvidersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Per ADR 014: we never call CreateUserFederatedIdentity from a user-facing endpoint (no proof-of-possession). Instead, the platform mints Keycloak\'s hashed link URL — the caller redirects the user\'s browser there and Keycloak completes the OAuth dance with the external IdP, writing the federated_identity row itself. 
         * @summary Start a social-provider link flow. Returns the Keycloak link URL.
         * @param {string} idempotencyKey 24-hour idempotency key (idem_&lt;ulid&gt;).
         * @param {string} userId 
         * @param {LinkSocialProviderRequest} linkSocialProviderRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        linkSocialProvider: async (idempotencyKey: string, userId: string, linkSocialProviderRequest: LinkSocialProviderRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'idempotencyKey' is not null or undefined
            assertParamExists('linkSocialProvider', 'idempotencyKey', idempotencyKey)
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('linkSocialProvider', 'userId', userId)
            // verify required parameter 'linkSocialProviderRequest' is not null or undefined
            assertParamExists('linkSocialProvider', 'linkSocialProviderRequest', linkSocialProviderRequest)
            const localVarPath = `/v1/users/{user_id}/social-providers`
                .replace('{user_id}', encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication apiKeyAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json,application/problem+json';

            if (idempotencyKey != null) {
                localVarHeaderParameter['Idempotency-Key'] = String(idempotencyKey);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(linkSocialProviderRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List linked social providers for a user.
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listSocialProviders: async (userId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('listSocialProviders', 'userId', userId)
            const localVarPath = `/v1/users/{user_id}/social-providers`
                .replace('{user_id}', encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication apiKeyAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json,application/problem+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Unlink a social provider. Emits user.social_unlinked.
         * @param {string} userId 
         * @param {UnlinkSocialProviderProviderEnum} provider 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        unlinkSocialProvider: async (userId: string, provider: UnlinkSocialProviderProviderEnum, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('unlinkSocialProvider', 'userId', userId)
            // verify required parameter 'provider' is not null or undefined
            assertParamExists('unlinkSocialProvider', 'provider', provider)
            const localVarPath = `/v1/users/{user_id}/social-providers/{provider}`
                .replace('{user_id}', encodeURIComponent(String(userId)))
                .replace('{provider}', encodeURIComponent(String(provider)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication apiKeyAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/problem+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * SocialProvidersApi - functional programming interface
 */
export const SocialProvidersApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SocialProvidersApiAxiosParamCreator(configuration)
    return {
        /**
         * Per ADR 014: we never call CreateUserFederatedIdentity from a user-facing endpoint (no proof-of-possession). Instead, the platform mints Keycloak\'s hashed link URL — the caller redirects the user\'s browser there and Keycloak completes the OAuth dance with the external IdP, writing the federated_identity row itself. 
         * @summary Start a social-provider link flow. Returns the Keycloak link URL.
         * @param {string} idempotencyKey 24-hour idempotency key (idem_&lt;ulid&gt;).
         * @param {string} userId 
         * @param {LinkSocialProviderRequest} linkSocialProviderRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async linkSocialProvider(idempotencyKey: string, userId: string, linkSocialProviderRequest: LinkSocialProviderRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<LinkSocialProviderResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.linkSocialProvider(idempotencyKey, userId, linkSocialProviderRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SocialProvidersApi.linkSocialProvider']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List linked social providers for a user.
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listSocialProviders(userId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SocialProviderListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listSocialProviders(userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SocialProvidersApi.listSocialProviders']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Unlink a social provider. Emits user.social_unlinked.
         * @param {string} userId 
         * @param {UnlinkSocialProviderProviderEnum} provider 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async unlinkSocialProvider(userId: string, provider: UnlinkSocialProviderProviderEnum, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.unlinkSocialProvider(userId, provider, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SocialProvidersApi.unlinkSocialProvider']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SocialProvidersApi - factory interface
 */
export const SocialProvidersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SocialProvidersApiFp(configuration)
    return {
        /**
         * Per ADR 014: we never call CreateUserFederatedIdentity from a user-facing endpoint (no proof-of-possession). Instead, the platform mints Keycloak\'s hashed link URL — the caller redirects the user\'s browser there and Keycloak completes the OAuth dance with the external IdP, writing the federated_identity row itself. 
         * @summary Start a social-provider link flow. Returns the Keycloak link URL.
         * @param {string} idempotencyKey 24-hour idempotency key (idem_&lt;ulid&gt;).
         * @param {string} userId 
         * @param {LinkSocialProviderRequest} linkSocialProviderRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        linkSocialProvider(idempotencyKey: string, userId: string, linkSocialProviderRequest: LinkSocialProviderRequest, options?: RawAxiosRequestConfig): AxiosPromise<LinkSocialProviderResponse> {
            return localVarFp.linkSocialProvider(idempotencyKey, userId, linkSocialProviderRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List linked social providers for a user.
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listSocialProviders(userId: string, options?: RawAxiosRequestConfig): AxiosPromise<SocialProviderListResponse> {
            return localVarFp.listSocialProviders(userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Unlink a social provider. Emits user.social_unlinked.
         * @param {string} userId 
         * @param {UnlinkSocialProviderProviderEnum} provider 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        unlinkSocialProvider(userId: string, provider: UnlinkSocialProviderProviderEnum, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.unlinkSocialProvider(userId, provider, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * SocialProvidersApi - interface
 */
export interface SocialProvidersApiInterface {
    /**
     * Per ADR 014: we never call CreateUserFederatedIdentity from a user-facing endpoint (no proof-of-possession). Instead, the platform mints Keycloak\'s hashed link URL — the caller redirects the user\'s browser there and Keycloak completes the OAuth dance with the external IdP, writing the federated_identity row itself. 
     * @summary Start a social-provider link flow. Returns the Keycloak link URL.
     * @param {string} idempotencyKey 24-hour idempotency key (idem_&lt;ulid&gt;).
     * @param {string} userId 
     * @param {LinkSocialProviderRequest} linkSocialProviderRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    linkSocialProvider(idempotencyKey: string, userId: string, linkSocialProviderRequest: LinkSocialProviderRequest, options?: RawAxiosRequestConfig): AxiosPromise<LinkSocialProviderResponse>;

    /**
     * 
     * @summary List linked social providers for a user.
     * @param {string} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listSocialProviders(userId: string, options?: RawAxiosRequestConfig): AxiosPromise<SocialProviderListResponse>;

    /**
     * 
     * @summary Unlink a social provider. Emits user.social_unlinked.
     * @param {string} userId 
     * @param {UnlinkSocialProviderProviderEnum} provider 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    unlinkSocialProvider(userId: string, provider: UnlinkSocialProviderProviderEnum, options?: RawAxiosRequestConfig): AxiosPromise<void>;

}

/**
 * SocialProvidersApi - object-oriented interface
 */
export class SocialProvidersApi extends BaseAPI implements SocialProvidersApiInterface {
    /**
     * Per ADR 014: we never call CreateUserFederatedIdentity from a user-facing endpoint (no proof-of-possession). Instead, the platform mints Keycloak\'s hashed link URL — the caller redirects the user\'s browser there and Keycloak completes the OAuth dance with the external IdP, writing the federated_identity row itself. 
     * @summary Start a social-provider link flow. Returns the Keycloak link URL.
     * @param {string} idempotencyKey 24-hour idempotency key (idem_&lt;ulid&gt;).
     * @param {string} userId 
     * @param {LinkSocialProviderRequest} linkSocialProviderRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public linkSocialProvider(idempotencyKey: string, userId: string, linkSocialProviderRequest: LinkSocialProviderRequest, options?: RawAxiosRequestConfig) {
        return SocialProvidersApiFp(this.configuration).linkSocialProvider(idempotencyKey, userId, linkSocialProviderRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List linked social providers for a user.
     * @param {string} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listSocialProviders(userId: string, options?: RawAxiosRequestConfig) {
        return SocialProvidersApiFp(this.configuration).listSocialProviders(userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Unlink a social provider. Emits user.social_unlinked.
     * @param {string} userId 
     * @param {UnlinkSocialProviderProviderEnum} provider 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public unlinkSocialProvider(userId: string, provider: UnlinkSocialProviderProviderEnum, options?: RawAxiosRequestConfig) {
        return SocialProvidersApiFp(this.configuration).unlinkSocialProvider(userId, provider, options).then((request) => request(this.axios, this.basePath));
    }
}

export const UnlinkSocialProviderProviderEnum = {
    Google: 'google',
    Github: 'github',
    Apple: 'apple',
} as const;
export type UnlinkSocialProviderProviderEnum = typeof UnlinkSocialProviderProviderEnum[keyof typeof UnlinkSocialProviderProviderEnum];
