/* tslint:disable */
/* eslint-disable */
/**
 * SaaS Data Plane API
 * Per-deployment data plane API. One vhost per Deployment under *.saas.omarss.net.
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreateUserRequest } from '../models';
// @ts-ignore
import type { Problem } from '../models';
// @ts-ignore
import type { UpdateUserRequest } from '../models';
// @ts-ignore
import type { UserListResponse } from '../models';
// @ts-ignore
import type { UserResponse } from '../models';
/**
 * UsersApi - axios parameter creator
 */
export const UsersApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Idempotent. The platform creates a row + a Keycloak user in the shared `saas-data-local` realm (per-Deployment realm lands in Phase 12). Email is envelope-encrypted; an HMAC-SHA256 lookup hash backs the per-tenant uniqueness index. 
         * @summary Create a platform user. Mirrors the row into Keycloak.
         * @param {string} idempotencyKey 24-hour idempotency key (idem_&lt;ulid&gt;).
         * @param {CreateUserRequest} createUserRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createUser: async (idempotencyKey: string, createUserRequest: CreateUserRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'idempotencyKey' is not null or undefined
            assertParamExists('createUser', 'idempotencyKey', idempotencyKey)
            // verify required parameter 'createUserRequest' is not null or undefined
            assertParamExists('createUser', 'createUserRequest', createUserRequest)
            const localVarPath = `/v1/users`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication apiKeyAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json,application/problem+json';

            if (idempotencyKey != null) {
                localVarHeaderParameter['Idempotency-Key'] = String(idempotencyKey);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createUserRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Soft-delete a platform user. Disables the Keycloak user.
         * @param {string} ifMatch Weak ETag from a prior GET; rejects on mismatch with 412.
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteUser: async (ifMatch: string, userId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ifMatch' is not null or undefined
            assertParamExists('deleteUser', 'ifMatch', ifMatch)
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('deleteUser', 'userId', userId)
            const localVarPath = `/v1/users/{user_id}`
                .replace('{user_id}', encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication apiKeyAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/problem+json';

            if (ifMatch != null) {
                localVarHeaderParameter['If-Match'] = String(ifMatch);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Disable a platform user. Emits user.disabled.
         * @param {string} idempotencyKey 24-hour idempotency key (idem_&lt;ulid&gt;).
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        disableUser: async (idempotencyKey: string, userId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'idempotencyKey' is not null or undefined
            assertParamExists('disableUser', 'idempotencyKey', idempotencyKey)
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('disableUser', 'userId', userId)
            const localVarPath = `/v1/users/{user_id}/disable`
                .replace('{user_id}', encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication apiKeyAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json,application/problem+json';

            if (idempotencyKey != null) {
                localVarHeaderParameter['Idempotency-Key'] = String(idempotencyKey);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Enable a previously-disabled platform user.
         * @param {string} idempotencyKey 24-hour idempotency key (idem_&lt;ulid&gt;).
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        enableUser: async (idempotencyKey: string, userId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'idempotencyKey' is not null or undefined
            assertParamExists('enableUser', 'idempotencyKey', idempotencyKey)
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('enableUser', 'userId', userId)
            const localVarPath = `/v1/users/{user_id}/enable`
                .replace('{user_id}', encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication apiKeyAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json,application/problem+json';

            if (idempotencyKey != null) {
                localVarHeaderParameter['Idempotency-Key'] = String(idempotencyKey);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Fetch a platform user by id.
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUser: async (userId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('getUser', 'userId', userId)
            const localVarPath = `/v1/users/{user_id}`
                .replace('{user_id}', encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication apiKeyAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/json,application/problem+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Returns the platform users belonging to the caller\'s tenant. Email plaintext is returned (decrypted at the persistence boundary); the envelope columns stay on the server. Set the `email` query parameter to look up a single user by email (HMAC-prefix lookup; never sends plaintext to the DB). 
         * @summary List users in the caller\'s tenant.
         * @param {number} [limit] Max items to return (default 25, max 200).
         * @param {string} [cursor] Opaque pagination cursor; obtained from a previous response.
         * @param {string} [sort] Sort token. Default \&quot;-created_at\&quot;.
         * @param {string} [email] HMAC-prefix lookup; matches on email_lookup_hash.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listUsers: async (limit?: number, cursor?: string, sort?: string, email?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/v1/users`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication apiKeyAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (cursor !== undefined) {
                localVarQueryParameter['cursor'] = cursor;
            }

            if (sort !== undefined) {
                localVarQueryParameter['sort'] = sort;
            }

            if (email !== undefined) {
                localVarQueryParameter['email'] = email;
            }

            localVarHeaderParameter['Accept'] = 'application/json,application/problem+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Trigger an email-verification action via Keycloak.
         * @param {string} idempotencyKey 24-hour idempotency key (idem_&lt;ulid&gt;).
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        triggerEmailVerify: async (idempotencyKey: string, userId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'idempotencyKey' is not null or undefined
            assertParamExists('triggerEmailVerify', 'idempotencyKey', idempotencyKey)
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('triggerEmailVerify', 'userId', userId)
            const localVarPath = `/v1/users/{user_id}/verify-email`
                .replace('{user_id}', encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication apiKeyAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/problem+json';

            if (idempotencyKey != null) {
                localVarHeaderParameter['Idempotency-Key'] = String(idempotencyKey);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Phase 5 uses Keycloak\'s built-in SMTP (ExecuteActionsEmail with UPDATE_PASSWORD). Phase 6 swaps the transport to the Notifications module + Novu without changing this endpoint. 
         * @summary Trigger a password-reset email via Keycloak.
         * @param {string} idempotencyKey 24-hour idempotency key (idem_&lt;ulid&gt;).
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        triggerPasswordReset: async (idempotencyKey: string, userId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'idempotencyKey' is not null or undefined
            assertParamExists('triggerPasswordReset', 'idempotencyKey', idempotencyKey)
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('triggerPasswordReset', 'userId', userId)
            const localVarPath = `/v1/users/{user_id}/reset-password`
                .replace('{user_id}', encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication apiKeyAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Accept'] = 'application/problem+json';

            if (idempotencyKey != null) {
                localVarHeaderParameter['Idempotency-Key'] = String(idempotencyKey);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update a platform user. ETag concurrency control required.
         * @param {string} ifMatch Weak ETag from a prior GET; rejects on mismatch with 412.
         * @param {string} idempotencyKey 24-hour idempotency key (idem_&lt;ulid&gt;).
         * @param {string} userId 
         * @param {UpdateUserRequest} updateUserRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateUser: async (ifMatch: string, idempotencyKey: string, userId: string, updateUserRequest: UpdateUserRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ifMatch' is not null or undefined
            assertParamExists('updateUser', 'ifMatch', ifMatch)
            // verify required parameter 'idempotencyKey' is not null or undefined
            assertParamExists('updateUser', 'idempotencyKey', idempotencyKey)
            // verify required parameter 'userId' is not null or undefined
            assertParamExists('updateUser', 'userId', userId)
            // verify required parameter 'updateUserRequest' is not null or undefined
            assertParamExists('updateUser', 'updateUserRequest', updateUserRequest)
            const localVarPath = `/v1/users/{user_id}`
                .replace('{user_id}', encodeURIComponent(String(userId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            // authentication apiKeyAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            // authentication bearerAuth required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json,application/problem+json';

            if (ifMatch != null) {
                localVarHeaderParameter['If-Match'] = String(ifMatch);
            }
            if (idempotencyKey != null) {
                localVarHeaderParameter['Idempotency-Key'] = String(idempotencyKey);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateUserRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * UsersApi - functional programming interface
 */
export const UsersApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = UsersApiAxiosParamCreator(configuration)
    return {
        /**
         * Idempotent. The platform creates a row + a Keycloak user in the shared `saas-data-local` realm (per-Deployment realm lands in Phase 12). Email is envelope-encrypted; an HMAC-SHA256 lookup hash backs the per-tenant uniqueness index. 
         * @summary Create a platform user. Mirrors the row into Keycloak.
         * @param {string} idempotencyKey 24-hour idempotency key (idem_&lt;ulid&gt;).
         * @param {CreateUserRequest} createUserRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createUser(idempotencyKey: string, createUserRequest: CreateUserRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createUser(idempotencyKey, createUserRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.createUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Soft-delete a platform user. Disables the Keycloak user.
         * @param {string} ifMatch Weak ETag from a prior GET; rejects on mismatch with 412.
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteUser(ifMatch: string, userId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteUser(ifMatch, userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.deleteUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Disable a platform user. Emits user.disabled.
         * @param {string} idempotencyKey 24-hour idempotency key (idem_&lt;ulid&gt;).
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async disableUser(idempotencyKey: string, userId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.disableUser(idempotencyKey, userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.disableUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Enable a previously-disabled platform user.
         * @param {string} idempotencyKey 24-hour idempotency key (idem_&lt;ulid&gt;).
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async enableUser(idempotencyKey: string, userId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.enableUser(idempotencyKey, userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.enableUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Fetch a platform user by id.
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getUser(userId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getUser(userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.getUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Returns the platform users belonging to the caller\'s tenant. Email plaintext is returned (decrypted at the persistence boundary); the envelope columns stay on the server. Set the `email` query parameter to look up a single user by email (HMAC-prefix lookup; never sends plaintext to the DB). 
         * @summary List users in the caller\'s tenant.
         * @param {number} [limit] Max items to return (default 25, max 200).
         * @param {string} [cursor] Opaque pagination cursor; obtained from a previous response.
         * @param {string} [sort] Sort token. Default \&quot;-created_at\&quot;.
         * @param {string} [email] HMAC-prefix lookup; matches on email_lookup_hash.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listUsers(limit?: number, cursor?: string, sort?: string, email?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listUsers(limit, cursor, sort, email, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.listUsers']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Trigger an email-verification action via Keycloak.
         * @param {string} idempotencyKey 24-hour idempotency key (idem_&lt;ulid&gt;).
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async triggerEmailVerify(idempotencyKey: string, userId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.triggerEmailVerify(idempotencyKey, userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.triggerEmailVerify']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Phase 5 uses Keycloak\'s built-in SMTP (ExecuteActionsEmail with UPDATE_PASSWORD). Phase 6 swaps the transport to the Notifications module + Novu without changing this endpoint. 
         * @summary Trigger a password-reset email via Keycloak.
         * @param {string} idempotencyKey 24-hour idempotency key (idem_&lt;ulid&gt;).
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async triggerPasswordReset(idempotencyKey: string, userId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.triggerPasswordReset(idempotencyKey, userId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.triggerPasswordReset']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Update a platform user. ETag concurrency control required.
         * @param {string} ifMatch Weak ETag from a prior GET; rejects on mismatch with 412.
         * @param {string} idempotencyKey 24-hour idempotency key (idem_&lt;ulid&gt;).
         * @param {string} userId 
         * @param {UpdateUserRequest} updateUserRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateUser(ifMatch: string, idempotencyKey: string, userId: string, updateUserRequest: UpdateUserRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<UserResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateUser(ifMatch, idempotencyKey, userId, updateUserRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['UsersApi.updateUser']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * UsersApi - factory interface
 */
export const UsersApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = UsersApiFp(configuration)
    return {
        /**
         * Idempotent. The platform creates a row + a Keycloak user in the shared `saas-data-local` realm (per-Deployment realm lands in Phase 12). Email is envelope-encrypted; an HMAC-SHA256 lookup hash backs the per-tenant uniqueness index. 
         * @summary Create a platform user. Mirrors the row into Keycloak.
         * @param {string} idempotencyKey 24-hour idempotency key (idem_&lt;ulid&gt;).
         * @param {CreateUserRequest} createUserRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createUser(idempotencyKey: string, createUserRequest: CreateUserRequest, options?: RawAxiosRequestConfig): AxiosPromise<UserResponse> {
            return localVarFp.createUser(idempotencyKey, createUserRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Soft-delete a platform user. Disables the Keycloak user.
         * @param {string} ifMatch Weak ETag from a prior GET; rejects on mismatch with 412.
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteUser(ifMatch: string, userId: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteUser(ifMatch, userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Disable a platform user. Emits user.disabled.
         * @param {string} idempotencyKey 24-hour idempotency key (idem_&lt;ulid&gt;).
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        disableUser(idempotencyKey: string, userId: string, options?: RawAxiosRequestConfig): AxiosPromise<UserResponse> {
            return localVarFp.disableUser(idempotencyKey, userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Enable a previously-disabled platform user.
         * @param {string} idempotencyKey 24-hour idempotency key (idem_&lt;ulid&gt;).
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        enableUser(idempotencyKey: string, userId: string, options?: RawAxiosRequestConfig): AxiosPromise<UserResponse> {
            return localVarFp.enableUser(idempotencyKey, userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Fetch a platform user by id.
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getUser(userId: string, options?: RawAxiosRequestConfig): AxiosPromise<UserResponse> {
            return localVarFp.getUser(userId, options).then((request) => request(axios, basePath));
        },
        /**
         * Returns the platform users belonging to the caller\'s tenant. Email plaintext is returned (decrypted at the persistence boundary); the envelope columns stay on the server. Set the `email` query parameter to look up a single user by email (HMAC-prefix lookup; never sends plaintext to the DB). 
         * @summary List users in the caller\'s tenant.
         * @param {number} [limit] Max items to return (default 25, max 200).
         * @param {string} [cursor] Opaque pagination cursor; obtained from a previous response.
         * @param {string} [sort] Sort token. Default \&quot;-created_at\&quot;.
         * @param {string} [email] HMAC-prefix lookup; matches on email_lookup_hash.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listUsers(limit?: number, cursor?: string, sort?: string, email?: string, options?: RawAxiosRequestConfig): AxiosPromise<UserListResponse> {
            return localVarFp.listUsers(limit, cursor, sort, email, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Trigger an email-verification action via Keycloak.
         * @param {string} idempotencyKey 24-hour idempotency key (idem_&lt;ulid&gt;).
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        triggerEmailVerify(idempotencyKey: string, userId: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.triggerEmailVerify(idempotencyKey, userId, options).then((request) => request(axios, basePath));
        },
        /**
         * Phase 5 uses Keycloak\'s built-in SMTP (ExecuteActionsEmail with UPDATE_PASSWORD). Phase 6 swaps the transport to the Notifications module + Novu without changing this endpoint. 
         * @summary Trigger a password-reset email via Keycloak.
         * @param {string} idempotencyKey 24-hour idempotency key (idem_&lt;ulid&gt;).
         * @param {string} userId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        triggerPasswordReset(idempotencyKey: string, userId: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.triggerPasswordReset(idempotencyKey, userId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update a platform user. ETag concurrency control required.
         * @param {string} ifMatch Weak ETag from a prior GET; rejects on mismatch with 412.
         * @param {string} idempotencyKey 24-hour idempotency key (idem_&lt;ulid&gt;).
         * @param {string} userId 
         * @param {UpdateUserRequest} updateUserRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateUser(ifMatch: string, idempotencyKey: string, userId: string, updateUserRequest: UpdateUserRequest, options?: RawAxiosRequestConfig): AxiosPromise<UserResponse> {
            return localVarFp.updateUser(ifMatch, idempotencyKey, userId, updateUserRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * UsersApi - interface
 */
export interface UsersApiInterface {
    /**
     * Idempotent. The platform creates a row + a Keycloak user in the shared `saas-data-local` realm (per-Deployment realm lands in Phase 12). Email is envelope-encrypted; an HMAC-SHA256 lookup hash backs the per-tenant uniqueness index. 
     * @summary Create a platform user. Mirrors the row into Keycloak.
     * @param {string} idempotencyKey 24-hour idempotency key (idem_&lt;ulid&gt;).
     * @param {CreateUserRequest} createUserRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createUser(idempotencyKey: string, createUserRequest: CreateUserRequest, options?: RawAxiosRequestConfig): AxiosPromise<UserResponse>;

    /**
     * 
     * @summary Soft-delete a platform user. Disables the Keycloak user.
     * @param {string} ifMatch Weak ETag from a prior GET; rejects on mismatch with 412.
     * @param {string} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteUser(ifMatch: string, userId: string, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Disable a platform user. Emits user.disabled.
     * @param {string} idempotencyKey 24-hour idempotency key (idem_&lt;ulid&gt;).
     * @param {string} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    disableUser(idempotencyKey: string, userId: string, options?: RawAxiosRequestConfig): AxiosPromise<UserResponse>;

    /**
     * 
     * @summary Enable a previously-disabled platform user.
     * @param {string} idempotencyKey 24-hour idempotency key (idem_&lt;ulid&gt;).
     * @param {string} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    enableUser(idempotencyKey: string, userId: string, options?: RawAxiosRequestConfig): AxiosPromise<UserResponse>;

    /**
     * 
     * @summary Fetch a platform user by id.
     * @param {string} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getUser(userId: string, options?: RawAxiosRequestConfig): AxiosPromise<UserResponse>;

    /**
     * Returns the platform users belonging to the caller\'s tenant. Email plaintext is returned (decrypted at the persistence boundary); the envelope columns stay on the server. Set the `email` query parameter to look up a single user by email (HMAC-prefix lookup; never sends plaintext to the DB). 
     * @summary List users in the caller\'s tenant.
     * @param {number} [limit] Max items to return (default 25, max 200).
     * @param {string} [cursor] Opaque pagination cursor; obtained from a previous response.
     * @param {string} [sort] Sort token. Default \&quot;-created_at\&quot;.
     * @param {string} [email] HMAC-prefix lookup; matches on email_lookup_hash.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listUsers(limit?: number, cursor?: string, sort?: string, email?: string, options?: RawAxiosRequestConfig): AxiosPromise<UserListResponse>;

    /**
     * 
     * @summary Trigger an email-verification action via Keycloak.
     * @param {string} idempotencyKey 24-hour idempotency key (idem_&lt;ulid&gt;).
     * @param {string} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    triggerEmailVerify(idempotencyKey: string, userId: string, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * Phase 5 uses Keycloak\'s built-in SMTP (ExecuteActionsEmail with UPDATE_PASSWORD). Phase 6 swaps the transport to the Notifications module + Novu without changing this endpoint. 
     * @summary Trigger a password-reset email via Keycloak.
     * @param {string} idempotencyKey 24-hour idempotency key (idem_&lt;ulid&gt;).
     * @param {string} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    triggerPasswordReset(idempotencyKey: string, userId: string, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @summary Update a platform user. ETag concurrency control required.
     * @param {string} ifMatch Weak ETag from a prior GET; rejects on mismatch with 412.
     * @param {string} idempotencyKey 24-hour idempotency key (idem_&lt;ulid&gt;).
     * @param {string} userId 
     * @param {UpdateUserRequest} updateUserRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateUser(ifMatch: string, idempotencyKey: string, userId: string, updateUserRequest: UpdateUserRequest, options?: RawAxiosRequestConfig): AxiosPromise<UserResponse>;

}

/**
 * UsersApi - object-oriented interface
 */
export class UsersApi extends BaseAPI implements UsersApiInterface {
    /**
     * Idempotent. The platform creates a row + a Keycloak user in the shared `saas-data-local` realm (per-Deployment realm lands in Phase 12). Email is envelope-encrypted; an HMAC-SHA256 lookup hash backs the per-tenant uniqueness index. 
     * @summary Create a platform user. Mirrors the row into Keycloak.
     * @param {string} idempotencyKey 24-hour idempotency key (idem_&lt;ulid&gt;).
     * @param {CreateUserRequest} createUserRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createUser(idempotencyKey: string, createUserRequest: CreateUserRequest, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).createUser(idempotencyKey, createUserRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Soft-delete a platform user. Disables the Keycloak user.
     * @param {string} ifMatch Weak ETag from a prior GET; rejects on mismatch with 412.
     * @param {string} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteUser(ifMatch: string, userId: string, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).deleteUser(ifMatch, userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Disable a platform user. Emits user.disabled.
     * @param {string} idempotencyKey 24-hour idempotency key (idem_&lt;ulid&gt;).
     * @param {string} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public disableUser(idempotencyKey: string, userId: string, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).disableUser(idempotencyKey, userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Enable a previously-disabled platform user.
     * @param {string} idempotencyKey 24-hour idempotency key (idem_&lt;ulid&gt;).
     * @param {string} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public enableUser(idempotencyKey: string, userId: string, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).enableUser(idempotencyKey, userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Fetch a platform user by id.
     * @param {string} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getUser(userId: string, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).getUser(userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Returns the platform users belonging to the caller\'s tenant. Email plaintext is returned (decrypted at the persistence boundary); the envelope columns stay on the server. Set the `email` query parameter to look up a single user by email (HMAC-prefix lookup; never sends plaintext to the DB). 
     * @summary List users in the caller\'s tenant.
     * @param {number} [limit] Max items to return (default 25, max 200).
     * @param {string} [cursor] Opaque pagination cursor; obtained from a previous response.
     * @param {string} [sort] Sort token. Default \&quot;-created_at\&quot;.
     * @param {string} [email] HMAC-prefix lookup; matches on email_lookup_hash.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listUsers(limit?: number, cursor?: string, sort?: string, email?: string, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).listUsers(limit, cursor, sort, email, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Trigger an email-verification action via Keycloak.
     * @param {string} idempotencyKey 24-hour idempotency key (idem_&lt;ulid&gt;).
     * @param {string} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public triggerEmailVerify(idempotencyKey: string, userId: string, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).triggerEmailVerify(idempotencyKey, userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Phase 5 uses Keycloak\'s built-in SMTP (ExecuteActionsEmail with UPDATE_PASSWORD). Phase 6 swaps the transport to the Notifications module + Novu without changing this endpoint. 
     * @summary Trigger a password-reset email via Keycloak.
     * @param {string} idempotencyKey 24-hour idempotency key (idem_&lt;ulid&gt;).
     * @param {string} userId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public triggerPasswordReset(idempotencyKey: string, userId: string, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).triggerPasswordReset(idempotencyKey, userId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update a platform user. ETag concurrency control required.
     * @param {string} ifMatch Weak ETag from a prior GET; rejects on mismatch with 412.
     * @param {string} idempotencyKey 24-hour idempotency key (idem_&lt;ulid&gt;).
     * @param {string} userId 
     * @param {UpdateUserRequest} updateUserRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateUser(ifMatch: string, idempotencyKey: string, userId: string, updateUserRequest: UpdateUserRequest, options?: RawAxiosRequestConfig) {
        return UsersApiFp(this.configuration).updateUser(ifMatch, idempotencyKey, userId, updateUserRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

