// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attempts.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAttemptsForUser = `-- name: CountAttemptsForUser :one
SELECT COUNT(*)::int FROM attempts WHERE user_id = $1
`

func (q *Queries) CountAttemptsForUser(ctx context.Context, userID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countAttemptsForUser, userID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getItemForAttempt = `-- name: GetItemForAttempt :one
SELECT id, status, exam_type, section, subject, grade_level, unit, topic, skill, cognitive_level, difficulty_target, difficulty_calibrated, question_archetype, question_text, correct_answer, explanation, estimated_time_seconds, concept_fingerprint, solution_fingerprint, surface_fingerprint, normalized_text_hash, stem_hash, choices_hash, similarity_cluster_id, source, model_name, generation_prompt_version, review_prompt_version, quality_score, novelty_score, ambiguity_score, novelty_notes, created_at, updated_at
FROM items
WHERE id = $1
  AND status = 'accepted'
`

// Returns the full item row including correct_answer + explanation. Callers
// compare the user's choice to correct_answer in code rather than at the SQL
// layer so they can return the same row to the client (with the answer + why
// each distractor was wrong). The item must be accepted.
func (q *Queries) GetItemForAttempt(ctx context.Context, id uuid.UUID) (Item, error) {
	row := q.db.QueryRow(ctx, getItemForAttempt, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.ExamType,
		&i.Section,
		&i.Subject,
		&i.GradeLevel,
		&i.Unit,
		&i.Topic,
		&i.Skill,
		&i.CognitiveLevel,
		&i.DifficultyTarget,
		&i.DifficultyCalibrated,
		&i.QuestionArchetype,
		&i.QuestionText,
		&i.CorrectAnswer,
		&i.Explanation,
		&i.EstimatedTimeSeconds,
		&i.ConceptFingerprint,
		&i.SolutionFingerprint,
		&i.SurfaceFingerprint,
		&i.NormalizedTextHash,
		&i.StemHash,
		&i.ChoicesHash,
		&i.SimilarityClusterID,
		&i.Source,
		&i.ModelName,
		&i.GenerationPromptVersion,
		&i.ReviewPromptVersion,
		&i.QualityScore,
		&i.NoveltyScore,
		&i.AmbiguityScore,
		&i.NoveltyNotes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAttempt = `-- name: InsertAttempt :one
INSERT INTO attempts (user_id, item_id, choice_key, correct, time_taken_ms, hint_used, served_at, answered_at)
VALUES ($1, $2, $3, $4, $5, $6, COALESCE($7::timestamptz, now()), now())
RETURNING id, user_id, item_id, choice_key, correct, time_taken_ms, hint_used, served_at, answered_at
`

type InsertAttemptParams struct {
	UserID      uuid.UUID          `json:"user_id"`
	ItemID      uuid.UUID          `json:"item_id"`
	ChoiceKey   *string            `json:"choice_key"`
	Correct     *bool              `json:"correct"`
	TimeTakenMs *int32             `json:"time_taken_ms"`
	HintUsed    bool               `json:"hint_used"`
	Column7     pgtype.Timestamptz `json:"column_7"`
}

// One row per answered item per user. choice_key + correct are nullable to
// support a "served but skipped" path later (Phase 4 mistake-clinic).
func (q *Queries) InsertAttempt(ctx context.Context, arg InsertAttemptParams) (Attempt, error) {
	row := q.db.QueryRow(ctx, insertAttempt,
		arg.UserID,
		arg.ItemID,
		arg.ChoiceKey,
		arg.Correct,
		arg.TimeTakenMs,
		arg.HintUsed,
		arg.Column7,
	)
	var i Attempt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ItemID,
		&i.ChoiceKey,
		&i.Correct,
		&i.TimeTakenMs,
		&i.HintUsed,
		&i.ServedAt,
		&i.AnsweredAt,
	)
	return i, err
}

const listItemChoicesByID = `-- name: ListItemChoicesByID :many
SELECT item_id, choice_key, choice_text, distractor_rationale
FROM item_choices
WHERE item_id = $1
ORDER BY choice_key
`

// Same contract as ListItemChoices but with explicit name to avoid collision.
func (q *Queries) ListItemChoicesByID(ctx context.Context, itemID uuid.UUID) ([]ItemChoice, error) {
	rows, err := q.db.Query(ctx, listItemChoicesByID, itemID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ItemChoice
	for rows.Next() {
		var i ItemChoice
		if err := rows.Scan(
			&i.ItemID,
			&i.ChoiceKey,
			&i.ChoiceText,
			&i.DistractorRationale,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentAttemptsForUser = `-- name: ListRecentAttemptsForUser :many
SELECT a.id, a.user_id, a.item_id, a.choice_key, a.correct, a.time_taken_ms, a.hint_used, a.served_at, a.answered_at, i.exam_type, i.section, i.topic, i.skill, i.difficulty_target
FROM attempts a
JOIN items   i ON i.id = a.item_id
WHERE a.user_id = $1
ORDER BY a.served_at DESC
LIMIT $2
`

type ListRecentAttemptsForUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
}

type ListRecentAttemptsForUserRow struct {
	ID               uuid.UUID          `json:"id"`
	UserID           uuid.UUID          `json:"user_id"`
	ItemID           uuid.UUID          `json:"item_id"`
	ChoiceKey        *string            `json:"choice_key"`
	Correct          *bool              `json:"correct"`
	TimeTakenMs      *int32             `json:"time_taken_ms"`
	HintUsed         bool               `json:"hint_used"`
	ServedAt         pgtype.Timestamptz `json:"served_at"`
	AnsweredAt       pgtype.Timestamptz `json:"answered_at"`
	ExamType         string             `json:"exam_type"`
	Section          string             `json:"section"`
	Topic            string             `json:"topic"`
	Skill            string             `json:"skill"`
	DifficultyTarget string             `json:"difficulty_target"`
}

func (q *Queries) ListRecentAttemptsForUser(ctx context.Context, arg ListRecentAttemptsForUserParams) ([]ListRecentAttemptsForUserRow, error) {
	rows, err := q.db.Query(ctx, listRecentAttemptsForUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentAttemptsForUserRow
	for rows.Next() {
		var i ListRecentAttemptsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ItemID,
			&i.ChoiceKey,
			&i.Correct,
			&i.TimeTakenMs,
			&i.HintUsed,
			&i.ServedAt,
			&i.AnsweredAt,
			&i.ExamType,
			&i.Section,
			&i.Topic,
			&i.Skill,
			&i.DifficultyTarget,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markItemServed = `-- name: MarkItemServed :exec
INSERT INTO served_items (user_id, item_id)
VALUES ($1, $2)
ON CONFLICT (user_id, item_id) DO NOTHING
`

type MarkItemServedParams struct {
	UserID uuid.UUID `json:"user_id"`
	ItemID uuid.UUID `json:"item_id"`
}

// Idempotent: ON CONFLICT DO NOTHING means re-serving (e.g. retry after a
// network error) doesn't fail. The PRIMARY KEY (user_id,item_id) covers it.
func (q *Queries) MarkItemServed(ctx context.Context, arg MarkItemServedParams) error {
	_, err := q.db.Exec(ctx, markItemServed, arg.UserID, arg.ItemID)
	return err
}

const pickUnservedItemsForUser = `-- name: PickUnservedItemsForUser :many
SELECT i.id, i.exam_type, i.section, i.subject, i.grade_level, i.unit, i.topic,
       i.skill, i.cognitive_level, i.difficulty_target, i.question_archetype,
       i.question_text, i.estimated_time_seconds
FROM items i
WHERE i.status = 'accepted'
  AND ($1::text IS NULL OR i.exam_type = $1)
  AND ($2::text   IS NULL OR i.section   = $2)
  AND ($3::text     IS NULL OR i.topic     = $3)
  AND NOT EXISTS (
      SELECT 1 FROM served_items s
      WHERE s.user_id = $4
        AND s.item_id = i.id
  )
ORDER BY random()
LIMIT $5
`

type PickUnservedItemsForUserParams struct {
	ExamType   *string   `json:"exam_type"`
	Section    *string   `json:"section"`
	Topic      *string   `json:"topic"`
	UserID     uuid.UUID `json:"user_id"`
	LimitCount int32     `json:"limit_count"`
}

type PickUnservedItemsForUserRow struct {
	ID                   uuid.UUID `json:"id"`
	ExamType             string    `json:"exam_type"`
	Section              string    `json:"section"`
	Subject              string    `json:"subject"`
	GradeLevel           string    `json:"grade_level"`
	Unit                 string    `json:"unit"`
	Topic                string    `json:"topic"`
	Skill                string    `json:"skill"`
	CognitiveLevel       string    `json:"cognitive_level"`
	DifficultyTarget     string    `json:"difficulty_target"`
	QuestionArchetype    string    `json:"question_archetype"`
	QuestionText         string    `json:"question_text"`
	EstimatedTimeSeconds int32     `json:"estimated_time_seconds"`
}

// Returns up to limit_count accepted items the user has never been served.
// Filters by exam_type/section/topic if provided (NULL = no filter).
// Random ordering keeps practice fresh; for ~10k items the cost is fine.
func (q *Queries) PickUnservedItemsForUser(ctx context.Context, arg PickUnservedItemsForUserParams) ([]PickUnservedItemsForUserRow, error) {
	rows, err := q.db.Query(ctx, pickUnservedItemsForUser,
		arg.ExamType,
		arg.Section,
		arg.Topic,
		arg.UserID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PickUnservedItemsForUserRow
	for rows.Next() {
		var i PickUnservedItemsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.ExamType,
			&i.Section,
			&i.Subject,
			&i.GradeLevel,
			&i.Unit,
			&i.Topic,
			&i.Skill,
			&i.CognitiveLevel,
			&i.DifficultyTarget,
			&i.QuestionArchetype,
			&i.QuestionText,
			&i.EstimatedTimeSeconds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const summarizeMasteryByTopic = `-- name: SummarizeMasteryByTopic :many
SELECT i.exam_type,
       i.section,
       i.topic,
       COUNT(*)::int                                     AS attempts,
       SUM(CASE WHEN a.correct THEN 1 ELSE 0 END)::int   AS correct_count,
       AVG(CASE WHEN a.correct THEN 1.0 ELSE 0.0 END)    AS accuracy
FROM attempts a
JOIN items   i ON i.id = a.item_id
WHERE a.user_id = $1
  AND a.choice_key IS NOT NULL
GROUP BY i.exam_type, i.section, i.topic
ORDER BY accuracy ASC
LIMIT $2
`

type SummarizeMasteryByTopicParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
}

type SummarizeMasteryByTopicRow struct {
	ExamType     string  `json:"exam_type"`
	Section      string  `json:"section"`
	Topic        string  `json:"topic"`
	Attempts     int32   `json:"attempts"`
	CorrectCount int32   `json:"correct_count"`
	Accuracy     float64 `json:"accuracy"`
}

// Per-topic accuracy + counts for the user. Drives the weakness heatmap
// (spec §4 #8). LIMIT keeps the payload bounded.
func (q *Queries) SummarizeMasteryByTopic(ctx context.Context, arg SummarizeMasteryByTopicParams) ([]SummarizeMasteryByTopicRow, error) {
	rows, err := q.db.Query(ctx, summarizeMasteryByTopic, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SummarizeMasteryByTopicRow
	for rows.Next() {
		var i SummarizeMasteryByTopicRow
		if err := rows.Scan(
			&i.ExamType,
			&i.Section,
			&i.Topic,
			&i.Attempts,
			&i.CorrectCount,
			&i.Accuracy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
