// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: calibration.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const itemsToCalibrate = `-- name: ItemsToCalibrate :many
SELECT i.id,
       COUNT(*)::int                                  AS attempts,
       AVG(CASE WHEN a.correct THEN 1.0 ELSE 0.0 END) AS accuracy
FROM items    i
JOIN attempts a ON a.item_id = i.id
WHERE a.correct IS NOT NULL
GROUP BY i.id
HAVING COUNT(*) >= $1::int
`

type ItemsToCalibrateRow struct {
	ID       uuid.UUID `json:"id"`
	Attempts int32     `json:"attempts"`
	Accuracy float64   `json:"accuracy"`
}

// Items with at least min_attempts answered. Calibration computes a
// per-item accuracy and stores it in items.difficulty_calibrated.
func (q *Queries) ItemsToCalibrate(ctx context.Context, minAttempts int32) ([]ItemsToCalibrateRow, error) {
	rows, err := q.db.Query(ctx, itemsToCalibrate, minAttempts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ItemsToCalibrateRow
	for rows.Next() {
		var i ItemsToCalibrateRow
		if err := rows.Scan(&i.ID, &i.Attempts, &i.Accuracy); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateItemCalibratedDifficulty = `-- name: UpdateItemCalibratedDifficulty :exec
UPDATE items
SET difficulty_calibrated = $2,
    updated_at            = now()
WHERE id = $1
`

type UpdateItemCalibratedDifficultyParams struct {
	ID                   uuid.UUID      `json:"id"`
	DifficultyCalibrated pgtype.Numeric `json:"difficulty_calibrated"`
}

func (q *Queries) UpdateItemCalibratedDifficulty(ctx context.Context, arg UpdateItemCalibratedDifficultyParams) error {
	_, err := q.db.Exec(ctx, updateItemCalibratedDifficulty, arg.ID, arg.DifficultyCalibrated)
	return err
}
