// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countEventsByTypeSince = `-- name: CountEventsByTypeSince :one
SELECT COUNT(*)::int
FROM events
WHERE event_type = $1
  AND created_at >= $2
`

type CountEventsByTypeSinceParams struct {
	EventType string             `json:"event_type"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CountEventsByTypeSince(ctx context.Context, arg CountEventsByTypeSinceParams) (int32, error) {
	row := q.db.QueryRow(ctx, countEventsByTypeSince, arg.EventType, arg.CreatedAt)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const listRecentEventsByType = `-- name: ListRecentEventsByType :many
SELECT id, event_type, user_id, item_id, payload, created_at
FROM events
WHERE event_type = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListRecentEventsByTypeParams struct {
	EventType string `json:"event_type"`
	Limit     int32  `json:"limit"`
}

func (q *Queries) ListRecentEventsByType(ctx context.Context, arg ListRecentEventsByTypeParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listRecentEventsByType, arg.EventType, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Event
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.UserID,
			&i.ItemID,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordEvent = `-- name: RecordEvent :exec
INSERT INTO events (event_type, user_id, item_id, payload)
VALUES ($1, $2, $3, COALESCE($4::jsonb, '{}'::jsonb))
`

type RecordEventParams struct {
	EventType string     `json:"event_type"`
	UserID    *uuid.UUID `json:"user_id"`
	ItemID    *uuid.UUID `json:"item_id"`
	Column4   []byte     `json:"column_4"`
}

func (q *Queries) RecordEvent(ctx context.Context, arg RecordEventParams) error {
	_, err := q.db.Exec(ctx, recordEvent,
		arg.EventType,
		arg.UserID,
		arg.ItemID,
		arg.Column4,
	)
	return err
}
