// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Attempt struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	ItemID      uuid.UUID          `json:"item_id"`
	ChoiceKey   *string            `json:"choice_key"`
	Correct     *bool              `json:"correct"`
	TimeTakenMs *int32             `json:"time_taken_ms"`
	HintUsed    bool               `json:"hint_used"`
	ServedAt    pgtype.Timestamptz `json:"served_at"`
	AnsweredAt  pgtype.Timestamptz `json:"answered_at"`
}

type Item struct {
	ID                      uuid.UUID          `json:"id"`
	Status                  string             `json:"status"`
	ExamType                string             `json:"exam_type"`
	Section                 string             `json:"section"`
	Subject                 string             `json:"subject"`
	GradeLevel              string             `json:"grade_level"`
	Unit                    string             `json:"unit"`
	Topic                   string             `json:"topic"`
	Skill                   string             `json:"skill"`
	CognitiveLevel          string             `json:"cognitive_level"`
	DifficultyTarget        string             `json:"difficulty_target"`
	DifficultyCalibrated    pgtype.Numeric     `json:"difficulty_calibrated"`
	QuestionArchetype       string             `json:"question_archetype"`
	QuestionText            string             `json:"question_text"`
	CorrectAnswer           string             `json:"correct_answer"`
	Explanation             string             `json:"explanation"`
	EstimatedTimeSeconds    int32              `json:"estimated_time_seconds"`
	ConceptFingerprint      string             `json:"concept_fingerprint"`
	SolutionFingerprint     string             `json:"solution_fingerprint"`
	SurfaceFingerprint      string             `json:"surface_fingerprint"`
	NormalizedTextHash      string             `json:"normalized_text_hash"`
	StemHash                string             `json:"stem_hash"`
	ChoicesHash             string             `json:"choices_hash"`
	SimilarityClusterID     *uuid.UUID         `json:"similarity_cluster_id"`
	Source                  string             `json:"source"`
	ModelName               *string            `json:"model_name"`
	GenerationPromptVersion *string            `json:"generation_prompt_version"`
	ReviewPromptVersion     *string            `json:"review_prompt_version"`
	QualityScore            pgtype.Numeric     `json:"quality_score"`
	NoveltyScore            pgtype.Numeric     `json:"novelty_score"`
	AmbiguityScore          pgtype.Numeric     `json:"ambiguity_score"`
	NoveltyNotes            string             `json:"novelty_notes"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
}

type ItemChoice struct {
	ItemID              uuid.UUID `json:"item_id"`
	ChoiceKey           string    `json:"choice_key"`
	ChoiceText          string    `json:"choice_text"`
	DistractorRationale string    `json:"distractor_rationale"`
}

type ItemTag struct {
	ItemID uuid.UUID `json:"item_id"`
	Tag    string    `json:"tag"`
}

type OtpChallenge struct {
	ID          uuid.UUID          `json:"id"`
	Channel     string             `json:"channel"`
	Identifier  string             `json:"identifier"`
	CodeHash    *string            `json:"code_hash"`
	ProviderRef *string            `json:"provider_ref"`
	Attempts    int32              `json:"attempts"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt  pgtype.Timestamptz `json:"consumed_at"`
	Ip          *string            `json:"ip"`
	Ua          *string            `json:"ua"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ServedItem struct {
	UserID   uuid.UUID          `json:"user_id"`
	ItemID   uuid.UUID          `json:"item_id"`
	ServedAt pgtype.Timestamptz `json:"served_at"`
}

type Session struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	RefreshHash string             `json:"refresh_hash"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
	Ip          *string            `json:"ip"`
	Ua          *string            `json:"ua"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	LastSeenAt  pgtype.Timestamptz `json:"last_seen_at"`
}

type SimilarityCluster struct {
	ID        uuid.UUID          `json:"id"`
	Label     string             `json:"label"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID          uuid.UUID          `json:"id"`
	Email       *string            `json:"email"`
	Phone       *string            `json:"phone"`
	Nickname    string             `json:"nickname"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
}
