// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: otp.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const consumeOTPChallenge = `-- name: ConsumeOTPChallenge :exec
UPDATE otp_challenges
SET consumed_at = now()
WHERE id = $1
  AND consumed_at IS NULL
`

func (q *Queries) ConsumeOTPChallenge(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, consumeOTPChallenge, id)
	return err
}

const countRecentOTPChallengesForIdentifier = `-- name: CountRecentOTPChallengesForIdentifier :one
SELECT COUNT(*)::int
FROM otp_challenges
WHERE identifier = $1
  AND channel    = $2
  AND created_at > now() - $3::interval
`

type CountRecentOTPChallengesForIdentifierParams struct {
	Identifier string          `json:"identifier"`
	Channel    string          `json:"channel"`
	Column3    pgtype.Interval `json:"column_3"`
}

// Used as a lightweight rate-limiter on the start path. The caller decides
// the lookback window so the same query can serve "last minute" and
// "last hour" buckets.
func (q *Queries) CountRecentOTPChallengesForIdentifier(ctx context.Context, arg CountRecentOTPChallengesForIdentifierParams) (int32, error) {
	row := q.db.QueryRow(ctx, countRecentOTPChallengesForIdentifier, arg.Identifier, arg.Channel, arg.Column3)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createEmailOTPChallenge = `-- name: CreateEmailOTPChallenge :one
INSERT INTO otp_challenges (channel, identifier, code_hash, expires_at, ip, ua)
VALUES ('email', $1, $2, $3, $4, $5)
RETURNING id, channel, identifier, code_hash, provider_ref, attempts, expires_at, consumed_at, ip, ua, created_at
`

type CreateEmailOTPChallengeParams struct {
	Identifier string             `json:"identifier"`
	CodeHash   *string            `json:"code_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	Ip         *string            `json:"ip"`
	Ua         *string            `json:"ua"`
}

// code_hash carries bcrypt(code); we own the secret on the email path.
func (q *Queries) CreateEmailOTPChallenge(ctx context.Context, arg CreateEmailOTPChallengeParams) (OtpChallenge, error) {
	row := q.db.QueryRow(ctx, createEmailOTPChallenge,
		arg.Identifier,
		arg.CodeHash,
		arg.ExpiresAt,
		arg.Ip,
		arg.Ua,
	)
	var i OtpChallenge
	err := row.Scan(
		&i.ID,
		&i.Channel,
		&i.Identifier,
		&i.CodeHash,
		&i.ProviderRef,
		&i.Attempts,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.Ip,
		&i.Ua,
		&i.CreatedAt,
	)
	return i, err
}

const createSMSOTPChallenge = `-- name: CreateSMSOTPChallenge :one
INSERT INTO otp_challenges (channel, identifier, provider_ref, expires_at, ip, ua)
VALUES ('sms', $1, $2, $3, $4, $5)
RETURNING id, channel, identifier, code_hash, provider_ref, attempts, expires_at, consumed_at, ip, ua, created_at
`

type CreateSMSOTPChallengeParams struct {
	Identifier  string             `json:"identifier"`
	ProviderRef *string            `json:"provider_ref"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	Ip          *string            `json:"ip"`
	Ua          *string            `json:"ua"`
}

// provider_ref is the Twilio Verify SID; Twilio holds the secret on the SMS path.
func (q *Queries) CreateSMSOTPChallenge(ctx context.Context, arg CreateSMSOTPChallengeParams) (OtpChallenge, error) {
	row := q.db.QueryRow(ctx, createSMSOTPChallenge,
		arg.Identifier,
		arg.ProviderRef,
		arg.ExpiresAt,
		arg.Ip,
		arg.Ua,
	)
	var i OtpChallenge
	err := row.Scan(
		&i.ID,
		&i.Channel,
		&i.Identifier,
		&i.CodeHash,
		&i.ProviderRef,
		&i.Attempts,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.Ip,
		&i.Ua,
		&i.CreatedAt,
	)
	return i, err
}

const getOTPChallengeByID = `-- name: GetOTPChallengeByID :one
SELECT id, channel, identifier, code_hash, provider_ref, attempts, expires_at, consumed_at, ip, ua, created_at
FROM otp_challenges
WHERE id = $1
`

func (q *Queries) GetOTPChallengeByID(ctx context.Context, id uuid.UUID) (OtpChallenge, error) {
	row := q.db.QueryRow(ctx, getOTPChallengeByID, id)
	var i OtpChallenge
	err := row.Scan(
		&i.ID,
		&i.Channel,
		&i.Identifier,
		&i.CodeHash,
		&i.ProviderRef,
		&i.Attempts,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.Ip,
		&i.Ua,
		&i.CreatedAt,
	)
	return i, err
}

const incrementOTPAttempts = `-- name: IncrementOTPAttempts :one
UPDATE otp_challenges
SET attempts = attempts + 1
WHERE id = $1
RETURNING id, channel, identifier, code_hash, provider_ref, attempts, expires_at, consumed_at, ip, ua, created_at
`

func (q *Queries) IncrementOTPAttempts(ctx context.Context, id uuid.UUID) (OtpChallenge, error) {
	row := q.db.QueryRow(ctx, incrementOTPAttempts, id)
	var i OtpChallenge
	err := row.Scan(
		&i.ID,
		&i.Channel,
		&i.Identifier,
		&i.CodeHash,
		&i.ProviderRef,
		&i.Attempts,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.Ip,
		&i.Ua,
		&i.CreatedAt,
	)
	return i, err
}
