// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	ConsumeOTPChallenge(ctx context.Context, id uuid.UUID) error
	CountAcceptedItems(ctx context.Context) (int64, error)
	CountAttemptsForUser(ctx context.Context, userID uuid.UUID) (int32, error)
	CountEventsByTypeSince(ctx context.Context, arg CountEventsByTypeSinceParams) (int32, error)
	CountItems(ctx context.Context) (int64, error)
	CountItemsNeedingReview(ctx context.Context) (int32, error)
	// Used as a lightweight rate-limiter on the start path. The caller decides
	// the lookback window so the same query can serve "last minute" and
	// "last hour" buckets.
	CountRecentOTPChallengesForIdentifier(ctx context.Context, arg CountRecentOTPChallengesForIdentifierParams) (int32, error)
	// code_hash carries bcrypt(code); we own the secret on the email path.
	CreateEmailOTPChallenge(ctx context.Context, arg CreateEmailOTPChallengeParams) (OtpChallenge, error)
	// provider_ref is the Twilio Verify SID; Twilio holds the secret on the SMS path.
	CreateSMSOTPChallenge(ctx context.Context, arg CreateSMSOTPChallengeParams) (OtpChallenge, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetActiveSessionByRefreshHash(ctx context.Context, refreshHash string) (Session, error)
	// Near-dup detector: returns the first accepted item that matches BOTH
	// concept_fingerprint AND solution_fingerprint. Empty fingerprints don't
	// count (they're the placeholder in items not authored by the new pipeline).
	GetItemByConceptSolutionFingerprint(ctx context.Context, arg GetItemByConceptSolutionFingerprintParams) (Item, error)
	GetItemByID(ctx context.Context, id uuid.UUID) (Item, error)
	GetItemByNormalizedHash(ctx context.Context, normalizedTextHash string) (Item, error)
	// Returns the full item row including correct_answer + explanation. Callers
	// compare the user's choice to correct_answer in code rather than at the SQL
	// layer so they can return the same row to the client (with the answer + why
	// each distractor was wrong). The item must be accepted.
	GetItemForAttempt(ctx context.Context, id uuid.UUID) (Item, error)
	GetOTPChallengeByID(ctx context.Context, id uuid.UUID) (OtpChallenge, error)
	GetUserByEmail(ctx context.Context, email *string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByPhone(ctx context.Context, phone *string) (User, error)
	// Week-over-week accuracy delta. Rewards growth, not raw skill — the
	// safe-leaderboard goal from spec §22 rule 5. min_attempts gates noisy
	// readings from very small samples.
	ImprovementLeaderboard(ctx context.Context, arg ImprovementLeaderboardParams) ([]ImprovementLeaderboardRow, error)
	IncrementOTPAttempts(ctx context.Context, id uuid.UUID) (OtpChallenge, error)
	// One row per answered item per user. choice_key + correct are nullable to
	// support a "served but skipped" path later (Phase 4 mistake-clinic).
	InsertAttempt(ctx context.Context, arg InsertAttemptParams) (Attempt, error)
	InsertItem(ctx context.Context, arg InsertItemParams) (Item, error)
	InsertItemChoice(ctx context.Context, arg InsertItemChoiceParams) error
	InsertItemTag(ctx context.Context, arg InsertItemTagParams) error
	// Items with at least min_attempts answered. Calibration computes a
	// per-item accuracy and stores it in items.difficulty_calibrated.
	ItemsToCalibrate(ctx context.Context, minAttempts int32) ([]ItemsToCalibrateRow, error)
	ListItemChoices(ctx context.Context, itemID uuid.UUID) ([]ItemChoice, error)
	// Same contract as ListItemChoices but with explicit name to avoid collision.
	ListItemChoicesByID(ctx context.Context, itemID uuid.UUID) ([]ItemChoice, error)
	ListItemTags(ctx context.Context, itemID uuid.UUID) ([]string, error)
	ListItemsByTopic(ctx context.Context, arg ListItemsByTopicParams) ([]Item, error)
	ListItemsNeedingReview(ctx context.Context, arg ListItemsNeedingReviewParams) ([]ListItemsNeedingReviewRow, error)
	ListRecentAttemptsForUser(ctx context.Context, arg ListRecentAttemptsForUserParams) ([]ListRecentAttemptsForUserRow, error)
	ListRecentEventsByType(ctx context.Context, arg ListRecentEventsByTypeParams) ([]Event, error)
	// Idempotent: ON CONFLICT DO NOTHING means re-serving (e.g. retry after a
	// network error) doesn't fail. The PRIMARY KEY (user_id,item_id) covers it.
	MarkItemServed(ctx context.Context, arg MarkItemServedParams) error
	// Top users by accuracy. Restricted to opt-in users with at least
	// min_attempts answered (spec §22 rule 8: don't rank tiny samples).
	// Phone is never selected; nickname is the only public identifier.
	MasteryLeaderboard(ctx context.Context, arg MasteryLeaderboardParams) ([]MasteryLeaderboardRow, error)
	// Items in the same skills as items the user has recently gotten wrong,
	// excluding everything the user has already been served. Backs the
	// Mistake Clinic session type — same concept, fresh question.
	PickMistakeClinicItems(ctx context.Context, arg PickMistakeClinicItemsParams) ([]PickMistakeClinicItemsRow, error)
	// Returns up to limit_count accepted items the user has never been served.
	// Filters by exam_type/section/topic/skill/difficulty if provided
	// (NULL = no filter). Random ordering keeps practice fresh; for ~10k items
	// the cost is fine.
	PickUnservedItemsForUser(ctx context.Context, arg PickUnservedItemsForUserParams) ([]PickUnservedItemsForUserRow, error)
	// Returns the user's weakest skill (lowest accuracy) with at least
	// min_attempts answered. Drives the Weak Spot Drill.
	PickWeakestSkillForUser(ctx context.Context, arg PickWeakestSkillForUserParams) (PickWeakestSkillForUserRow, error)
	RecordEvent(ctx context.Context, arg RecordEventParams) error
	RevokeAllUserSessions(ctx context.Context, userID uuid.UUID) error
	RevokeSession(ctx context.Context, id uuid.UUID) error
	// Used by the reviewer-LLM pass once it lands (Phase 7 stub for now).
	SetItemQualityScore(ctx context.Context, arg SetItemQualityScoreParams) error
	SetItemStatus(ctx context.Context, arg SetItemStatusParams) error
	SetLeaderboardOptIn(ctx context.Context, arg SetLeaderboardOptInParams) error
	SetUserNickname(ctx context.Context, arg SetUserNicknameParams) error
	// Per-topic accuracy + counts for the user. Drives the weakness heatmap
	// (spec §4 #8). LIMIT keeps the payload bounded.
	SummarizeMasteryByTopic(ctx context.Context, arg SummarizeMasteryByTopicParams) ([]SummarizeMasteryByTopicRow, error)
	TouchSessionLastSeen(ctx context.Context, id uuid.UUID) error
	TouchUserLastLogin(ctx context.Context, id uuid.UUID) error
	UpdateItemCalibratedDifficulty(ctx context.Context, arg UpdateItemCalibratedDifficultyParams) error
}

var _ Querier = (*Queries)(nil)
