// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, refresh_hash, expires_at, ip, ua)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, refresh_hash, expires_at, revoked_at, ip, ua, created_at, last_seen_at
`

type CreateSessionParams struct {
	UserID      uuid.UUID          `json:"user_id"`
	RefreshHash string             `json:"refresh_hash"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	Ip          *string            `json:"ip"`
	Ua          *string            `json:"ua"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession,
		arg.UserID,
		arg.RefreshHash,
		arg.ExpiresAt,
		arg.Ip,
		arg.Ua,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.Ip,
		&i.Ua,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const getActiveSessionByRefreshHash = `-- name: GetActiveSessionByRefreshHash :one
SELECT id, user_id, refresh_hash, expires_at, revoked_at, ip, ua, created_at, last_seen_at
FROM sessions
WHERE refresh_hash = $1
  AND revoked_at   IS NULL
  AND expires_at   > now()
`

func (q *Queries) GetActiveSessionByRefreshHash(ctx context.Context, refreshHash string) (Session, error) {
	row := q.db.QueryRow(ctx, getActiveSessionByRefreshHash, refreshHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RefreshHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.Ip,
		&i.Ua,
		&i.CreatedAt,
		&i.LastSeenAt,
	)
	return i, err
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
UPDATE sessions
SET revoked_at = now()
WHERE user_id = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeAllUserSessions(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserSessions, userID)
	return err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions
SET revoked_at = now()
WHERE id = $1
  AND revoked_at IS NULL
`

func (q *Queries) RevokeSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}

const touchSessionLastSeen = `-- name: TouchSessionLastSeen :exec
UPDATE sessions
SET last_seen_at = now()
WHERE id = $1
`

func (q *Queries) TouchSessionLastSeen(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchSessionLastSeen, id)
	return err
}
