/* tslint:disable */
/* eslint-disable */
/**
 * SaaS Control Plane API
 * Operator-only API for provisioning and operating isolated SaaS deployments. Audience saas-control; the operators Keycloak realm is the sole issuer (Phase 13 wires MFA + step-up + IP allowlist). The Bring-Your-Own-Domain endpoints live alongside core deployment CRUD because the verification + cert lifecycle is operator-owned (ADR 015). 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { CreateDeploymentRequest } from '../models';
// @ts-ignore
import type { CreateDeploymentResponse } from '../models';
// @ts-ignore
import type { DeploymentHealthResponse } from '../models';
// @ts-ignore
import type { DeploymentListResponse } from '../models';
// @ts-ignore
import type { DeploymentResponse } from '../models';
// @ts-ignore
import type { DeploymentRevisionListResponse } from '../models';
// @ts-ignore
import type { RestoreDeploymentRequest } from '../models';
// @ts-ignore
import type { StartImpersonationRequest } from '../models';
// @ts-ignore
import type { StartImpersonationResponse } from '../models';
// @ts-ignore
import type { UpdateDeploymentRequest } from '../models';
// @ts-ignore
import type { UpgradeDeploymentRequest } from '../models';
/**
 * DeploymentsApi - axios parameter creator
 */
export const DeploymentsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Provision a new Deployment.
         * @param {string} idempotencyKey 
         * @param {CreateDeploymentRequest} createDeploymentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createDeployment: async (idempotencyKey: string, createDeploymentRequest: CreateDeploymentRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'idempotencyKey' is not null or undefined
            assertParamExists('createDeployment', 'idempotencyKey', idempotencyKey)
            // verify required parameter 'createDeploymentRequest' is not null or undefined
            assertParamExists('createDeployment', 'createDeploymentRequest', createDeploymentRequest)
            const localVarPath = `/control/v1/deployments`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            if (idempotencyKey != null) {
                localVarHeaderParameter['Idempotency-Key'] = String(idempotencyKey);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(createDeploymentRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} deploymentId 
         * @param {number} [retainDays] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteDeployment: async (deploymentId: string, retainDays?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'deploymentId' is not null or undefined
            assertParamExists('deleteDeployment', 'deploymentId', deploymentId)
            const localVarPath = `/control/v1/deployments/{deployment_id}`
                .replace('{deployment_id}', encodeURIComponent(String(deploymentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (retainDays !== undefined) {
                localVarQueryParameter['retain_days'] = retainDays;
            }


            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} idempotencyKey 
         * @param {string} deploymentId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        freezeDeploymentKeys: async (idempotencyKey: string, deploymentId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'idempotencyKey' is not null or undefined
            assertParamExists('freezeDeploymentKeys', 'idempotencyKey', idempotencyKey)
            // verify required parameter 'deploymentId' is not null or undefined
            assertParamExists('freezeDeploymentKeys', 'deploymentId', deploymentId)
            const localVarPath = `/control/v1/deployments/{deployment_id}/freeze-keys`
                .replace('{deployment_id}', encodeURIComponent(String(deploymentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            if (idempotencyKey != null) {
                localVarHeaderParameter['Idempotency-Key'] = String(idempotencyKey);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} deploymentId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDeployment: async (deploymentId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'deploymentId' is not null or undefined
            assertParamExists('getDeployment', 'deploymentId', deploymentId)
            const localVarPath = `/control/v1/deployments/{deployment_id}`
                .replace('{deployment_id}', encodeURIComponent(String(deploymentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} deploymentId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDeploymentHealth: async (deploymentId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'deploymentId' is not null or undefined
            assertParamExists('getDeploymentHealth', 'deploymentId', deploymentId)
            const localVarPath = `/control/v1/deployments/{deployment_id}/health`
                .replace('{deployment_id}', encodeURIComponent(String(deploymentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} deploymentId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listDeploymentRevisions: async (deploymentId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'deploymentId' is not null or undefined
            assertParamExists('listDeploymentRevisions', 'deploymentId', deploymentId)
            const localVarPath = `/control/v1/deployments/{deployment_id}/revisions`
                .replace('{deployment_id}', encodeURIComponent(String(deploymentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary List Deployments.
         * @param {number} [limit] 
         * @param {string} [cursor] 
         * @param {string} [status] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listDeployments: async (limit?: number, cursor?: string, status?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/control/v1/deployments`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (cursor !== undefined) {
                localVarQueryParameter['cursor'] = cursor;
            }

            if (status !== undefined) {
                localVarQueryParameter['status'] = status;
            }

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} idempotencyKey 
         * @param {string} deploymentId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        purgeDeployment: async (idempotencyKey: string, deploymentId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'idempotencyKey' is not null or undefined
            assertParamExists('purgeDeployment', 'idempotencyKey', idempotencyKey)
            // verify required parameter 'deploymentId' is not null or undefined
            assertParamExists('purgeDeployment', 'deploymentId', deploymentId)
            const localVarPath = `/control/v1/deployments/{deployment_id}/purge`
                .replace('{deployment_id}', encodeURIComponent(String(deploymentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            if (idempotencyKey != null) {
                localVarHeaderParameter['Idempotency-Key'] = String(idempotencyKey);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} idempotencyKey 
         * @param {string} deploymentId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        restartDeployment: async (idempotencyKey: string, deploymentId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'idempotencyKey' is not null or undefined
            assertParamExists('restartDeployment', 'idempotencyKey', idempotencyKey)
            // verify required parameter 'deploymentId' is not null or undefined
            assertParamExists('restartDeployment', 'deploymentId', deploymentId)
            const localVarPath = `/control/v1/deployments/{deployment_id}/restart`
                .replace('{deployment_id}', encodeURIComponent(String(deploymentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            if (idempotencyKey != null) {
                localVarHeaderParameter['Idempotency-Key'] = String(idempotencyKey);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} idempotencyKey 
         * @param {string} deploymentId 
         * @param {RestoreDeploymentRequest} restoreDeploymentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        restoreDeployment: async (idempotencyKey: string, deploymentId: string, restoreDeploymentRequest: RestoreDeploymentRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'idempotencyKey' is not null or undefined
            assertParamExists('restoreDeployment', 'idempotencyKey', idempotencyKey)
            // verify required parameter 'deploymentId' is not null or undefined
            assertParamExists('restoreDeployment', 'deploymentId', deploymentId)
            // verify required parameter 'restoreDeploymentRequest' is not null or undefined
            assertParamExists('restoreDeployment', 'restoreDeploymentRequest', restoreDeploymentRequest)
            const localVarPath = `/control/v1/deployments/{deployment_id}/restore`
                .replace('{deployment_id}', encodeURIComponent(String(deploymentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            if (idempotencyKey != null) {
                localVarHeaderParameter['Idempotency-Key'] = String(idempotencyKey);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(restoreDeploymentRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} idempotencyKey 
         * @param {string} deploymentId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        rollbackDeployment: async (idempotencyKey: string, deploymentId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'idempotencyKey' is not null or undefined
            assertParamExists('rollbackDeployment', 'idempotencyKey', idempotencyKey)
            // verify required parameter 'deploymentId' is not null or undefined
            assertParamExists('rollbackDeployment', 'deploymentId', deploymentId)
            const localVarPath = `/control/v1/deployments/{deployment_id}/rollback`
                .replace('{deployment_id}', encodeURIComponent(String(deploymentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            if (idempotencyKey != null) {
                localVarHeaderParameter['Idempotency-Key'] = String(idempotencyKey);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} idempotencyKey 
         * @param {string} deploymentId 
         * @param {StartImpersonationRequest} startImpersonationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        startImpersonationSession: async (idempotencyKey: string, deploymentId: string, startImpersonationRequest: StartImpersonationRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'idempotencyKey' is not null or undefined
            assertParamExists('startImpersonationSession', 'idempotencyKey', idempotencyKey)
            // verify required parameter 'deploymentId' is not null or undefined
            assertParamExists('startImpersonationSession', 'deploymentId', deploymentId)
            // verify required parameter 'startImpersonationRequest' is not null or undefined
            assertParamExists('startImpersonationSession', 'startImpersonationRequest', startImpersonationRequest)
            const localVarPath = `/control/v1/deployments/{deployment_id}/impersonation-sessions`
                .replace('{deployment_id}', encodeURIComponent(String(deploymentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            if (idempotencyKey != null) {
                localVarHeaderParameter['Idempotency-Key'] = String(idempotencyKey);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(startImpersonationRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} deploymentId 
         * @param {string} [since] 
         * @param {string} [filter] 
         * @param {number} [tail] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tailDeploymentLogs: async (deploymentId: string, since?: string, filter?: string, tail?: number, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'deploymentId' is not null or undefined
            assertParamExists('tailDeploymentLogs', 'deploymentId', deploymentId)
            const localVarPath = `/control/v1/deployments/{deployment_id}/logs`
                .replace('{deployment_id}', encodeURIComponent(String(deploymentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (since !== undefined) {
                localVarQueryParameter['since'] = (since as any instanceof Date) ?
                    (since as any).toISOString() :
                    since;
            }

            if (filter !== undefined) {
                localVarQueryParameter['filter'] = filter;
            }

            if (tail !== undefined) {
                localVarQueryParameter['tail'] = tail;
            }

            localVarHeaderParameter['Accept'] = 'application/x-ndjson';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} ifMatch 
         * @param {string} deploymentId 
         * @param {UpdateDeploymentRequest} updateDeploymentRequest 
         * @param {string} [idempotencyKey] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateDeployment: async (ifMatch: string, deploymentId: string, updateDeploymentRequest: UpdateDeploymentRequest, idempotencyKey?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'ifMatch' is not null or undefined
            assertParamExists('updateDeployment', 'ifMatch', ifMatch)
            // verify required parameter 'deploymentId' is not null or undefined
            assertParamExists('updateDeployment', 'deploymentId', deploymentId)
            // verify required parameter 'updateDeploymentRequest' is not null or undefined
            assertParamExists('updateDeployment', 'updateDeploymentRequest', updateDeploymentRequest)
            const localVarPath = `/control/v1/deployments/{deployment_id}`
                .replace('{deployment_id}', encodeURIComponent(String(deploymentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            if (ifMatch != null) {
                localVarHeaderParameter['If-Match'] = String(ifMatch);
            }
            if (idempotencyKey != null) {
                localVarHeaderParameter['Idempotency-Key'] = String(idempotencyKey);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(updateDeploymentRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} idempotencyKey 
         * @param {string} deploymentId 
         * @param {UpgradeDeploymentRequest} upgradeDeploymentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        upgradeDeployment: async (idempotencyKey: string, deploymentId: string, upgradeDeploymentRequest: UpgradeDeploymentRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'idempotencyKey' is not null or undefined
            assertParamExists('upgradeDeployment', 'idempotencyKey', idempotencyKey)
            // verify required parameter 'deploymentId' is not null or undefined
            assertParamExists('upgradeDeployment', 'deploymentId', deploymentId)
            // verify required parameter 'upgradeDeploymentRequest' is not null or undefined
            assertParamExists('upgradeDeployment', 'upgradeDeploymentRequest', upgradeDeploymentRequest)
            const localVarPath = `/control/v1/deployments/{deployment_id}/upgrade`
                .replace('{deployment_id}', encodeURIComponent(String(deploymentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            if (idempotencyKey != null) {
                localVarHeaderParameter['Idempotency-Key'] = String(idempotencyKey);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(upgradeDeploymentRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DeploymentsApi - functional programming interface
 */
export const DeploymentsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DeploymentsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Provision a new Deployment.
         * @param {string} idempotencyKey 
         * @param {CreateDeploymentRequest} createDeploymentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async createDeployment(idempotencyKey: string, createDeploymentRequest: CreateDeploymentRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<CreateDeploymentResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createDeployment(idempotencyKey, createDeploymentRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DeploymentsApi.createDeployment']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} deploymentId 
         * @param {number} [retainDays] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteDeployment(deploymentId: string, retainDays?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteDeployment(deploymentId, retainDays, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DeploymentsApi.deleteDeployment']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} idempotencyKey 
         * @param {string} deploymentId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async freezeDeploymentKeys(idempotencyKey: string, deploymentId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DeploymentResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.freezeDeploymentKeys(idempotencyKey, deploymentId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DeploymentsApi.freezeDeploymentKeys']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} deploymentId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDeployment(deploymentId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DeploymentResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getDeployment(deploymentId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DeploymentsApi.getDeployment']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} deploymentId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDeploymentHealth(deploymentId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DeploymentHealthResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getDeploymentHealth(deploymentId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DeploymentsApi.getDeploymentHealth']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} deploymentId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listDeploymentRevisions(deploymentId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DeploymentRevisionListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listDeploymentRevisions(deploymentId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DeploymentsApi.listDeploymentRevisions']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary List Deployments.
         * @param {number} [limit] 
         * @param {string} [cursor] 
         * @param {string} [status] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listDeployments(limit?: number, cursor?: string, status?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DeploymentListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listDeployments(limit, cursor, status, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DeploymentsApi.listDeployments']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} idempotencyKey 
         * @param {string} deploymentId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async purgeDeployment(idempotencyKey: string, deploymentId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DeploymentResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.purgeDeployment(idempotencyKey, deploymentId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DeploymentsApi.purgeDeployment']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} idempotencyKey 
         * @param {string} deploymentId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async restartDeployment(idempotencyKey: string, deploymentId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DeploymentResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.restartDeployment(idempotencyKey, deploymentId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DeploymentsApi.restartDeployment']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} idempotencyKey 
         * @param {string} deploymentId 
         * @param {RestoreDeploymentRequest} restoreDeploymentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async restoreDeployment(idempotencyKey: string, deploymentId: string, restoreDeploymentRequest: RestoreDeploymentRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DeploymentResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.restoreDeployment(idempotencyKey, deploymentId, restoreDeploymentRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DeploymentsApi.restoreDeployment']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} idempotencyKey 
         * @param {string} deploymentId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async rollbackDeployment(idempotencyKey: string, deploymentId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DeploymentResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.rollbackDeployment(idempotencyKey, deploymentId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DeploymentsApi.rollbackDeployment']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} idempotencyKey 
         * @param {string} deploymentId 
         * @param {StartImpersonationRequest} startImpersonationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async startImpersonationSession(idempotencyKey: string, deploymentId: string, startImpersonationRequest: StartImpersonationRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<StartImpersonationResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.startImpersonationSession(idempotencyKey, deploymentId, startImpersonationRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DeploymentsApi.startImpersonationSession']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} deploymentId 
         * @param {string} [since] 
         * @param {string} [filter] 
         * @param {number} [tail] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async tailDeploymentLogs(deploymentId: string, since?: string, filter?: string, tail?: number, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<string>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.tailDeploymentLogs(deploymentId, since, filter, tail, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DeploymentsApi.tailDeploymentLogs']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} ifMatch 
         * @param {string} deploymentId 
         * @param {UpdateDeploymentRequest} updateDeploymentRequest 
         * @param {string} [idempotencyKey] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateDeployment(ifMatch: string, deploymentId: string, updateDeploymentRequest: UpdateDeploymentRequest, idempotencyKey?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DeploymentResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateDeployment(ifMatch, deploymentId, updateDeploymentRequest, idempotencyKey, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DeploymentsApi.updateDeployment']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} idempotencyKey 
         * @param {string} deploymentId 
         * @param {UpgradeDeploymentRequest} upgradeDeploymentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async upgradeDeployment(idempotencyKey: string, deploymentId: string, upgradeDeploymentRequest: UpgradeDeploymentRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DeploymentResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.upgradeDeployment(idempotencyKey, deploymentId, upgradeDeploymentRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DeploymentsApi.upgradeDeployment']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DeploymentsApi - factory interface
 */
export const DeploymentsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DeploymentsApiFp(configuration)
    return {
        /**
         * 
         * @summary Provision a new Deployment.
         * @param {string} idempotencyKey 
         * @param {CreateDeploymentRequest} createDeploymentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        createDeployment(idempotencyKey: string, createDeploymentRequest: CreateDeploymentRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateDeploymentResponse> {
            return localVarFp.createDeployment(idempotencyKey, createDeploymentRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} deploymentId 
         * @param {number} [retainDays] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteDeployment(deploymentId: string, retainDays?: number, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteDeployment(deploymentId, retainDays, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} idempotencyKey 
         * @param {string} deploymentId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        freezeDeploymentKeys(idempotencyKey: string, deploymentId: string, options?: RawAxiosRequestConfig): AxiosPromise<DeploymentResponse> {
            return localVarFp.freezeDeploymentKeys(idempotencyKey, deploymentId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} deploymentId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDeployment(deploymentId: string, options?: RawAxiosRequestConfig): AxiosPromise<DeploymentResponse> {
            return localVarFp.getDeployment(deploymentId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} deploymentId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDeploymentHealth(deploymentId: string, options?: RawAxiosRequestConfig): AxiosPromise<DeploymentHealthResponse> {
            return localVarFp.getDeploymentHealth(deploymentId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} deploymentId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listDeploymentRevisions(deploymentId: string, options?: RawAxiosRequestConfig): AxiosPromise<DeploymentRevisionListResponse> {
            return localVarFp.listDeploymentRevisions(deploymentId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary List Deployments.
         * @param {number} [limit] 
         * @param {string} [cursor] 
         * @param {string} [status] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listDeployments(limit?: number, cursor?: string, status?: string, options?: RawAxiosRequestConfig): AxiosPromise<DeploymentListResponse> {
            return localVarFp.listDeployments(limit, cursor, status, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} idempotencyKey 
         * @param {string} deploymentId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        purgeDeployment(idempotencyKey: string, deploymentId: string, options?: RawAxiosRequestConfig): AxiosPromise<DeploymentResponse> {
            return localVarFp.purgeDeployment(idempotencyKey, deploymentId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} idempotencyKey 
         * @param {string} deploymentId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        restartDeployment(idempotencyKey: string, deploymentId: string, options?: RawAxiosRequestConfig): AxiosPromise<DeploymentResponse> {
            return localVarFp.restartDeployment(idempotencyKey, deploymentId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} idempotencyKey 
         * @param {string} deploymentId 
         * @param {RestoreDeploymentRequest} restoreDeploymentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        restoreDeployment(idempotencyKey: string, deploymentId: string, restoreDeploymentRequest: RestoreDeploymentRequest, options?: RawAxiosRequestConfig): AxiosPromise<DeploymentResponse> {
            return localVarFp.restoreDeployment(idempotencyKey, deploymentId, restoreDeploymentRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} idempotencyKey 
         * @param {string} deploymentId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        rollbackDeployment(idempotencyKey: string, deploymentId: string, options?: RawAxiosRequestConfig): AxiosPromise<DeploymentResponse> {
            return localVarFp.rollbackDeployment(idempotencyKey, deploymentId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} idempotencyKey 
         * @param {string} deploymentId 
         * @param {StartImpersonationRequest} startImpersonationRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        startImpersonationSession(idempotencyKey: string, deploymentId: string, startImpersonationRequest: StartImpersonationRequest, options?: RawAxiosRequestConfig): AxiosPromise<StartImpersonationResponse> {
            return localVarFp.startImpersonationSession(idempotencyKey, deploymentId, startImpersonationRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} deploymentId 
         * @param {string} [since] 
         * @param {string} [filter] 
         * @param {number} [tail] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        tailDeploymentLogs(deploymentId: string, since?: string, filter?: string, tail?: number, options?: RawAxiosRequestConfig): AxiosPromise<string> {
            return localVarFp.tailDeploymentLogs(deploymentId, since, filter, tail, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} ifMatch 
         * @param {string} deploymentId 
         * @param {UpdateDeploymentRequest} updateDeploymentRequest 
         * @param {string} [idempotencyKey] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateDeployment(ifMatch: string, deploymentId: string, updateDeploymentRequest: UpdateDeploymentRequest, idempotencyKey?: string, options?: RawAxiosRequestConfig): AxiosPromise<DeploymentResponse> {
            return localVarFp.updateDeployment(ifMatch, deploymentId, updateDeploymentRequest, idempotencyKey, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} idempotencyKey 
         * @param {string} deploymentId 
         * @param {UpgradeDeploymentRequest} upgradeDeploymentRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        upgradeDeployment(idempotencyKey: string, deploymentId: string, upgradeDeploymentRequest: UpgradeDeploymentRequest, options?: RawAxiosRequestConfig): AxiosPromise<DeploymentResponse> {
            return localVarFp.upgradeDeployment(idempotencyKey, deploymentId, upgradeDeploymentRequest, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DeploymentsApi - interface
 */
export interface DeploymentsApiInterface {
    /**
     * 
     * @summary Provision a new Deployment.
     * @param {string} idempotencyKey 
     * @param {CreateDeploymentRequest} createDeploymentRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    createDeployment(idempotencyKey: string, createDeploymentRequest: CreateDeploymentRequest, options?: RawAxiosRequestConfig): AxiosPromise<CreateDeploymentResponse>;

    /**
     * 
     * @param {string} deploymentId 
     * @param {number} [retainDays] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    deleteDeployment(deploymentId: string, retainDays?: number, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @param {string} idempotencyKey 
     * @param {string} deploymentId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    freezeDeploymentKeys(idempotencyKey: string, deploymentId: string, options?: RawAxiosRequestConfig): AxiosPromise<DeploymentResponse>;

    /**
     * 
     * @param {string} deploymentId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getDeployment(deploymentId: string, options?: RawAxiosRequestConfig): AxiosPromise<DeploymentResponse>;

    /**
     * 
     * @param {string} deploymentId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getDeploymentHealth(deploymentId: string, options?: RawAxiosRequestConfig): AxiosPromise<DeploymentHealthResponse>;

    /**
     * 
     * @param {string} deploymentId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listDeploymentRevisions(deploymentId: string, options?: RawAxiosRequestConfig): AxiosPromise<DeploymentRevisionListResponse>;

    /**
     * 
     * @summary List Deployments.
     * @param {number} [limit] 
     * @param {string} [cursor] 
     * @param {string} [status] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listDeployments(limit?: number, cursor?: string, status?: string, options?: RawAxiosRequestConfig): AxiosPromise<DeploymentListResponse>;

    /**
     * 
     * @param {string} idempotencyKey 
     * @param {string} deploymentId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    purgeDeployment(idempotencyKey: string, deploymentId: string, options?: RawAxiosRequestConfig): AxiosPromise<DeploymentResponse>;

    /**
     * 
     * @param {string} idempotencyKey 
     * @param {string} deploymentId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    restartDeployment(idempotencyKey: string, deploymentId: string, options?: RawAxiosRequestConfig): AxiosPromise<DeploymentResponse>;

    /**
     * 
     * @param {string} idempotencyKey 
     * @param {string} deploymentId 
     * @param {RestoreDeploymentRequest} restoreDeploymentRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    restoreDeployment(idempotencyKey: string, deploymentId: string, restoreDeploymentRequest: RestoreDeploymentRequest, options?: RawAxiosRequestConfig): AxiosPromise<DeploymentResponse>;

    /**
     * 
     * @param {string} idempotencyKey 
     * @param {string} deploymentId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    rollbackDeployment(idempotencyKey: string, deploymentId: string, options?: RawAxiosRequestConfig): AxiosPromise<DeploymentResponse>;

    /**
     * 
     * @param {string} idempotencyKey 
     * @param {string} deploymentId 
     * @param {StartImpersonationRequest} startImpersonationRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    startImpersonationSession(idempotencyKey: string, deploymentId: string, startImpersonationRequest: StartImpersonationRequest, options?: RawAxiosRequestConfig): AxiosPromise<StartImpersonationResponse>;

    /**
     * 
     * @param {string} deploymentId 
     * @param {string} [since] 
     * @param {string} [filter] 
     * @param {number} [tail] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    tailDeploymentLogs(deploymentId: string, since?: string, filter?: string, tail?: number, options?: RawAxiosRequestConfig): AxiosPromise<string>;

    /**
     * 
     * @param {string} ifMatch 
     * @param {string} deploymentId 
     * @param {UpdateDeploymentRequest} updateDeploymentRequest 
     * @param {string} [idempotencyKey] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    updateDeployment(ifMatch: string, deploymentId: string, updateDeploymentRequest: UpdateDeploymentRequest, idempotencyKey?: string, options?: RawAxiosRequestConfig): AxiosPromise<DeploymentResponse>;

    /**
     * 
     * @param {string} idempotencyKey 
     * @param {string} deploymentId 
     * @param {UpgradeDeploymentRequest} upgradeDeploymentRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    upgradeDeployment(idempotencyKey: string, deploymentId: string, upgradeDeploymentRequest: UpgradeDeploymentRequest, options?: RawAxiosRequestConfig): AxiosPromise<DeploymentResponse>;

}

/**
 * DeploymentsApi - object-oriented interface
 */
export class DeploymentsApi extends BaseAPI implements DeploymentsApiInterface {
    /**
     * 
     * @summary Provision a new Deployment.
     * @param {string} idempotencyKey 
     * @param {CreateDeploymentRequest} createDeploymentRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public createDeployment(idempotencyKey: string, createDeploymentRequest: CreateDeploymentRequest, options?: RawAxiosRequestConfig) {
        return DeploymentsApiFp(this.configuration).createDeployment(idempotencyKey, createDeploymentRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} deploymentId 
     * @param {number} [retainDays] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public deleteDeployment(deploymentId: string, retainDays?: number, options?: RawAxiosRequestConfig) {
        return DeploymentsApiFp(this.configuration).deleteDeployment(deploymentId, retainDays, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} idempotencyKey 
     * @param {string} deploymentId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public freezeDeploymentKeys(idempotencyKey: string, deploymentId: string, options?: RawAxiosRequestConfig) {
        return DeploymentsApiFp(this.configuration).freezeDeploymentKeys(idempotencyKey, deploymentId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} deploymentId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getDeployment(deploymentId: string, options?: RawAxiosRequestConfig) {
        return DeploymentsApiFp(this.configuration).getDeployment(deploymentId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} deploymentId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getDeploymentHealth(deploymentId: string, options?: RawAxiosRequestConfig) {
        return DeploymentsApiFp(this.configuration).getDeploymentHealth(deploymentId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} deploymentId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listDeploymentRevisions(deploymentId: string, options?: RawAxiosRequestConfig) {
        return DeploymentsApiFp(this.configuration).listDeploymentRevisions(deploymentId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary List Deployments.
     * @param {number} [limit] 
     * @param {string} [cursor] 
     * @param {string} [status] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listDeployments(limit?: number, cursor?: string, status?: string, options?: RawAxiosRequestConfig) {
        return DeploymentsApiFp(this.configuration).listDeployments(limit, cursor, status, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} idempotencyKey 
     * @param {string} deploymentId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public purgeDeployment(idempotencyKey: string, deploymentId: string, options?: RawAxiosRequestConfig) {
        return DeploymentsApiFp(this.configuration).purgeDeployment(idempotencyKey, deploymentId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} idempotencyKey 
     * @param {string} deploymentId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public restartDeployment(idempotencyKey: string, deploymentId: string, options?: RawAxiosRequestConfig) {
        return DeploymentsApiFp(this.configuration).restartDeployment(idempotencyKey, deploymentId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} idempotencyKey 
     * @param {string} deploymentId 
     * @param {RestoreDeploymentRequest} restoreDeploymentRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public restoreDeployment(idempotencyKey: string, deploymentId: string, restoreDeploymentRequest: RestoreDeploymentRequest, options?: RawAxiosRequestConfig) {
        return DeploymentsApiFp(this.configuration).restoreDeployment(idempotencyKey, deploymentId, restoreDeploymentRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} idempotencyKey 
     * @param {string} deploymentId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public rollbackDeployment(idempotencyKey: string, deploymentId: string, options?: RawAxiosRequestConfig) {
        return DeploymentsApiFp(this.configuration).rollbackDeployment(idempotencyKey, deploymentId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} idempotencyKey 
     * @param {string} deploymentId 
     * @param {StartImpersonationRequest} startImpersonationRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public startImpersonationSession(idempotencyKey: string, deploymentId: string, startImpersonationRequest: StartImpersonationRequest, options?: RawAxiosRequestConfig) {
        return DeploymentsApiFp(this.configuration).startImpersonationSession(idempotencyKey, deploymentId, startImpersonationRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} deploymentId 
     * @param {string} [since] 
     * @param {string} [filter] 
     * @param {number} [tail] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public tailDeploymentLogs(deploymentId: string, since?: string, filter?: string, tail?: number, options?: RawAxiosRequestConfig) {
        return DeploymentsApiFp(this.configuration).tailDeploymentLogs(deploymentId, since, filter, tail, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} ifMatch 
     * @param {string} deploymentId 
     * @param {UpdateDeploymentRequest} updateDeploymentRequest 
     * @param {string} [idempotencyKey] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public updateDeployment(ifMatch: string, deploymentId: string, updateDeploymentRequest: UpdateDeploymentRequest, idempotencyKey?: string, options?: RawAxiosRequestConfig) {
        return DeploymentsApiFp(this.configuration).updateDeployment(ifMatch, deploymentId, updateDeploymentRequest, idempotencyKey, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} idempotencyKey 
     * @param {string} deploymentId 
     * @param {UpgradeDeploymentRequest} upgradeDeploymentRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public upgradeDeployment(idempotencyKey: string, deploymentId: string, upgradeDeploymentRequest: UpgradeDeploymentRequest, options?: RawAxiosRequestConfig) {
        return DeploymentsApiFp(this.configuration).upgradeDeployment(idempotencyKey, deploymentId, upgradeDeploymentRequest, options).then((request) => request(this.axios, this.basePath));
    }
}

