/* tslint:disable */
/* eslint-disable */
/**
 * SaaS Control Plane API
 * Operator-only API for provisioning and operating isolated SaaS deployments. Audience saas-control; the operators Keycloak realm is the sole issuer (Phase 13 wires MFA + step-up + IP allowlist). The Bring-Your-Own-Domain endpoints live alongside core deployment CRUD because the verification + cert lifecycle is operator-owned (ADR 015). 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { AttachDomainRequest } from '../models';
// @ts-ignore
import type { DeploymentDomainListResponse } from '../models';
// @ts-ignore
import type { DeploymentDomainResponse } from '../models';
/**
 * DomainsApi - axios parameter creator
 */
export const DomainsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {string} idempotencyKey 
         * @param {string} deploymentId 
         * @param {AttachDomainRequest} attachDomainRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        attachDeploymentDomain: async (idempotencyKey: string, deploymentId: string, attachDomainRequest: AttachDomainRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'idempotencyKey' is not null or undefined
            assertParamExists('attachDeploymentDomain', 'idempotencyKey', idempotencyKey)
            // verify required parameter 'deploymentId' is not null or undefined
            assertParamExists('attachDeploymentDomain', 'deploymentId', deploymentId)
            // verify required parameter 'attachDomainRequest' is not null or undefined
            assertParamExists('attachDeploymentDomain', 'attachDomainRequest', attachDomainRequest)
            const localVarPath = `/control/v1/deployments/{deployment_id}/domains`
                .replace('{deployment_id}', encodeURIComponent(String(deploymentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Content-Type'] = 'application/json';
            localVarHeaderParameter['Accept'] = 'application/json';

            if (idempotencyKey != null) {
                localVarHeaderParameter['Idempotency-Key'] = String(idempotencyKey);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(attachDomainRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} deploymentId 
         * @param {string} domainId 
         * @param {string} [ifMatch] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        detachDeploymentDomain: async (deploymentId: string, domainId: string, ifMatch?: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'deploymentId' is not null or undefined
            assertParamExists('detachDeploymentDomain', 'deploymentId', deploymentId)
            // verify required parameter 'domainId' is not null or undefined
            assertParamExists('detachDeploymentDomain', 'domainId', domainId)
            const localVarPath = `/control/v1/deployments/{deployment_id}/domains/{domain_id}`
                .replace('{deployment_id}', encodeURIComponent(String(deploymentId)))
                .replace('{domain_id}', encodeURIComponent(String(domainId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


            if (ifMatch != null) {
                localVarHeaderParameter['If-Match'] = String(ifMatch);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} deploymentId 
         * @param {string} domainId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDeploymentDomain: async (deploymentId: string, domainId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'deploymentId' is not null or undefined
            assertParamExists('getDeploymentDomain', 'deploymentId', deploymentId)
            // verify required parameter 'domainId' is not null or undefined
            assertParamExists('getDeploymentDomain', 'domainId', domainId)
            const localVarPath = `/control/v1/deployments/{deployment_id}/domains/{domain_id}`
                .replace('{deployment_id}', encodeURIComponent(String(deploymentId)))
                .replace('{domain_id}', encodeURIComponent(String(domainId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} deploymentId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listDeploymentDomains: async (deploymentId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'deploymentId' is not null or undefined
            assertParamExists('listDeploymentDomains', 'deploymentId', deploymentId)
            const localVarPath = `/control/v1/deployments/{deployment_id}/domains`
                .replace('{deployment_id}', encodeURIComponent(String(deploymentId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {string} idempotencyKey 
         * @param {string} deploymentId 
         * @param {string} domainId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        verifyDeploymentDomain: async (idempotencyKey: string, deploymentId: string, domainId: string, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'idempotencyKey' is not null or undefined
            assertParamExists('verifyDeploymentDomain', 'idempotencyKey', idempotencyKey)
            // verify required parameter 'deploymentId' is not null or undefined
            assertParamExists('verifyDeploymentDomain', 'deploymentId', deploymentId)
            // verify required parameter 'domainId' is not null or undefined
            assertParamExists('verifyDeploymentDomain', 'domainId', domainId)
            const localVarPath = `/control/v1/deployments/{deployment_id}/domains/{domain_id}/verify`
                .replace('{deployment_id}', encodeURIComponent(String(deploymentId)))
                .replace('{domain_id}', encodeURIComponent(String(domainId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            if (idempotencyKey != null) {
                localVarHeaderParameter['Idempotency-Key'] = String(idempotencyKey);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * DomainsApi - functional programming interface
 */
export const DomainsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = DomainsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {string} idempotencyKey 
         * @param {string} deploymentId 
         * @param {AttachDomainRequest} attachDomainRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async attachDeploymentDomain(idempotencyKey: string, deploymentId: string, attachDomainRequest: AttachDomainRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DeploymentDomainResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.attachDeploymentDomain(idempotencyKey, deploymentId, attachDomainRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DomainsApi.attachDeploymentDomain']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} deploymentId 
         * @param {string} domainId 
         * @param {string} [ifMatch] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async detachDeploymentDomain(deploymentId: string, domainId: string, ifMatch?: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.detachDeploymentDomain(deploymentId, domainId, ifMatch, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DomainsApi.detachDeploymentDomain']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} deploymentId 
         * @param {string} domainId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getDeploymentDomain(deploymentId: string, domainId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DeploymentDomainResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getDeploymentDomain(deploymentId, domainId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DomainsApi.getDeploymentDomain']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} deploymentId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listDeploymentDomains(deploymentId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DeploymentDomainListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listDeploymentDomains(deploymentId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DomainsApi.listDeploymentDomains']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {string} idempotencyKey 
         * @param {string} deploymentId 
         * @param {string} domainId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async verifyDeploymentDomain(idempotencyKey: string, deploymentId: string, domainId: string, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<DeploymentDomainResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.verifyDeploymentDomain(idempotencyKey, deploymentId, domainId, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['DomainsApi.verifyDeploymentDomain']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * DomainsApi - factory interface
 */
export const DomainsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = DomainsApiFp(configuration)
    return {
        /**
         * 
         * @param {string} idempotencyKey 
         * @param {string} deploymentId 
         * @param {AttachDomainRequest} attachDomainRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        attachDeploymentDomain(idempotencyKey: string, deploymentId: string, attachDomainRequest: AttachDomainRequest, options?: RawAxiosRequestConfig): AxiosPromise<DeploymentDomainResponse> {
            return localVarFp.attachDeploymentDomain(idempotencyKey, deploymentId, attachDomainRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} deploymentId 
         * @param {string} domainId 
         * @param {string} [ifMatch] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        detachDeploymentDomain(deploymentId: string, domainId: string, ifMatch?: string, options?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.detachDeploymentDomain(deploymentId, domainId, ifMatch, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} deploymentId 
         * @param {string} domainId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getDeploymentDomain(deploymentId: string, domainId: string, options?: RawAxiosRequestConfig): AxiosPromise<DeploymentDomainResponse> {
            return localVarFp.getDeploymentDomain(deploymentId, domainId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} deploymentId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listDeploymentDomains(deploymentId: string, options?: RawAxiosRequestConfig): AxiosPromise<DeploymentDomainListResponse> {
            return localVarFp.listDeploymentDomains(deploymentId, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {string} idempotencyKey 
         * @param {string} deploymentId 
         * @param {string} domainId 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        verifyDeploymentDomain(idempotencyKey: string, deploymentId: string, domainId: string, options?: RawAxiosRequestConfig): AxiosPromise<DeploymentDomainResponse> {
            return localVarFp.verifyDeploymentDomain(idempotencyKey, deploymentId, domainId, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * DomainsApi - interface
 */
export interface DomainsApiInterface {
    /**
     * 
     * @param {string} idempotencyKey 
     * @param {string} deploymentId 
     * @param {AttachDomainRequest} attachDomainRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    attachDeploymentDomain(idempotencyKey: string, deploymentId: string, attachDomainRequest: AttachDomainRequest, options?: RawAxiosRequestConfig): AxiosPromise<DeploymentDomainResponse>;

    /**
     * 
     * @param {string} deploymentId 
     * @param {string} domainId 
     * @param {string} [ifMatch] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    detachDeploymentDomain(deploymentId: string, domainId: string, ifMatch?: string, options?: RawAxiosRequestConfig): AxiosPromise<void>;

    /**
     * 
     * @param {string} deploymentId 
     * @param {string} domainId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    getDeploymentDomain(deploymentId: string, domainId: string, options?: RawAxiosRequestConfig): AxiosPromise<DeploymentDomainResponse>;

    /**
     * 
     * @param {string} deploymentId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listDeploymentDomains(deploymentId: string, options?: RawAxiosRequestConfig): AxiosPromise<DeploymentDomainListResponse>;

    /**
     * 
     * @param {string} idempotencyKey 
     * @param {string} deploymentId 
     * @param {string} domainId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    verifyDeploymentDomain(idempotencyKey: string, deploymentId: string, domainId: string, options?: RawAxiosRequestConfig): AxiosPromise<DeploymentDomainResponse>;

}

/**
 * DomainsApi - object-oriented interface
 */
export class DomainsApi extends BaseAPI implements DomainsApiInterface {
    /**
     * 
     * @param {string} idempotencyKey 
     * @param {string} deploymentId 
     * @param {AttachDomainRequest} attachDomainRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public attachDeploymentDomain(idempotencyKey: string, deploymentId: string, attachDomainRequest: AttachDomainRequest, options?: RawAxiosRequestConfig) {
        return DomainsApiFp(this.configuration).attachDeploymentDomain(idempotencyKey, deploymentId, attachDomainRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} deploymentId 
     * @param {string} domainId 
     * @param {string} [ifMatch] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public detachDeploymentDomain(deploymentId: string, domainId: string, ifMatch?: string, options?: RawAxiosRequestConfig) {
        return DomainsApiFp(this.configuration).detachDeploymentDomain(deploymentId, domainId, ifMatch, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} deploymentId 
     * @param {string} domainId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public getDeploymentDomain(deploymentId: string, domainId: string, options?: RawAxiosRequestConfig) {
        return DomainsApiFp(this.configuration).getDeploymentDomain(deploymentId, domainId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} deploymentId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listDeploymentDomains(deploymentId: string, options?: RawAxiosRequestConfig) {
        return DomainsApiFp(this.configuration).listDeploymentDomains(deploymentId, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {string} idempotencyKey 
     * @param {string} deploymentId 
     * @param {string} domainId 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public verifyDeploymentDomain(idempotencyKey: string, deploymentId: string, domainId: string, options?: RawAxiosRequestConfig) {
        return DomainsApiFp(this.configuration).verifyDeploymentDomain(idempotencyKey, deploymentId, domainId, options).then((request) => request(this.axios, this.basePath));
    }
}

