/* tslint:disable */
/* eslint-disable */
/**
 * SaaS Control Plane API
 * Operator-only API for provisioning and operating isolated SaaS deployments. Audience saas-control; the operators Keycloak realm is the sole issuer (Phase 13 wires MFA + step-up + IP allowlist). The Bring-Your-Own-Domain endpoints live alongside core deployment CRUD because the verification + cert lifecycle is operator-owned (ADR 015). 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, replaceWithSerializableTypeIfNeeded } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { OperatorListResponse } from '../models';
/**
 * OperatorsApi - axios parameter creator
 */
export const OperatorsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary List operators (Phase 13 extends with MFA status).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listOperators: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/control/v1/operators`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            localVarHeaderParameter['Accept'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * OperatorsApi - functional programming interface
 */
export const OperatorsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = OperatorsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary List operators (Phase 13 extends with MFA status).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listOperators(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<OperatorListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listOperators(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['OperatorsApi.listOperators']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * OperatorsApi - factory interface
 */
export const OperatorsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = OperatorsApiFp(configuration)
    return {
        /**
         * 
         * @summary List operators (Phase 13 extends with MFA status).
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listOperators(options?: RawAxiosRequestConfig): AxiosPromise<OperatorListResponse> {
            return localVarFp.listOperators(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * OperatorsApi - interface
 */
export interface OperatorsApiInterface {
    /**
     * 
     * @summary List operators (Phase 13 extends with MFA status).
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    listOperators(options?: RawAxiosRequestConfig): AxiosPromise<OperatorListResponse>;

}

/**
 * OperatorsApi - object-oriented interface
 */
export class OperatorsApi extends BaseAPI implements OperatorsApiInterface {
    /**
     * 
     * @summary List operators (Phase 13 extends with MFA status).
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    public listOperators(options?: RawAxiosRequestConfig) {
        return OperatorsApiFp(this.configuration).listOperators(options).then((request) => request(this.axios, this.basePath));
    }
}

