FROM golang:1.24-alpine AS build
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
ARG VERSION=dev
ARG COMMIT=unknown
RUN CGO_ENABLED=0 go build \
    -ldflags="-s -w -X main.version=${VERSION} -X main.commit=${COMMIT}" \
    -o /out/dataplane ./cmd/dataplane

FROM gcr.io/distroless/static:nonroot
COPY --from=build /out/dataplane /dataplane
USER nonroot:nonroot
EXPOSE 9090
ENTRYPOINT ["/dataplane"]
