-- Organizations (Phase 7): organization + member + invitation.
--
-- AGENTS.md §7: Organization is an OPTIONAL intra-tenant team layer. MVP
-- auto-creates exactly one Organization per Tenant (slug = "default"); the
-- multi_org flag (per-Tenant, jsonb metadata) controls whether new
-- organizations may be created. Tenant remains the unit of isolation and
-- billing — Organizations only structure the user-facing membership graph.
--
-- Member: a User's membership in an Organization. role_id is a placeholder
-- (text, NULL-able) until Phase 8 RBAC introduces the role table + FK.
-- Phase 7 ships members without role assignment; "any active member can
-- invite" is the temporary policy.
--
-- Invitation: tokenised invite to join an Organization. The accept-token
-- is generated by crypto/rand (32 bytes), sha256-hashed for DB lookup,
-- and the email recipient is envelope-encrypted at rest (per
-- CONVENTIONS.md §10.1 — the new AAD format
-- deployment_id|resource_type|resource_id|field_name). An HMAC-SHA256
-- email_lookup_hash backs the per-org "one pending invite per email"
-- uniqueness predicate without ever storing plaintext.

CREATE TABLE organization (
    id              text PRIMARY KEY
                    CHECK (id LIKE 'org\_%' ESCAPE '\'),
    tenant_id       text NOT NULL REFERENCES tenant (id),
    slug            text NOT NULL,
    name            text NOT NULL,
    status          text NOT NULL DEFAULT 'active'
                    CHECK (status IN ('active', 'suspended', 'deleted')),
    metadata        jsonb NOT NULL DEFAULT '{}'::jsonb
                    CHECK (jsonb_typeof(metadata) = 'object'),
    row_seq         bigint NOT NULL DEFAULT 1,
    created_at      timestamptz NOT NULL DEFAULT now(),
    updated_at      timestamptz NOT NULL DEFAULT now(),
    deleted_at      timestamptz
);

CREATE UNIQUE INDEX organization_slug_unique
    ON organization (tenant_id, slug)
    WHERE deleted_at IS NULL;
CREATE INDEX organization_tenant_idx
    ON organization (tenant_id, status)
    WHERE deleted_at IS NULL;

CREATE TRIGGER organization_bump_row_seq
    BEFORE UPDATE ON organization
    FOR EACH ROW EXECUTE FUNCTION bump_row_seq();

ALTER TABLE organization ENABLE ROW LEVEL SECURITY;
ALTER TABLE organization FORCE  ROW LEVEL SECURITY;
CREATE POLICY organization_tenant_only ON organization
    USING (tenant_id = current_setting('app.current_tenant_id', true));


CREATE TABLE member (
    id               text PRIMARY KEY
                     CHECK (id LIKE 'member\_%' ESCAPE '\'),
    tenant_id        text NOT NULL REFERENCES tenant (id),
    organization_id  text NOT NULL REFERENCES organization (id),
    user_id          text NOT NULL REFERENCES platform_user (id),
    -- role_id is a forward placeholder for Phase 8 RBAC. NULL-able until
    -- the role table lands; the FK is added by the Phase 8 migration once
    -- the referenced table exists. Keep this as plain text for forward
    -- compatibility.
    role_id          text,
    status           text NOT NULL DEFAULT 'active'
                     CHECK (status IN ('active', 'suspended', 'removed')),
    metadata         jsonb NOT NULL DEFAULT '{}'::jsonb
                     CHECK (jsonb_typeof(metadata) = 'object'),
    row_seq          bigint NOT NULL DEFAULT 1,
    joined_at        timestamptz NOT NULL DEFAULT now(),
    updated_at       timestamptz NOT NULL DEFAULT now(),
    removed_at       timestamptz
);

-- One active membership per (organization, user). Removed rows retain
-- history; re-joining inserts a new row.
CREATE UNIQUE INDEX member_active_unique
    ON member (organization_id, user_id)
    WHERE status = 'active';
CREATE INDEX member_tenant_idx
    ON member (tenant_id, status);
CREATE INDEX member_user_idx
    ON member (user_id)
    WHERE status = 'active';
CREATE INDEX member_organization_idx
    ON member (organization_id, status);

CREATE TRIGGER member_bump_row_seq
    BEFORE UPDATE ON member
    FOR EACH ROW EXECUTE FUNCTION bump_row_seq();

ALTER TABLE member ENABLE ROW LEVEL SECURITY;
ALTER TABLE member FORCE  ROW LEVEL SECURITY;
CREATE POLICY member_tenant_only ON member
    USING (tenant_id = current_setting('app.current_tenant_id', true));


CREATE TABLE invitation (
    id                          text PRIMARY KEY
                                CHECK (id LIKE 'inv\_%' ESCAPE '\'),
    tenant_id                   text NOT NULL REFERENCES tenant (id),
    organization_id             text NOT NULL REFERENCES organization (id),

    -- Invitee email PII envelope columns (CONVENTIONS.md §10.1). The
    -- five-column set carries ciphertext + DEK + nonce + kid +
    -- key_version. plaintext is NEVER written here.
    invitee_email_lookup_hash   bytea NOT NULL,
    invitee_email_ciphertext    bytea NOT NULL,
    invitee_email_wrapped_dek   text  NOT NULL,
    invitee_email_nonce         bytea NOT NULL,
    invitee_email_kid           text  NOT NULL,
    invitee_email_key_version   integer NOT NULL,

    -- Accept token. The plaintext token (32 random bytes, base64-url) is
    -- ONLY emailed to the invitee; the DB carries:
    --   * token_hash    : sha256 of the raw token (constant-time lookup)
    --   * token_prefix  : first 8 chars of the base64-url plaintext for
    --                     operator-friendly identification in audit logs
    -- Refusing to envelope-encrypt the raw token avoids forensic-recovery
    -- footguns; a leaked DB cannot reconstruct a usable invite without
    -- the live transit key, and the platform never needs to "recover" the
    -- token because re-issuance is cheap.
    token_hash                  bytea NOT NULL UNIQUE,
    token_prefix                text  NOT NULL,

    invited_by_user_id          text  NOT NULL REFERENCES platform_user (id),
    proposed_role_id            text,
    status                      text  NOT NULL DEFAULT 'pending'
                                CHECK (status IN ('pending', 'accepted', 'revoked', 'expired')),
    expires_at                  timestamptz NOT NULL,
    accepted_at                 timestamptz,
    accepted_by_user_id         text REFERENCES platform_user (id),
    revoked_at                  timestamptz,
    revoked_by_user_id          text REFERENCES platform_user (id),
    row_seq                     bigint NOT NULL DEFAULT 1,
    created_at                  timestamptz NOT NULL DEFAULT now(),
    updated_at                  timestamptz NOT NULL DEFAULT now()
);

-- One pending invite per (org, email) — re-invite requires revoking the
-- previous one first. Other statuses do not block re-invitation.
CREATE UNIQUE INDEX invitation_pending_unique
    ON invitation (organization_id, invitee_email_lookup_hash)
    WHERE status = 'pending';
CREATE INDEX invitation_tenant_idx
    ON invitation (tenant_id, status);
CREATE INDEX invitation_token_prefix_idx
    ON invitation (token_prefix);
CREATE INDEX invitation_expires_idx
    ON invitation (expires_at)
    WHERE status = 'pending';
CREATE INDEX invitation_organization_idx
    ON invitation (organization_id, status);

CREATE TRIGGER invitation_bump_row_seq
    BEFORE UPDATE ON invitation
    FOR EACH ROW EXECUTE FUNCTION bump_row_seq();

ALTER TABLE invitation ENABLE ROW LEVEL SECURITY;
ALTER TABLE invitation FORCE  ROW LEVEL SECURITY;
CREATE POLICY invitation_tenant_only ON invitation
    USING (tenant_id = current_setting('app.current_tenant_id', true));


-- App role grants. Phase 11c tightens to per-Deployment app roles.
GRANT SELECT, INSERT, UPDATE, DELETE ON organization TO PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON member       TO PUBLIC;
GRANT SELECT, INSERT, UPDATE, DELETE ON invitation   TO PUBLIC;
