// Package controlplaneapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package controlplaneapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for AuditIntegrityResponseDataFirstMismatchReason.
const (
	PrevHash    AuditIntegrityResponseDataFirstMismatchReason = "prev_hash"
	RowHash     AuditIntegrityResponseDataFirstMismatchReason = "row_hash"
	SequenceGap AuditIntegrityResponseDataFirstMismatchReason = "sequence-gap"
)

// Valid indicates whether the value is a known member of the AuditIntegrityResponseDataFirstMismatchReason enum.
func (e AuditIntegrityResponseDataFirstMismatchReason) Valid() bool {
	switch e {
	case PrevHash:
		return true
	case RowHash:
		return true
	case SequenceGap:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// AuditIntegrityResponse defines model for AuditIntegrityResponse.
type AuditIntegrityResponse struct {
	Data struct {
		FirstMismatchId       *string                                        `json:"first_mismatch_id,omitempty"`
		FirstMismatchReason   *AuditIntegrityResponseDataFirstMismatchReason `json:"first_mismatch_reason,omitempty"`
		FirstMismatchSequence *int64                                         `json:"first_mismatch_sequence,omitempty"`
		FirstMismatchTenantId *string                                        `json:"first_mismatch_tenant_id,omitempty"`
		RowsChecked           int                                            `json:"rows_checked"`
		TenantsChecked        int                                            `json:"tenants_checked"`
		Verified              bool                                           `json:"verified"`
		VerifiedAt            time.Time                                      `json:"verified_at"`
	} `json:"data"`
}

// AuditIntegrityResponseDataFirstMismatchReason defines model for AuditIntegrityResponse.Data.FirstMismatchReason.
type AuditIntegrityResponseDataFirstMismatchReason string

// Health defines model for Health.
type Health struct {
	Commit  *string      `json:"commit,omitempty"`
	Status  HealthStatus `json:"status"`
	Version *string      `json:"version,omitempty"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// VerifyDeploymentAuditIntegrityParams defines parameters for VerifyDeploymentAuditIntegrity.
type VerifyDeploymentAuditIntegrityParams struct {
	// TenantId Optional — verify a single tenant's chain instead of every tenant on the Deployment.
	TenantId *string `form:"tenant_id,omitempty" json:"tenant_id,omitempty"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Walk the audit chain and report the first mismatch (if any).
	// (GET /control/v1/deployments/{deployment_id}/audit-integrity)
	VerifyDeploymentAuditIntegrity(w http.ResponseWriter, r *http.Request, deploymentId string, params VerifyDeploymentAuditIntegrityParams)
	// Liveness probe.
	// (GET /healthz)
	GetHealthz(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Walk the audit chain and report the first mismatch (if any).
// (GET /control/v1/deployments/{deployment_id}/audit-integrity)
func (_ Unimplemented) VerifyDeploymentAuditIntegrity(w http.ResponseWriter, r *http.Request, deploymentId string, params VerifyDeploymentAuditIntegrityParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Liveness probe.
// (GET /healthz)
func (_ Unimplemented) GetHealthz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// VerifyDeploymentAuditIntegrity operation middleware
func (siw *ServerInterfaceWrapper) VerifyDeploymentAuditIntegrity(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "deployment_id" -------------
	var deploymentId string

	err = runtime.BindStyledParameterWithOptions("simple", "deployment_id", chi.URLParam(r, "deployment_id"), &deploymentId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "deployment_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params VerifyDeploymentAuditIntegrityParams

	// ------------- Optional query parameter "tenant_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "tenant_id", r.URL.Query(), &params.TenantId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "tenant_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "tenant_id", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.VerifyDeploymentAuditIntegrity(w, r, deploymentId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/control/v1/deployments/{deployment_id}/audit-integrity", wrapper.VerifyDeploymentAuditIntegrity)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.GetHealthz)
	})

	return r
}

type VerifyDeploymentAuditIntegrityRequestObject struct {
	DeploymentId string `json:"deployment_id"`
	Params       VerifyDeploymentAuditIntegrityParams
}

type VerifyDeploymentAuditIntegrityResponseObject interface {
	VisitVerifyDeploymentAuditIntegrityResponse(w http.ResponseWriter) error
}

type VerifyDeploymentAuditIntegrity200JSONResponse AuditIntegrityResponse

func (response VerifyDeploymentAuditIntegrity200JSONResponse) VisitVerifyDeploymentAuditIntegrityResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthzRequestObject struct {
}

type GetHealthzResponseObject interface {
	VisitGetHealthzResponse(w http.ResponseWriter) error
}

type GetHealthz200JSONResponse Health

func (response GetHealthz200JSONResponse) VisitGetHealthzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Walk the audit chain and report the first mismatch (if any).
	// (GET /control/v1/deployments/{deployment_id}/audit-integrity)
	VerifyDeploymentAuditIntegrity(ctx context.Context, request VerifyDeploymentAuditIntegrityRequestObject) (VerifyDeploymentAuditIntegrityResponseObject, error)
	// Liveness probe.
	// (GET /healthz)
	GetHealthz(ctx context.Context, request GetHealthzRequestObject) (GetHealthzResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// VerifyDeploymentAuditIntegrity operation middleware
func (sh *strictHandler) VerifyDeploymentAuditIntegrity(w http.ResponseWriter, r *http.Request, deploymentId string, params VerifyDeploymentAuditIntegrityParams) {
	var request VerifyDeploymentAuditIntegrityRequestObject

	request.DeploymentId = deploymentId
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.VerifyDeploymentAuditIntegrity(ctx, request.(VerifyDeploymentAuditIntegrityRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "VerifyDeploymentAuditIntegrity")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(VerifyDeploymentAuditIntegrityResponseObject); ok {
		if err := validResponse.VisitVerifyDeploymentAuditIntegrityResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetHealthz operation middleware
func (sh *strictHandler) GetHealthz(w http.ResponseWriter, r *http.Request) {
	var request GetHealthzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealthz(ctx, request.(GetHealthzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealthz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetHealthzResponseObject); ok {
		if err := validResponse.VisitGetHealthzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"tFVtbhs3EL3KgC0QG5VWstMGxeaXkbRJ2qIN7KD9ERnGaHe8y5g7ZDhcCdtEQA/RO/QePUpPUpC7slaW",
	"89Ef/bcSyceZN+89vlOFbZxl4iAqf6ekqKnB9HnWljq84ECV16E7J3GWheKK89aRD5rSvhIDHv57rb2E",
	"q0ZLg6Gor3QZ/+TWGFwaUnnwLU1U6BypXEnwmiu1mdw95QnFcjxJ3DYqf62E3rbEBU0rdGqinKfVVY1S",
	"q4nydt1/Xk7+80Vb2FS59Q0GlSvN4dHX6oNgOlJD/h60QIwcPrdnb9dyVdRU3FA6cAjf431i04q8vtZ7",
	"q0trDSGPV69iZ6MeSww0DbohdVBZLI3ettpHzNc7/DsVH5a3f9vlLbBdvqEiHAAn/RzumqjnhCbUh9Iq",
	"bNPoMOpzx6UEDK2MBWNvRti7jSvyontpfbztAfGeLjYTpfnaJguQFF67kBDVL448Buunlk0HZy9fwLX1",
	"4Lxd6Xin5gqQS7BpW/ylxRoMVMIF4gWU5IztmujILLKrQxSPSmtPLAdvDbw0yBSh1agVNc/m2Unszjpi",
	"dFrl6mE2zx5Go2CoEy+zooeYrU5mo5tm73Y/rnS5mWF0/1Rv7R+PVhQ+0WwGr2qCokbNsEZzA1pA89T6",
	"kjw48tBL5TGEmhbsSVoTIJBvNGMgAQxxBZKdYGunDM5TDEgOY/dPFnzr/glszZ/B99bDinwHBn1FYzYh",
	"1FqAuHRWc1iwFjCWq6lvOQ4lVQWrE/AWywYdNHZFAjqA5WABYYnFTeVty+WC39hlBi9rFIKTOUitnaTj",
	"0nFRe8u2FZAaHWULVmkgcdaWX5QqV79Ge3RPbyvbT9o0LY8NBfKi8teHjMcPNPDPH39CcloHCKK5MjQQ",
	"/ECGIWiWQFiCvQZKpPTrYDlVuyshKk1H9Lct+VgCYxNVt4uyyfA23GeZy+iZ/n1IIjudz3ujciBOokHn",
	"jC4SBbM3Q6bv8L70dK1y9cVs9xjNhpdo9oFnKPnvDjE/JvdK2zToO5Wr36IEY59JzAMl0XqenPX3aQ2O",
	"9DUgd8fJeVhF/lU6rS43B3NJhEVn7fjac5EaR0mf/h/hcDNRszpF3u8fdNs5hdazwOl8Dmsd6jj4Bo2B",
	"PqbAYWcslrCuqZ/w4HZwKTC0ABq9ouxAks8oPB/u/h9nOST658zuJ70iJpGYm0saj6Oh+F4kDCG/2g6j",
	"9Ublqg7BST7bplwmiJLZBr1IxhRUlOoAdJfbvrikj3hFfJay3WDTrZvJ3UNn+zG59eM2ZDLYfwyiZWMw",
	"Sp+A8Y5pP5oYXgcKlZFEvV3DurZCIMF6Khe8zTwotWDliaTXhNR4+s2jo9t0hPfv4YcnF0cFsmVdoIGl",
	"Lbvj48mCrb/NVKjQxbROVzry0yEq+pqOzp599/Ori6wp4e+/vs0ewVdw9vR8wfOT0+NR6k9T6htb6WII",
	"Rc23Mfl4P4AfyIKfWVjraAAwyOV498mBhgeilprRd6BlwShCzdJQ2YfsMKnerpvLzb8BAAD//w==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
