// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Placeholder. Real control-plane queries land in Phase 11 (control plane
	// skeleton). sqlc rejects empty query directories so this stub satisfies the
	// generator without emitting any Go.
	GetControlPlaneBootstrap(ctx context.Context) (pgtype.Timestamptz, error)
}

var _ Querier = (*Queries)(nil)
