/* tslint:disable */
/* eslint-disable */
/**
 * SaaS Control Plane API
 * Operator-only API for provisioning and operating isolated SaaS deployments. Audience saas-control; the operators Keycloak realm is the sole issuer (Phase 13 wires MFA + step-up + IP allowlist). The Bring-Your-Own-Domain endpoints live alongside core deployment CRUD because the verification + cert lifecycle is operator-owned (ADR 015). 
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { DeploymentDomainVerificationRecord } from './deployment-domain-verification-record';

export interface DeploymentDomain {
    'id': string;
    'deployment_id': string;
    'domain': string;
    'is_primary'?: boolean;
    'status': DeploymentDomainStatusEnum;
    'verification_method': DeploymentDomainVerificationMethodEnum;
    'verification_record': DeploymentDomainVerificationRecord;
    'verified_at'?: string;
    'last_check_at'?: string;
    'last_check_error'?: string;
    'cert_status'?: DeploymentDomainCertStatusEnum;
    'created_at': string;
}

export const DeploymentDomainStatusEnum = {
    Pending: 'pending',
    Verified: 'verified',
    Failed: 'failed',
    Removed: 'removed',
} as const;

export type DeploymentDomainStatusEnum = typeof DeploymentDomainStatusEnum[keyof typeof DeploymentDomainStatusEnum];
export const DeploymentDomainVerificationMethodEnum = {
    DnsTxt: 'dns_txt',
} as const;

export type DeploymentDomainVerificationMethodEnum = typeof DeploymentDomainVerificationMethodEnum[keyof typeof DeploymentDomainVerificationMethodEnum];
export const DeploymentDomainCertStatusEnum = {
    Pending: 'pending',
    Issued: 'issued',
    Renewing: 'renewing',
    Failed: 'failed',
    Revoked: 'revoked',
} as const;

export type DeploymentDomainCertStatusEnum = typeof DeploymentDomainCertStatusEnum[keyof typeof DeploymentDomainCertStatusEnum];


