/* tslint:disable */
/* eslint-disable */
/**
 * SaaS Control Plane API
 * Operator-only API for provisioning and operating isolated SaaS deployments.
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface Health {
    'status': HealthStatusEnum;
    'version'?: string;
    'commit'?: string;
}

export const HealthStatusEnum = {
    Ok: 'ok',
} as const;

export type HealthStatusEnum = typeof HealthStatusEnum[keyof typeof HealthStatusEnum];


