// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: authorization.sql

package db

import (
	"context"
)

const assignMemberRole = `-- name: AssignMemberRole :one
INSERT INTO member_role (member_id, role_id, tenant_id, assigned_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (member_id, role_id) DO UPDATE
    SET assigned_by = EXCLUDED.assigned_by,
        assigned_at = now()
RETURNING member_id, role_id, tenant_id, assigned_by, assigned_at
`

type AssignMemberRoleParams struct {
	MemberID   string `json:"member_id"`
	RoleID     string `json:"role_id"`
	TenantID   string `json:"tenant_id"`
	AssignedBy string `json:"assigned_by"`
}

func (q *Queries) AssignMemberRole(ctx context.Context, arg AssignMemberRoleParams) (MemberRole, error) {
	row := q.db.QueryRow(ctx, assignMemberRole,
		arg.MemberID,
		arg.RoleID,
		arg.TenantID,
		arg.AssignedBy,
	)
	var i MemberRole
	err := row.Scan(
		&i.MemberID,
		&i.RoleID,
		&i.TenantID,
		&i.AssignedBy,
		&i.AssignedAt,
	)
	return i, err
}

const createRole = `-- name: CreateRole :one

INSERT INTO role (id, tenant_id, name, description, is_system, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, tenant_id, name, description, is_system, metadata, row_seq, created_at, updated_at, deleted_at
`

type CreateRoleParams struct {
	ID          string  `json:"id"`
	TenantID    string  `json:"tenant_id"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
	IsSystem    bool    `json:"is_system"`
	Metadata    []byte  `json:"metadata"`
}

// Authorization (Phase 8) queries.
//
// Owns the role catalogue, the permission catalogue, and the member_role
// assignment denormalisation. The casbin_rule table is owned by the Casbin
// pgx adapter; we never query it directly from sqlc — the adapter's
// AddPolicy / RemovePolicy / LoadPolicy is the only writer/reader.
func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.Description,
		arg.IsSystem,
		arg.Metadata,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.Metadata,
		&i.RowSeq,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMemberTenantID = `-- name: GetMemberTenantID :one
SELECT tenant_id
FROM member
WHERE id = $1
`

// Resolves the tenant a member belongs to. Used by the authorization
// service before consulting the enforcer so cross-tenant Check requests
// can be rejected before any policy round-trip.
func (q *Queries) GetMemberTenantID(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getMemberTenantID, id)
	var tenant_id string
	err := row.Scan(&tenant_id)
	return tenant_id, err
}

const getRole = `-- name: GetRole :one
SELECT id, tenant_id, name, description, is_system, metadata, row_seq, created_at, updated_at, deleted_at
FROM role
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetRole(ctx context.Context, id string) (Role, error) {
	row := q.db.QueryRow(ctx, getRole, id)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.Metadata,
		&i.RowSeq,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listMemberRoles = `-- name: ListMemberRoles :many
SELECT mr.member_id, mr.role_id, mr.tenant_id, mr.assigned_by, mr.assigned_at
FROM member_role mr
WHERE mr.member_id = $1
ORDER BY mr.assigned_at DESC
`

func (q *Queries) ListMemberRoles(ctx context.Context, memberID string) ([]MemberRole, error) {
	rows, err := q.db.Query(ctx, listMemberRoles, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MemberRole
	for rows.Next() {
		var i MemberRole
		if err := rows.Scan(
			&i.MemberID,
			&i.RoleID,
			&i.TenantID,
			&i.AssignedBy,
			&i.AssignedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPermissions = `-- name: ListPermissions :many
SELECT id, resource_type, action, description, module, is_system
FROM permission
ORDER BY module, resource_type, action
`

func (q *Queries) ListPermissions(ctx context.Context) ([]Permission, error) {
	rows, err := q.db.Query(ctx, listPermissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Permission
	for rows.Next() {
		var i Permission
		if err := rows.Scan(
			&i.ID,
			&i.ResourceType,
			&i.Action,
			&i.Description,
			&i.Module,
			&i.IsSystem,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolesByTenant = `-- name: ListRolesByTenant :many
SELECT id, tenant_id, name, description, is_system, metadata, row_seq, created_at, updated_at, deleted_at
FROM role
WHERE tenant_id = $1
  AND deleted_at IS NULL
ORDER BY created_at DESC, id DESC
LIMIT $2::int
`

type ListRolesByTenantParams struct {
	TenantID string `json:"tenant_id"`
	RowLimit int32  `json:"row_limit"`
}

func (q *Queries) ListRolesByTenant(ctx context.Context, arg ListRolesByTenantParams) ([]Role, error) {
	rows, err := q.db.Query(ctx, listRolesByTenant, arg.TenantID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Role
	for rows.Next() {
		var i Role
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.Description,
			&i.IsSystem,
			&i.Metadata,
			&i.RowSeq,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteRole = `-- name: SoftDeleteRole :one
UPDATE role
SET deleted_at = now()
WHERE id = $1 AND row_seq = $2 AND deleted_at IS NULL
RETURNING id, tenant_id, name, description, is_system, metadata, row_seq, created_at, updated_at, deleted_at
`

type SoftDeleteRoleParams struct {
	ID     string `json:"id"`
	RowSeq int64  `json:"row_seq"`
}

func (q *Queries) SoftDeleteRole(ctx context.Context, arg SoftDeleteRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, softDeleteRole, arg.ID, arg.RowSeq)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.Metadata,
		&i.RowSeq,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const unassignMemberRole = `-- name: UnassignMemberRole :execrows
DELETE FROM member_role
WHERE member_id = $1 AND role_id = $2
`

type UnassignMemberRoleParams struct {
	MemberID string `json:"member_id"`
	RoleID   string `json:"role_id"`
}

func (q *Queries) UnassignMemberRole(ctx context.Context, arg UnassignMemberRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, unassignMemberRole, arg.MemberID, arg.RoleID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateRole = `-- name: UpdateRole :one
UPDATE role
SET name        = COALESCE($3,        name),
    description = COALESCE($4, description),
    metadata    = COALESCE($5,    metadata)
WHERE id = $1 AND row_seq = $2 AND deleted_at IS NULL
RETURNING id, tenant_id, name, description, is_system, metadata, row_seq, created_at, updated_at, deleted_at
`

type UpdateRoleParams struct {
	ID          string  `json:"id"`
	RowSeq      int64   `json:"row_seq"`
	Name        *string `json:"name"`
	Description *string `json:"description"`
	Metadata    []byte  `json:"metadata"`
}

func (q *Queries) UpdateRole(ctx context.Context, arg UpdateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, updateRole,
		arg.ID,
		arg.RowSeq,
		arg.Name,
		arg.Description,
		arg.Metadata,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.Description,
		&i.IsSystem,
		&i.Metadata,
		&i.RowSeq,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
