// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type IdempotencyRecord struct {
	ID              int64              `json:"id"`
	TenantID        string             `json:"tenant_id"`
	IdempotencyKey  string             `json:"idempotency_key"`
	Route           string             `json:"route"`
	Method          string             `json:"method"`
	RequestBodyHash []byte             `json:"request_body_hash"`
	ResponseStatus  *int32             `json:"response_status"`
	ResponseHeaders []byte             `json:"response_headers"`
	ResponseBody    []byte             `json:"response_body"`
	InFlight        bool               `json:"in_flight"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
}

type OutboxEvent struct {
	ID               int64              `json:"id"`
	EventID          string             `json:"event_id"`
	Type             string             `json:"type"`
	EventVersion     int32              `json:"event_version"`
	TenantID         *string            `json:"tenant_id"`
	DeploymentID     string             `json:"deployment_id"`
	OccurredAt       pgtype.Timestamptz `json:"occurred_at"`
	Payload          []byte             `json:"payload"`
	PublishedAt      pgtype.Timestamptz `json:"published_at"`
	DeliveryAttempts int32              `json:"delivery_attempts"`
	LastError        *string            `json:"last_error"`
}

type SchemaBootstrapDataplane struct {
	BootstrappedAt pgtype.Timestamptz `json:"bootstrapped_at"`
}

type Tenant struct {
	ID                    string             `json:"id"`
	Slug                  string             `json:"slug"`
	Name                  string             `json:"name"`
	Status                string             `json:"status"`
	DefaultOrganizationID *string            `json:"default_organization_id"`
	Metadata              []byte             `json:"metadata"`
	RowSeq                int64              `json:"row_seq"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	DeletedAt             pgtype.Timestamptz `json:"deleted_at"`
}
