// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createNotification = `-- name: CreateNotification :one
INSERT INTO notification (
    id, tenant_id, workflow_name, to_user_id,
    payload_ciphertext, payload_wrapped_dek, payload_nonce, payload_kid, payload_key_version,
    status
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, tenant_id, workflow_name, to_user_id, payload_ciphertext, payload_wrapped_dek, payload_nonce, payload_kid, payload_key_version, novu_transaction_id, status, queued_at, sent_at, delivered_at, failed_at, failure_reason, row_seq
`

type CreateNotificationParams struct {
	ID                string `json:"id"`
	TenantID          string `json:"tenant_id"`
	WorkflowName      string `json:"workflow_name"`
	ToUserID          string `json:"to_user_id"`
	PayloadCiphertext []byte `json:"payload_ciphertext"`
	PayloadWrappedDek string `json:"payload_wrapped_dek"`
	PayloadNonce      []byte `json:"payload_nonce"`
	PayloadKid        string `json:"payload_kid"`
	PayloadKeyVersion int32  `json:"payload_key_version"`
	Status            string `json:"status"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.ID,
		arg.TenantID,
		arg.WorkflowName,
		arg.ToUserID,
		arg.PayloadCiphertext,
		arg.PayloadWrappedDek,
		arg.PayloadNonce,
		arg.PayloadKid,
		arg.PayloadKeyVersion,
		arg.Status,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorkflowName,
		&i.ToUserID,
		&i.PayloadCiphertext,
		&i.PayloadWrappedDek,
		&i.PayloadNonce,
		&i.PayloadKid,
		&i.PayloadKeyVersion,
		&i.NovuTransactionID,
		&i.Status,
		&i.QueuedAt,
		&i.SentAt,
		&i.DeliveredAt,
		&i.FailedAt,
		&i.FailureReason,
		&i.RowSeq,
	)
	return i, err
}

const createNotificationChannel = `-- name: CreateNotificationChannel :one
INSERT INTO notification_channel (
    id, tenant_id,
    provider, name, config,
    secrets_ciphertext, secrets_wrapped_dek, secrets_nonce, secrets_kid, secrets_key_version,
    is_default_for, status
)
VALUES (
    $1, $2,
    $3, $4, $5,
    $6, $7, $8, $9, $10,
    $11, $12
)
RETURNING id, tenant_id, provider, name, config, secrets_ciphertext, secrets_wrapped_dek, secrets_nonce, secrets_kid, secrets_key_version, is_default_for, status, novu_integration_id, last_rotated_at, row_seq, created_at, updated_at, deleted_at
`

type CreateNotificationChannelParams struct {
	ID                string   `json:"id"`
	TenantID          string   `json:"tenant_id"`
	Provider          string   `json:"provider"`
	Name              string   `json:"name"`
	Config            []byte   `json:"config"`
	SecretsCiphertext []byte   `json:"secrets_ciphertext"`
	SecretsWrappedDek *string  `json:"secrets_wrapped_dek"`
	SecretsNonce      []byte   `json:"secrets_nonce"`
	SecretsKid        *string  `json:"secrets_kid"`
	SecretsKeyVersion *int32   `json:"secrets_key_version"`
	IsDefaultFor      []string `json:"is_default_for"`
	Status            string   `json:"status"`
}

// Inserts a new channel row. The repo layer runs the strict envelope walker
// on the secrets payload before binding the parameters; this query is a thin
// shim over a fully-formed row.
func (q *Queries) CreateNotificationChannel(ctx context.Context, arg CreateNotificationChannelParams) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, createNotificationChannel,
		arg.ID,
		arg.TenantID,
		arg.Provider,
		arg.Name,
		arg.Config,
		arg.SecretsCiphertext,
		arg.SecretsWrappedDek,
		arg.SecretsNonce,
		arg.SecretsKid,
		arg.SecretsKeyVersion,
		arg.IsDefaultFor,
		arg.Status,
	)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Provider,
		&i.Name,
		&i.Config,
		&i.SecretsCiphertext,
		&i.SecretsWrappedDek,
		&i.SecretsNonce,
		&i.SecretsKid,
		&i.SecretsKeyVersion,
		&i.IsDefaultFor,
		&i.Status,
		&i.NovuIntegrationID,
		&i.LastRotatedAt,
		&i.RowSeq,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getNotification = `-- name: GetNotification :one
SELECT id, tenant_id, workflow_name, to_user_id, payload_ciphertext, payload_wrapped_dek, payload_nonce, payload_kid, payload_key_version, novu_transaction_id, status, queued_at, sent_at, delivered_at, failed_at, failure_reason, row_seq
FROM notification
WHERE id = $1
`

func (q *Queries) GetNotification(ctx context.Context, id string) (Notification, error) {
	row := q.db.QueryRow(ctx, getNotification, id)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorkflowName,
		&i.ToUserID,
		&i.PayloadCiphertext,
		&i.PayloadWrappedDek,
		&i.PayloadNonce,
		&i.PayloadKid,
		&i.PayloadKeyVersion,
		&i.NovuTransactionID,
		&i.Status,
		&i.QueuedAt,
		&i.SentAt,
		&i.DeliveredAt,
		&i.FailedAt,
		&i.FailureReason,
		&i.RowSeq,
	)
	return i, err
}

const getNotificationChannel = `-- name: GetNotificationChannel :one
SELECT id, tenant_id, provider, name, config, secrets_ciphertext, secrets_wrapped_dek, secrets_nonce, secrets_kid, secrets_key_version, is_default_for, status, novu_integration_id, last_rotated_at, row_seq, created_at, updated_at, deleted_at
FROM notification_channel
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetNotificationChannel(ctx context.Context, id string) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, getNotificationChannel, id)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Provider,
		&i.Name,
		&i.Config,
		&i.SecretsCiphertext,
		&i.SecretsWrappedDek,
		&i.SecretsNonce,
		&i.SecretsKid,
		&i.SecretsKeyVersion,
		&i.IsDefaultFor,
		&i.Status,
		&i.NovuIntegrationID,
		&i.LastRotatedAt,
		&i.RowSeq,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getNotificationChannelByName = `-- name: GetNotificationChannelByName :one
SELECT id, tenant_id, provider, name, config, secrets_ciphertext, secrets_wrapped_dek, secrets_nonce, secrets_kid, secrets_key_version, is_default_for, status, novu_integration_id, last_rotated_at, row_seq, created_at, updated_at, deleted_at
FROM notification_channel
WHERE tenant_id = $1 AND name = $2 AND deleted_at IS NULL
`

type GetNotificationChannelByNameParams struct {
	TenantID string `json:"tenant_id"`
	Name     string `json:"name"`
}

func (q *Queries) GetNotificationChannelByName(ctx context.Context, arg GetNotificationChannelByNameParams) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, getNotificationChannelByName, arg.TenantID, arg.Name)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Provider,
		&i.Name,
		&i.Config,
		&i.SecretsCiphertext,
		&i.SecretsWrappedDek,
		&i.SecretsNonce,
		&i.SecretsKid,
		&i.SecretsKeyVersion,
		&i.IsDefaultFor,
		&i.Status,
		&i.NovuIntegrationID,
		&i.LastRotatedAt,
		&i.RowSeq,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getNotificationWorkflow = `-- name: GetNotificationWorkflow :one
SELECT id, tenant_id, name, novu_workflow_id, description, created_at
FROM notification_workflow
WHERE id = $1
`

func (q *Queries) GetNotificationWorkflow(ctx context.Context, id string) (NotificationWorkflow, error) {
	row := q.db.QueryRow(ctx, getNotificationWorkflow, id)
	var i NotificationWorkflow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.NovuWorkflowID,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getNotificationWorkflowByName = `-- name: GetNotificationWorkflowByName :one
SELECT id, tenant_id, name, novu_workflow_id, description, created_at
FROM notification_workflow
WHERE tenant_id = $1 AND name = $2
`

type GetNotificationWorkflowByNameParams struct {
	TenantID string `json:"tenant_id"`
	Name     string `json:"name"`
}

func (q *Queries) GetNotificationWorkflowByName(ctx context.Context, arg GetNotificationWorkflowByNameParams) (NotificationWorkflow, error) {
	row := q.db.QueryRow(ctx, getNotificationWorkflowByName, arg.TenantID, arg.Name)
	var i NotificationWorkflow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.NovuWorkflowID,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const insertNotificationAttempt = `-- name: InsertNotificationAttempt :exec
INSERT INTO notification_attempt (notification_id, status, failure_reason)
VALUES ($1, $2, $3)
`

type InsertNotificationAttemptParams struct {
	NotificationID string  `json:"notification_id"`
	Status         string  `json:"status"`
	FailureReason  *string `json:"failure_reason"`
}

func (q *Queries) InsertNotificationAttempt(ctx context.Context, arg InsertNotificationAttemptParams) error {
	_, err := q.db.Exec(ctx, insertNotificationAttempt, arg.NotificationID, arg.Status, arg.FailureReason)
	return err
}

const listNotificationChannels = `-- name: ListNotificationChannels :many
SELECT id, tenant_id, provider, name, config, secrets_ciphertext, secrets_wrapped_dek, secrets_nonce, secrets_kid, secrets_key_version, is_default_for, status, novu_integration_id, last_rotated_at, row_seq, created_at, updated_at, deleted_at
FROM notification_channel
WHERE tenant_id = $1
  AND deleted_at IS NULL
ORDER BY created_at DESC, id DESC
LIMIT $2::int
`

type ListNotificationChannelsParams struct {
	TenantID string `json:"tenant_id"`
	RowLimit int32  `json:"row_limit"`
}

func (q *Queries) ListNotificationChannels(ctx context.Context, arg ListNotificationChannelsParams) ([]NotificationChannel, error) {
	rows, err := q.db.Query(ctx, listNotificationChannels, arg.TenantID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationChannel
	for rows.Next() {
		var i NotificationChannel
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Provider,
			&i.Name,
			&i.Config,
			&i.SecretsCiphertext,
			&i.SecretsWrappedDek,
			&i.SecretsNonce,
			&i.SecretsKid,
			&i.SecretsKeyVersion,
			&i.IsDefaultFor,
			&i.Status,
			&i.NovuIntegrationID,
			&i.LastRotatedAt,
			&i.RowSeq,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotificationWorkflows = `-- name: ListNotificationWorkflows :many
SELECT id, tenant_id, name, novu_workflow_id, description, created_at
FROM notification_workflow
WHERE tenant_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListNotificationWorkflows(ctx context.Context, tenantID string) ([]NotificationWorkflow, error) {
	rows, err := q.db.Query(ctx, listNotificationWorkflows, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationWorkflow
	for rows.Next() {
		var i NotificationWorkflow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.NovuWorkflowID,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotifications = `-- name: ListNotifications :many
SELECT id, tenant_id, workflow_name, to_user_id, payload_ciphertext, payload_wrapped_dek, payload_nonce, payload_kid, payload_key_version, novu_transaction_id, status, queued_at, sent_at, delivered_at, failed_at, failure_reason, row_seq
FROM notification
WHERE tenant_id = $1
  AND (
      $2::timestamptz IS NULL
      OR (queued_at, id) < ($2::timestamptz, $3::text)
  )
ORDER BY queued_at DESC, id DESC
LIMIT $4::int
`

type ListNotificationsParams struct {
	TenantID       string             `json:"tenant_id"`
	CursorQueuedAt pgtype.Timestamptz `json:"cursor_queued_at"`
	CursorID       *string            `json:"cursor_id"`
	RowLimit       int32              `json:"row_limit"`
}

func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, listNotifications,
		arg.TenantID,
		arg.CursorQueuedAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.WorkflowName,
			&i.ToUserID,
			&i.PayloadCiphertext,
			&i.PayloadWrappedDek,
			&i.PayloadNonce,
			&i.PayloadKid,
			&i.PayloadKeyVersion,
			&i.NovuTransactionID,
			&i.Status,
			&i.QueuedAt,
			&i.SentAt,
			&i.DeliveredAt,
			&i.FailedAt,
			&i.FailureReason,
			&i.RowSeq,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerNotificationWorkflow = `-- name: RegisterNotificationWorkflow :one
INSERT INTO notification_workflow (id, tenant_id, name, novu_workflow_id, description)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, tenant_id, name, novu_workflow_id, description, created_at
`

type RegisterNotificationWorkflowParams struct {
	ID             string  `json:"id"`
	TenantID       string  `json:"tenant_id"`
	Name           string  `json:"name"`
	NovuWorkflowID string  `json:"novu_workflow_id"`
	Description    *string `json:"description"`
}

func (q *Queries) RegisterNotificationWorkflow(ctx context.Context, arg RegisterNotificationWorkflowParams) (NotificationWorkflow, error) {
	row := q.db.QueryRow(ctx, registerNotificationWorkflow,
		arg.ID,
		arg.TenantID,
		arg.Name,
		arg.NovuWorkflowID,
		arg.Description,
	)
	var i NotificationWorkflow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.NovuWorkflowID,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const rotateNotificationChannelSecrets = `-- name: RotateNotificationChannelSecrets :one
UPDATE notification_channel
SET
    secrets_ciphertext  = $2,
    secrets_wrapped_dek = $3,
    secrets_nonce       = $4,
    secrets_kid         = $5,
    secrets_key_version = $6,
    last_rotated_at     = now()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING id, tenant_id, provider, name, config, secrets_ciphertext, secrets_wrapped_dek, secrets_nonce, secrets_kid, secrets_key_version, is_default_for, status, novu_integration_id, last_rotated_at, row_seq, created_at, updated_at, deleted_at
`

type RotateNotificationChannelSecretsParams struct {
	ID                string  `json:"id"`
	SecretsCiphertext []byte  `json:"secrets_ciphertext"`
	SecretsWrappedDek *string `json:"secrets_wrapped_dek"`
	SecretsNonce      []byte  `json:"secrets_nonce"`
	SecretsKid        *string `json:"secrets_kid"`
	SecretsKeyVersion *int32  `json:"secrets_key_version"`
}

// Rotation endpoint: swaps the envelope columns and stamps last_rotated_at.
// Bumps row_seq via the trigger.
func (q *Queries) RotateNotificationChannelSecrets(ctx context.Context, arg RotateNotificationChannelSecretsParams) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, rotateNotificationChannelSecrets,
		arg.ID,
		arg.SecretsCiphertext,
		arg.SecretsWrappedDek,
		arg.SecretsNonce,
		arg.SecretsKid,
		arg.SecretsKeyVersion,
	)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Provider,
		&i.Name,
		&i.Config,
		&i.SecretsCiphertext,
		&i.SecretsWrappedDek,
		&i.SecretsNonce,
		&i.SecretsKid,
		&i.SecretsKeyVersion,
		&i.IsDefaultFor,
		&i.Status,
		&i.NovuIntegrationID,
		&i.LastRotatedAt,
		&i.RowSeq,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const setNotificationChannelNovuIntegration = `-- name: SetNotificationChannelNovuIntegration :exec
UPDATE notification_channel
SET novu_integration_id = $2
WHERE id = $1
  AND deleted_at IS NULL
`

type SetNotificationChannelNovuIntegrationParams struct {
	ID                string  `json:"id"`
	NovuIntegrationID *string `json:"novu_integration_id"`
}

func (q *Queries) SetNotificationChannelNovuIntegration(ctx context.Context, arg SetNotificationChannelNovuIntegrationParams) error {
	_, err := q.db.Exec(ctx, setNotificationChannelNovuIntegration, arg.ID, arg.NovuIntegrationID)
	return err
}

const softDeleteNotificationChannel = `-- name: SoftDeleteNotificationChannel :execrows
UPDATE notification_channel
SET status = 'disabled',
    deleted_at = now()
WHERE id = $1
  AND row_seq = $2
  AND deleted_at IS NULL
`

type SoftDeleteNotificationChannelParams struct {
	ID     string `json:"id"`
	RowSeq int64  `json:"row_seq"`
}

func (q *Queries) SoftDeleteNotificationChannel(ctx context.Context, arg SoftDeleteNotificationChannelParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteNotificationChannel, arg.ID, arg.RowSeq)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateNotificationChannelMeta = `-- name: UpdateNotificationChannelMeta :one
UPDATE notification_channel
SET
    name           = COALESCE($3, name),
    status         = COALESCE($4, status),
    is_default_for = COALESCE($5::text[], is_default_for),
    config         = COALESCE($6, config)
WHERE id = $1
  AND row_seq = $2
  AND deleted_at IS NULL
RETURNING id, tenant_id, provider, name, config, secrets_ciphertext, secrets_wrapped_dek, secrets_nonce, secrets_kid, secrets_key_version, is_default_for, status, novu_integration_id, last_rotated_at, row_seq, created_at, updated_at, deleted_at
`

type UpdateNotificationChannelMetaParams struct {
	ID           string   `json:"id"`
	RowSeq       int64    `json:"row_seq"`
	Name         *string  `json:"name"`
	Status       *string  `json:"status"`
	IsDefaultFor []string `json:"is_default_for"`
	Config       []byte   `json:"config"`
}

// Metadata-only patch under optimistic concurrency. Does NOT accept new
// credentials (per ADR 017 rotation is a distinct verb).
func (q *Queries) UpdateNotificationChannelMeta(ctx context.Context, arg UpdateNotificationChannelMetaParams) (NotificationChannel, error) {
	row := q.db.QueryRow(ctx, updateNotificationChannelMeta,
		arg.ID,
		arg.RowSeq,
		arg.Name,
		arg.Status,
		arg.IsDefaultFor,
		arg.Config,
	)
	var i NotificationChannel
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Provider,
		&i.Name,
		&i.Config,
		&i.SecretsCiphertext,
		&i.SecretsWrappedDek,
		&i.SecretsNonce,
		&i.SecretsKid,
		&i.SecretsKeyVersion,
		&i.IsDefaultFor,
		&i.Status,
		&i.NovuIntegrationID,
		&i.LastRotatedAt,
		&i.RowSeq,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateNotificationStatus = `-- name: UpdateNotificationStatus :one
UPDATE notification
SET status         = $2,
    sent_at        = CASE WHEN $2 = 'sent'      THEN now() ELSE sent_at      END,
    delivered_at   = CASE WHEN $2 = 'delivered' THEN now() ELSE delivered_at END,
    failed_at      = CASE WHEN $2 = 'failed'    THEN now() ELSE failed_at    END,
    failure_reason = $3,
    novu_transaction_id = COALESCE($4, novu_transaction_id)
WHERE id = $1
RETURNING id, tenant_id, workflow_name, to_user_id, payload_ciphertext, payload_wrapped_dek, payload_nonce, payload_kid, payload_key_version, novu_transaction_id, status, queued_at, sent_at, delivered_at, failed_at, failure_reason, row_seq
`

type UpdateNotificationStatusParams struct {
	ID                string  `json:"id"`
	Status            string  `json:"status"`
	FailureReason     *string `json:"failure_reason"`
	NovuTransactionID *string `json:"novu_transaction_id"`
}

func (q *Queries) UpdateNotificationStatus(ctx context.Context, arg UpdateNotificationStatusParams) (Notification, error) {
	row := q.db.QueryRow(ctx, updateNotificationStatus,
		arg.ID,
		arg.Status,
		arg.FailureReason,
		arg.NovuTransactionID,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.WorkflowName,
		&i.ToUserID,
		&i.PayloadCiphertext,
		&i.PayloadWrappedDek,
		&i.PayloadNonce,
		&i.PayloadKid,
		&i.PayloadKeyVersion,
		&i.NovuTransactionID,
		&i.Status,
		&i.QueuedAt,
		&i.SentAt,
		&i.DeliveredAt,
		&i.FailedAt,
		&i.FailureReason,
		&i.RowSeq,
	)
	return i, err
}

const updateNotificationWorkflow = `-- name: UpdateNotificationWorkflow :one
UPDATE notification_workflow
SET
    novu_workflow_id = COALESCE($2, novu_workflow_id),
    description      = COALESCE($3, description)
WHERE id = $1 AND tenant_id = $4
RETURNING id, tenant_id, name, novu_workflow_id, description, created_at
`

type UpdateNotificationWorkflowParams struct {
	ID             string  `json:"id"`
	NovuWorkflowID *string `json:"novu_workflow_id"`
	Description    *string `json:"description"`
	TenantID       string  `json:"tenant_id"`
}

// COALESCE keeps each column unchanged when the caller passes NULL. The
// description column accepts an explicit NULL only by clearing the patch
// field at the service layer; the wire-level patch model carries a flag.
func (q *Queries) UpdateNotificationWorkflow(ctx context.Context, arg UpdateNotificationWorkflowParams) (NotificationWorkflow, error) {
	row := q.db.QueryRow(ctx, updateNotificationWorkflow,
		arg.ID,
		arg.NovuWorkflowID,
		arg.Description,
		arg.TenantID,
	)
	var i NotificationWorkflow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.NovuWorkflowID,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}
