"""Employee-submitted salary survey adapter — stub.

This is the integration point for self-reported compensation data we expect to collect
later (e.g. via a partner site, a SaaS form, or an academic survey). Per CLAUDE.md, the
canonical shape is :class:`EmployeeSurveyRow`; the iteration runner ingests it via the
same path as any other source and fine-tunes the production bundle on the combined
dataset.

Confidence prior: 0.55-0.75 depending on verification. Lower than authoritative
microdata (GOSI ~0.95), higher than scraped postings (0.4).

Data-quality concerns specific to this source (handle before training):

- self-selection (high earners over-represented)
- self-inflation (people round up; ~5-10% upward bias documented in academic literature)
- monthly vs annual confusion (validate against segment percentiles)
- currency misclassification (auto-detect by magnitude)
- duplicates from the same person across time (de-dup by hashed contact)

Schema expected from upstream:

| field                | type    | notes                                       |
|----------------------|---------|---------------------------------------------|
| submission_id        | str     | UUID generated by the collection layer      |
| submitted_at         | date    |                                             |
| respondent_hash      | str     | salted hash for dedup; never raw email      |
| family_raw           | str     | normalized via data.taxonomy on ingest      |
| level_raw            | str     |                                             |
| years_experience     | float   |                                             |
| years_at_employer    | float   |                                             |
| education            | str     |                                             |
| employer_name_raw    | str     | normalized via fuzzy match                  |
| employer_size_bucket | str     |                                             |
| sector_raw           | str     | ISIC mapped                                 |
| region_raw           | str     |                                             |
| employment_type      | str     |                                             |
| work_mode            | str     |                                             |
| base_monthly         | float   | SAR, gross                                  |
| housing_monthly      | float?  |                                             |
| transport_monthly    | float?  |                                             |
| other_fixed_monthly  | float?  |                                             |
| annual_bonus         | float?  | annualized; converted to monthly_eq         |
| equity_value         | float?  | annual expected value                       |
| is_saudi             | bool    |                                             |
| gender               | str?    | optional; recommendation head blinds        |
| age_bucket           | str?    | optional; recommendation head blinds        |
| verification_method  | str     | 'unverified' / 'email_domain' / 'payslip'   |
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path

import pandas as pd
from pydantic import BaseModel, ConfigDict, Field, NonNegativeFloat

from salary_model.config import get_logger
from salary_model.data.sources._common import FetchManifest

log = get_logger("salary_model.data.sources.employee_survey")
_ = FetchManifest


class EmployeeSurveyRow(BaseModel):
    """Typed shape of one employee self-reported salary record."""

    model_config = ConfigDict(frozen=True, extra="forbid")

    submission_id: str = Field(min_length=8)
    submitted_at: datetime
    respondent_hash: str = Field(min_length=8)
    family_raw: str
    level_raw: str
    years_experience: float = Field(ge=0.0, le=60.0)
    years_at_employer: float = Field(ge=0.0, le=60.0)
    education: str
    employer_name_raw: str
    employer_size_bucket: str
    sector_raw: str
    region_raw: str
    employment_type: str = Field(pattern="^(ft|pt|contract|intern)$")
    work_mode: str = Field(pattern="^(onsite|hybrid|remote)$")
    base_monthly: NonNegativeFloat
    housing_monthly: NonNegativeFloat | None = None
    transport_monthly: NonNegativeFloat | None = None
    other_fixed_monthly: NonNegativeFloat | None = None
    annual_bonus: NonNegativeFloat | None = None
    equity_value: NonNegativeFloat | None = None
    is_saudi: bool
    gender: str | None = Field(default=None, pattern="^[MF]$")
    age_bucket: str | None = None
    verification_method: str = Field(
        default="unverified", pattern="^(unverified|email_domain|payslip|hr_attested)$",
    )


def fetch_employee_surveys(
    *, parquet_path: Path | None = None,
) -> tuple[pd.DataFrame, FetchManifest]:
    """Load employee-survey submissions from a local Parquet drop. Not implemented in v0.

    When the collection layer is live, point ``parquet_path`` at the daily extract and
    parse against :class:`EmployeeSurveyRow`. The training pipeline will combine this
    with synthetic rows automatically; the per-row ``confidence`` (based on
    ``verification_method``) drives sample weighting.
    """
    path_str = str(parquet_path) if parquet_path else None
    log.warning("employee_survey_loader_not_implemented", path=path_str)
    msg = (
        "Employee-survey loader is a scaffold. Wire the collection layer's daily "
        "Parquet path, parse against EmployeeSurveyRow, run data-quality checks "
        "(§16 of the design doc), then return (DataFrame, FetchManifest)."
    )
    raise NotImplementedError(msg)


__all__ = ["EmployeeSurveyRow", "fetch_employee_surveys"]
