// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: challenges.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const getActiveChallengeByID = `-- name: GetActiveChallengeByID :one
SELECT id, slug, title, modality, language, difficulty, target_code, test_suite, active_from, active_to, created_at
FROM challenges
WHERE id = $1
  AND active_from <= now()
  AND (active_to IS NULL OR active_to > now())
`

// "active" means within the active_from/active_to window. The window is
// enforced here so handler code never has to think about it.
func (q *Queries) GetActiveChallengeByID(ctx context.Context, id uuid.UUID) (Challenge, error) {
	row := q.db.QueryRow(ctx, getActiveChallengeByID, id)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Modality,
		&i.Language,
		&i.Difficulty,
		&i.TargetCode,
		&i.TestSuite,
		&i.ActiveFrom,
		&i.ActiveTo,
		&i.CreatedAt,
	)
	return i, err
}

const getChallengeByID = `-- name: GetChallengeByID :one
SELECT id, slug, title, modality, language, difficulty, target_code, test_suite, active_from, active_to, created_at
FROM challenges
WHERE id = $1
`

func (q *Queries) GetChallengeByID(ctx context.Context, id uuid.UUID) (Challenge, error) {
	row := q.db.QueryRow(ctx, getChallengeByID, id)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Modality,
		&i.Language,
		&i.Difficulty,
		&i.TargetCode,
		&i.TestSuite,
		&i.ActiveFrom,
		&i.ActiveTo,
		&i.CreatedAt,
	)
	return i, err
}

const getChallengeBySlug = `-- name: GetChallengeBySlug :one
SELECT id, slug, title, modality, language, difficulty, target_code, test_suite, active_from, active_to, created_at
FROM challenges
WHERE slug = $1
`

func (q *Queries) GetChallengeBySlug(ctx context.Context, slug string) (Challenge, error) {
	row := q.db.QueryRow(ctx, getChallengeBySlug, slug)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Modality,
		&i.Language,
		&i.Difficulty,
		&i.TargetCode,
		&i.TestSuite,
		&i.ActiveFrom,
		&i.ActiveTo,
		&i.CreatedAt,
	)
	return i, err
}

const getTodayDailyChallenge = `-- name: GetTodayDailyChallenge :one
SELECT c.id, c.slug, c.title, c.modality, c.language, c.difficulty, c.target_code, c.test_suite, c.active_from, c.active_to, c.created_at
FROM daily_challenges d
JOIN challenges c ON c.id = d.challenge_id
WHERE d.challenge_date = (now() AT TIME ZONE 'UTC')::date
`

// Resolves the daily-mode challenge for today's date in UTC.
func (q *Queries) GetTodayDailyChallenge(ctx context.Context) (Challenge, error) {
	row := q.db.QueryRow(ctx, getTodayDailyChallenge)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Title,
		&i.Modality,
		&i.Language,
		&i.Difficulty,
		&i.TargetCode,
		&i.TestSuite,
		&i.ActiveFrom,
		&i.ActiveTo,
		&i.CreatedAt,
	)
	return i, err
}

const listPracticeChallenges = `-- name: ListPracticeChallenges :many
SELECT id, slug, title, modality, language, difficulty, target_code, test_suite, active_from, active_to, created_at
FROM challenges
WHERE modality = $1
  AND active_from <= now()
  AND (active_to IS NULL OR active_to > now())
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListPracticeChallengesParams struct {
	Modality string `json:"modality"`
	Limit    int32  `json:"limit"`
	Offset   int32  `json:"offset"`
}

// Practice mode: every active challenge for a modality, paged by recency.
func (q *Queries) ListPracticeChallenges(ctx context.Context, arg ListPracticeChallengesParams) ([]Challenge, error) {
	rows, err := q.db.Query(ctx, listPracticeChallenges, arg.Modality, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Challenge
	for rows.Next() {
		var i Challenge
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Title,
			&i.Modality,
			&i.Language,
			&i.Difficulty,
			&i.TargetCode,
			&i.TestSuite,
			&i.ActiveFrom,
			&i.ActiveTo,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
