// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Challenge struct {
	ID         uuid.UUID          `json:"id"`
	Slug       string             `json:"slug"`
	Title      string             `json:"title"`
	Modality   string             `json:"modality"`
	Language   string             `json:"language"`
	Difficulty string             `json:"difficulty"`
	TargetCode string             `json:"target_code"`
	TestSuite  []byte             `json:"test_suite"`
	ActiveFrom pgtype.Timestamptz `json:"active_from"`
	ActiveTo   pgtype.Timestamptz `json:"active_to"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type DailyChallenge struct {
	ChallengeDate pgtype.Date        `json:"challenge_date"`
	ChallengeID   uuid.UUID          `json:"challenge_id"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type Model struct {
	Slug        string             `json:"slug"`
	DisplayName string             `json:"display_name"`
	Provider    string             `json:"provider"`
	ParamCountB pgtype.Numeric     `json:"param_count_b"`
	Multiplier  pgtype.Numeric     `json:"multiplier"`
	Active      bool               `json:"active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type OtpChallenge struct {
	ID          uuid.UUID          `json:"id"`
	Channel     string             `json:"channel"`
	Identifier  string             `json:"identifier"`
	CodeHash    *string            `json:"code_hash"`
	ProviderRef *string            `json:"provider_ref"`
	Attempts    int32              `json:"attempts"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt  pgtype.Timestamptz `json:"consumed_at"`
	Ip          *string            `json:"ip"`
	Ua          *string            `json:"ua"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Rating struct {
	UserID      uuid.UUID          `json:"user_id"`
	Modality    string             `json:"modality"`
	Elo         pgtype.Numeric     `json:"elo"`
	GamesPlayed int32              `json:"games_played"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Session struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	RefreshHash string             `json:"refresh_hash"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
	Ip          *string            `json:"ip"`
	Ua          *string            `json:"ua"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Submission struct {
	ID           uuid.UUID          `json:"id"`
	UserID       uuid.UUID          `json:"user_id"`
	ChallengeID  uuid.UUID          `json:"challenge_id"`
	ModelSlug    string             `json:"model_slug"`
	Prompt       string             `json:"prompt"`
	PromptTokens int32              `json:"prompt_tokens"`
	OutputCode   *string            `json:"output_code"`
	Similarity   pgtype.Numeric     `json:"similarity"`
	TestsPassed  *int32             `json:"tests_passed"`
	TestsTotal   *int32             `json:"tests_total"`
	Multiplier   pgtype.Numeric     `json:"multiplier"`
	Brevity      pgtype.Numeric     `json:"brevity"`
	Score        pgtype.Numeric     `json:"score"`
	Status       string             `json:"status"`
	RejectReason *string            `json:"reject_reason"`
	Seed         int64              `json:"seed"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	GradedAt     pgtype.Timestamptz `json:"graded_at"`
}

type User struct {
	ID          uuid.UUID          `json:"id"`
	Email       *string            `json:"email"`
	Phone       *string            `json:"phone"`
	DisplayName string             `json:"display_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
}
