// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: submissions.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSubmission = `-- name: CreateSubmission :one
INSERT INTO submissions (
    user_id, challenge_id, model_slug, prompt, prompt_tokens, status, seed
) VALUES ($1, $2, $3, $4, $5, 'queued', $6)
RETURNING id, user_id, challenge_id, model_slug, prompt, prompt_tokens, output_code, similarity, tests_passed, tests_total, multiplier, brevity, score, status, reject_reason, seed, created_at, graded_at
`

type CreateSubmissionParams struct {
	UserID       uuid.UUID `json:"user_id"`
	ChallengeID  uuid.UUID `json:"challenge_id"`
	ModelSlug    string    `json:"model_slug"`
	Prompt       string    `json:"prompt"`
	PromptTokens int32     `json:"prompt_tokens"`
	Seed         int64     `json:"seed"`
}

func (q *Queries) CreateSubmission(ctx context.Context, arg CreateSubmissionParams) (Submission, error) {
	row := q.db.QueryRow(ctx, createSubmission,
		arg.UserID,
		arg.ChallengeID,
		arg.ModelSlug,
		arg.Prompt,
		arg.PromptTokens,
		arg.Seed,
	)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChallengeID,
		&i.ModelSlug,
		&i.Prompt,
		&i.PromptTokens,
		&i.OutputCode,
		&i.Similarity,
		&i.TestsPassed,
		&i.TestsTotal,
		&i.Multiplier,
		&i.Brevity,
		&i.Score,
		&i.Status,
		&i.RejectReason,
		&i.Seed,
		&i.CreatedAt,
		&i.GradedAt,
	)
	return i, err
}

const getSubmissionByIDForUser = `-- name: GetSubmissionByIDForUser :one
SELECT id, user_id, challenge_id, model_slug, prompt, prompt_tokens, output_code, similarity, tests_passed, tests_total, multiplier, brevity, score, status, reject_reason, seed, created_at, graded_at
FROM submissions
WHERE id = $1
  AND user_id = $2
`

type GetSubmissionByIDForUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetSubmissionByIDForUser(ctx context.Context, arg GetSubmissionByIDForUserParams) (Submission, error) {
	row := q.db.QueryRow(ctx, getSubmissionByIDForUser, arg.ID, arg.UserID)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChallengeID,
		&i.ModelSlug,
		&i.Prompt,
		&i.PromptTokens,
		&i.OutputCode,
		&i.Similarity,
		&i.TestsPassed,
		&i.TestsTotal,
		&i.Multiplier,
		&i.Brevity,
		&i.Score,
		&i.Status,
		&i.RejectReason,
		&i.Seed,
		&i.CreatedAt,
		&i.GradedAt,
	)
	return i, err
}

const listUserSubmissions = `-- name: ListUserSubmissions :many
SELECT id, user_id, challenge_id, model_slug, prompt, prompt_tokens, output_code, similarity, tests_passed, tests_total, multiplier, brevity, score, status, reject_reason, seed, created_at, graded_at
FROM submissions
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListUserSubmissionsParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
	Offset int32     `json:"offset"`
}

func (q *Queries) ListUserSubmissions(ctx context.Context, arg ListUserSubmissionsParams) ([]Submission, error) {
	rows, err := q.db.Query(ctx, listUserSubmissions, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Submission
	for rows.Next() {
		var i Submission
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ChallengeID,
			&i.ModelSlug,
			&i.Prompt,
			&i.PromptTokens,
			&i.OutputCode,
			&i.Similarity,
			&i.TestsPassed,
			&i.TestsTotal,
			&i.Multiplier,
			&i.Brevity,
			&i.Score,
			&i.Status,
			&i.RejectReason,
			&i.Seed,
			&i.CreatedAt,
			&i.GradedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markSubmissionFailed = `-- name: MarkSubmissionFailed :one
UPDATE submissions
SET status        = 'rejected',
    reject_reason = $2,
    graded_at     = now()
WHERE id = $1
RETURNING id, user_id, challenge_id, model_slug, prompt, prompt_tokens, output_code, similarity, tests_passed, tests_total, multiplier, brevity, score, status, reject_reason, seed, created_at, graded_at
`

type MarkSubmissionFailedParams struct {
	ID           uuid.UUID `json:"id"`
	RejectReason *string   `json:"reject_reason"`
}

func (q *Queries) MarkSubmissionFailed(ctx context.Context, arg MarkSubmissionFailedParams) (Submission, error) {
	row := q.db.QueryRow(ctx, markSubmissionFailed, arg.ID, arg.RejectReason)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChallengeID,
		&i.ModelSlug,
		&i.Prompt,
		&i.PromptTokens,
		&i.OutputCode,
		&i.Similarity,
		&i.TestsPassed,
		&i.TestsTotal,
		&i.Multiplier,
		&i.Brevity,
		&i.Score,
		&i.Status,
		&i.RejectReason,
		&i.Seed,
		&i.CreatedAt,
		&i.GradedAt,
	)
	return i, err
}

const markSubmissionGraded = `-- name: MarkSubmissionGraded :one
UPDATE submissions
SET status        = 'graded',
    output_code   = $2,
    similarity    = $3,
    tests_passed  = $4,
    tests_total   = $5,
    multiplier    = $6,
    brevity       = $7,
    score         = $8,
    graded_at     = now()
WHERE id = $1
RETURNING id, user_id, challenge_id, model_slug, prompt, prompt_tokens, output_code, similarity, tests_passed, tests_total, multiplier, brevity, score, status, reject_reason, seed, created_at, graded_at
`

type MarkSubmissionGradedParams struct {
	ID          uuid.UUID      `json:"id"`
	OutputCode  *string        `json:"output_code"`
	Similarity  pgtype.Numeric `json:"similarity"`
	TestsPassed *int32         `json:"tests_passed"`
	TestsTotal  *int32         `json:"tests_total"`
	Multiplier  pgtype.Numeric `json:"multiplier"`
	Brevity     pgtype.Numeric `json:"brevity"`
	Score       pgtype.Numeric `json:"score"`
}

func (q *Queries) MarkSubmissionGraded(ctx context.Context, arg MarkSubmissionGradedParams) (Submission, error) {
	row := q.db.QueryRow(ctx, markSubmissionGraded,
		arg.ID,
		arg.OutputCode,
		arg.Similarity,
		arg.TestsPassed,
		arg.TestsTotal,
		arg.Multiplier,
		arg.Brevity,
		arg.Score,
	)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChallengeID,
		&i.ModelSlug,
		&i.Prompt,
		&i.PromptTokens,
		&i.OutputCode,
		&i.Similarity,
		&i.TestsPassed,
		&i.TestsTotal,
		&i.Multiplier,
		&i.Brevity,
		&i.Score,
		&i.Status,
		&i.RejectReason,
		&i.Seed,
		&i.CreatedAt,
		&i.GradedAt,
	)
	return i, err
}

const pickAndLockQueuedSubmission = `-- name: PickAndLockQueuedSubmission :one
UPDATE submissions
SET status = 'running'
WHERE id = (
    SELECT id FROM submissions
    WHERE status = 'queued'
    ORDER BY created_at
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
RETURNING id, user_id, challenge_id, model_slug, prompt, prompt_tokens, output_code, similarity, tests_passed, tests_total, multiplier, brevity, score, status, reject_reason, seed, created_at, graded_at
`

// Worker poll path. SKIP LOCKED makes multiple workers safe.
func (q *Queries) PickAndLockQueuedSubmission(ctx context.Context) (Submission, error) {
	row := q.db.QueryRow(ctx, pickAndLockQueuedSubmission)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChallengeID,
		&i.ModelSlug,
		&i.Prompt,
		&i.PromptTokens,
		&i.OutputCode,
		&i.Similarity,
		&i.TestsPassed,
		&i.TestsTotal,
		&i.Multiplier,
		&i.Brevity,
		&i.Score,
		&i.Status,
		&i.RejectReason,
		&i.Seed,
		&i.CreatedAt,
		&i.GradedAt,
	)
	return i, err
}

const rejectSubmission = `-- name: RejectSubmission :one
INSERT INTO submissions (
    user_id, challenge_id, model_slug, prompt, prompt_tokens, status, reject_reason, seed
) VALUES ($1, $2, $3, $4, $5, 'rejected', $6, $7)
RETURNING id, user_id, challenge_id, model_slug, prompt, prompt_tokens, output_code, similarity, tests_passed, tests_total, multiplier, brevity, score, status, reject_reason, seed, created_at, graded_at
`

type RejectSubmissionParams struct {
	UserID       uuid.UUID `json:"user_id"`
	ChallengeID  uuid.UUID `json:"challenge_id"`
	ModelSlug    string    `json:"model_slug"`
	Prompt       string    `json:"prompt"`
	PromptTokens int32     `json:"prompt_tokens"`
	RejectReason *string   `json:"reject_reason"`
	Seed         int64     `json:"seed"`
}

func (q *Queries) RejectSubmission(ctx context.Context, arg RejectSubmissionParams) (Submission, error) {
	row := q.db.QueryRow(ctx, rejectSubmission,
		arg.UserID,
		arg.ChallengeID,
		arg.ModelSlug,
		arg.Prompt,
		arg.PromptTokens,
		arg.RejectReason,
		arg.Seed,
	)
	var i Submission
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ChallengeID,
		&i.ModelSlug,
		&i.Prompt,
		&i.PromptTokens,
		&i.OutputCode,
		&i.Similarity,
		&i.TestsPassed,
		&i.TestsTotal,
		&i.Multiplier,
		&i.Brevity,
		&i.Score,
		&i.Status,
		&i.RejectReason,
		&i.Seed,
		&i.CreatedAt,
		&i.GradedAt,
	)
	return i, err
}
