package net.omarss.omono.feature.speed

// Random-pick phrase pools for the "Fun mode" setting. Each list
// holds ~50 short speed-limit-related zingers in its language — TTS
// picks one uniformly at random when funMode is enabled, replacing
// the canned "Please slow down" line.
//
// Keep phrases short (≤ 8 words) so TTS doesn't talk over a whole
// acceleration. New phrases can be appended freely; only the chosen
// index changes, no code elsewhere depends on list length or order.
internal object FunPhrases {

    // Mix of nudges, cultural cues, and playful reminders. Nothing
    // mean-spirited — the point is to make the reminder memorable,
    // not to shame the user.
    val english: List<String> = listOf(
        "Whoa there, speed racer.",
        "Let's not break any records today.",
        "Your tyres are calling, please slow down.",
        "Easy, easy. Saudi roads can wait.",
        "Gravity wins. Slow down.",
        "Physics says: chill out.",
        "You're faster than the music. Ease up.",
        "This isn't the Nürburgring.",
        "The road is not in a hurry.",
        "Leave the driving to tomorrow.",
        "Your future self says slow down.",
        "Speed cameras never blink.",
        "Saher is watching. Take it easy.",
        "Breathe. Relax. Slow down.",
        "You're overdoing it. Ease off.",
        "Take a deep breath and lift.",
        "Let's arrive alive.",
        "Nothing ahead is worth this speed.",
        "The sheikh says: be patient.",
        "Even the desert is in no rush.",
        "Slow hands, fast thoughts.",
        "You've got places to be, but stay intact.",
        "Speed limits were written for you today.",
        "Somewhere, a camel is laughing at you.",
        "Horses used to win races. Not anymore.",
        "Your insurance premium thanks you.",
        "Slow now, coffee sooner.",
        "Your passenger is praying.",
        "Easy on the throttle, champ.",
        "Take it easy, my friend.",
        "The road is not going anywhere.",
        "Your steering wheel is not a joystick.",
        "Lift off. You're flying.",
        "Gentle, gentle.",
        "The limit isn't a suggestion.",
        "Back it off a notch.",
        "Let the others race, we cruise.",
        "You're ahead, you can afford to coast.",
        "Red lights prefer calm cars.",
        "Your neighbourhood called. Slow down.",
        "The Kaaba isn't going anywhere.",
        "Back to the real world, please.",
        "You're setting a bad example.",
        "The speedometer called. It's worried.",
        "One more km/h won't save the day.",
        "Your car's whispering: please stop.",
        "Arrive five seconds later, fine.",
        "Even the wind says: calm.",
        "Time isn't that tight.",
        "Breathe in, foot up.",
    )

    val arabic: List<String> = listOf(
        "هدّئ سرعتك، لا تستعجل.",
        "الطريق صبور، كن مثله.",
        "خفف السرعة، الجمل أسرع منك مشياً ما يستعجل.",
        "ما في داعي للسرعة.",
        "رفق بنفسك وبسيارتك.",
        "ما في شيء يستاهل هالسرعة.",
        "تمهّل بالله عليك.",
        "الطريق ما يروح.",
        "هدّيها شوي.",
        "فرامل، يا بطل.",
        "ساهر يراقبك.",
        "التأخير أفضل من كثير أشياء.",
        "الحياة ما تستعجل.",
        "اتركها شوي، نفّس.",
        "خذها ببساطة.",
        "هوّن عليك.",
        "إن شاء الله توصل بسلامة.",
        "حافظ على روحك ومن معك.",
        "توكل على الله، لكن ما يضر تهدأ.",
        "اللي قدامك ما راح يهرب.",
        "سرعتك مبالغ فيها.",
        "ارفع رجلك عن البنزين.",
        "إنت مو في سباق.",
        "خذ نفس عميق واهدأ.",
        "بلاش استعجال، الأمان أهم.",
        "السرعة غدر.",
        "تذكر، البيت ينتظرك.",
        "لا تهدي عمرك بسرعتك.",
        "اللي يصل بسلام يصل مرتين.",
        "الحذر واجب.",
        "لا تجرب حظك.",
        "الحياة أغلى من دقيقة.",
        "استرخ، الطريق طويلة.",
        "يا حلو خفف شوي.",
        "بسم الله، وبس برهق شوي.",
        "انت بطل، بطّئها بطولة.",
        "الكاميرا ما تغفل.",
        "حق المخالفة غالي، وفّره.",
        "سلامتك أولاً.",
        "ما تحتاج كل هذه السرعة.",
        "الناس تتذكر السائق الهادئ.",
        "أمك تدعي لك، لا تخيب ظنها.",
        "القهوة تنتظر، بس بسلام.",
        "اهدأ قبل لا تندم.",
        "خفف، يا غالي.",
        "لا أحد أسرع من القدر، هوّن عليك.",
        "الطريق أمانة، احفظها.",
        "كل شوي ريّح الفرامل.",
        "مو ضروري تسبق الجميع.",
        "هدّي من روعك.",
    )
}
