/* tslint:disable */
/* eslint-disable */
/**
 * SaaS Data Plane API
 * Per-deployment data plane API. One vhost per Deployment under *.saas.omarss.net.
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface APIKey {
    'id': string;
    'object': APIKeyObjectEnum;
    'tenant_id': string;
    'environment_id'?: string;
    'name': string;
    /**
     * Visible prefix shape `<env>_<8-char-random>`, e.g. \"live_AX9BC7D3\".
     */
    'prefix': string;
    'scopes': Array<string>;
    'status': APIKeyStatusEnum;
    'rate_limit_per_minute'?: number;
    'ip_allowlist'?: Array<string>;
    'created_by': string;
    'created_at': string;
    'updated_at': string;
    'expires_at'?: string;
    'last_used_at'?: string;
    'revoked_at'?: string;
    'rotated_at'?: string;
    /**
     * When the previous secret stops authenticating during rotation grace.
     */
    'predecessor_expires_at'?: string;
    /**
     * Weak ETag, format W/\"v<sequence>\".
     */
    'etag': string;
}

export const APIKeyObjectEnum = {
    ApiKey: 'api_key',
} as const;

export type APIKeyObjectEnum = typeof APIKeyObjectEnum[keyof typeof APIKeyObjectEnum];
export const APIKeyStatusEnum = {
    Active: 'active',
    Revoked: 'revoked',
    Expired: 'expired',
} as const;

export type APIKeyStatusEnum = typeof APIKeyStatusEnum[keyof typeof APIKeyStatusEnum];


