/* tslint:disable */
/* eslint-disable */
/**
 * SaaS Data Plane API
 * Per-deployment data plane API. One vhost per Deployment under *.saas.omarss.net.
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface AuditEvent {
    'id': string;
    'tenant_id': string;
    'actor_type': AuditEventActorTypeEnum;
    'actor_id': string;
    'action': string;
    'resource_type': string;
    'resource_id'?: string;
    'occurred_at': string;
    'ip_address'?: string;
    'user_agent'?: string;
    'request_id'?: string;
    'metadata'?: { [key: string]: any; };
    /**
     * Lowercase hex SHA-256 of the previous row, or the per-tenant Genesis seed for chain_sequence=1.
     */
    'prev_hash': string;
    /**
     * Lowercase hex SHA-256 of (prev_hash || JCS(canonical row body)).
     */
    'row_hash': string;
    /**
     * Per-tenant monotonic sequence number starting at 1.
     */
    'chain_sequence': number;
}

export const AuditEventActorTypeEnum = {
    User: 'user',
    ApiKey: 'api_key',
    Operator: 'operator',
    OperatorImpersonation: 'operator_impersonation',
    System: 'system',
} as const;

export type AuditEventActorTypeEnum = typeof AuditEventActorTypeEnum[keyof typeof AuditEventActorTypeEnum];


