/* tslint:disable */
/* eslint-disable */
/**
 * SaaS Data Plane API
 * Per-deployment data plane API. One vhost per Deployment under *.saas.omarss.net.
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface CreateAPIKeyRequest {
    'name': string;
    'scopes': Array<string>;
    'environment_id'?: string;
    'expires_at'?: string;
    'rate_limit_per_minute'?: number;
    'ip_allowlist'?: Array<string>;
}

