/* tslint:disable */
/* eslint-disable */
/**
 * SaaS Data Plane API
 * Per-deployment data plane API. One vhost per Deployment under *.saas.omarss.net.
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { Invitation } from './invitation';

export interface CreateInvitationResponse {
    'data': Invitation;
    /**
     * Full accept URL including the one-time plaintext token. Never logged; returned only in this 202 response.
     */
    'accept_url': string;
    /**
     * Plaintext one-time accept token. Discard after sending the email; subsequent reads return only token_prefix.
     */
    'state': string;
    'expires_at': string;
}

