/* tslint:disable */
/* eslint-disable */
/**
 * SaaS Data Plane API
 * Per-deployment data plane API. One vhost per Deployment under *.saas.omarss.net.
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { CredentialsBundle } from './credentials-bundle';

export interface CreateNotificationChannelRequest {
    'provider': CreateNotificationChannelRequestProviderEnum;
    'name': string;
    'config'?: { [key: string]: string; };
    'is_default_for'?: Array<CreateNotificationChannelRequestIsDefaultForEnum>;
    'credentials'?: CredentialsBundle;
}

export const CreateNotificationChannelRequestProviderEnum = {
    Smtp: 'smtp',
    Sendgrid: 'sendgrid',
    Ses: 'ses',
    InApp: 'in_app',
} as const;

export type CreateNotificationChannelRequestProviderEnum = typeof CreateNotificationChannelRequestProviderEnum[keyof typeof CreateNotificationChannelRequestProviderEnum];
export const CreateNotificationChannelRequestIsDefaultForEnum = {
    Email: 'email',
    InApp: 'in_app',
} as const;

export type CreateNotificationChannelRequestIsDefaultForEnum = typeof CreateNotificationChannelRequestIsDefaultForEnum[keyof typeof CreateNotificationChannelRequestIsDefaultForEnum];


