/* tslint:disable */
/* eslint-disable */
/**
 * SaaS Data Plane API
 * Per-deployment data plane API. One vhost per Deployment under *.saas.omarss.net.
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SESCredentials } from './sescredentials';
// May contain unused imports in some cases
// @ts-ignore
import type { SMTPCredentials } from './smtpcredentials';
// May contain unused imports in some cases
// @ts-ignore
import type { SendGridCredentials } from './send-grid-credentials';

/**
 * Per-provider credential bundle. Exactly one of smtp / sendgrid / ses is populated based on the channel provider; the in_app provider rejects any credential payload. 
 */
export interface CredentialsBundle {
    'smtp'?: SMTPCredentials;
    'sendgrid'?: SendGridCredentials;
    'ses'?: SESCredentials;
}

