/* tslint:disable */
/* eslint-disable */
/**
 * SaaS Data Plane API
 * Per-deployment data plane API. One vhost per Deployment under *.saas.omarss.net.
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface Invitation {
    'id': string;
    'object': InvitationObjectEnum;
    'tenant_id': string;
    'organization_id': string;
    'invitee_email': string;
    /**
     * First 8 chars of the base64-url accept token. The full token is only returned in the POST /invitations 202 response.
     */
    'token_prefix': string;
    'invited_by_user_id'?: string;
    'proposed_role_id'?: string;
    'status': InvitationStatusEnum;
    'expires_at': string;
    'accepted_at'?: string;
    'accepted_by_user_id'?: string;
    'revoked_at'?: string;
    'revoked_by_user_id'?: string;
    'created_at': string;
    'updated_at': string;
    'etag': string;
}

export const InvitationObjectEnum = {
    Invitation: 'invitation',
} as const;

export type InvitationObjectEnum = typeof InvitationObjectEnum[keyof typeof InvitationObjectEnum];
export const InvitationStatusEnum = {
    Pending: 'pending',
    Accepted: 'accepted',
    Revoked: 'revoked',
    Expired: 'expired',
} as const;

export type InvitationStatusEnum = typeof InvitationStatusEnum[keyof typeof InvitationStatusEnum];


