/* tslint:disable */
/* eslint-disable */
/**
 * SaaS Data Plane API
 * Per-deployment data plane API. One vhost per Deployment under *.saas.omarss.net.
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface Member {
    'id': string;
    'object': MemberObjectEnum;
    'tenant_id': string;
    'organization_id': string;
    'user_id': string;
    'role_id'?: string;
    'status': MemberStatusEnum;
    'metadata'?: { [key: string]: string; };
    'joined_at': string;
    'updated_at': string;
    'removed_at'?: string;
    'etag': string;
}

export const MemberObjectEnum = {
    Member: 'member',
} as const;

export type MemberObjectEnum = typeof MemberObjectEnum[keyof typeof MemberObjectEnum];
export const MemberStatusEnum = {
    Active: 'active',
    Suspended: 'suspended',
    Removed: 'removed',
} as const;

export type MemberStatusEnum = typeof MemberStatusEnum[keyof typeof MemberStatusEnum];


