/* tslint:disable */
/* eslint-disable */
/**
 * SaaS Data Plane API
 * Per-deployment data plane API. One vhost per Deployment under *.saas.omarss.net.
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface NotificationChannel {
    'id': string;
    'object': NotificationChannelObjectEnum;
    'provider': NotificationChannelProviderEnum;
    'name': string;
    'status': NotificationChannelStatusEnum;
    'is_default_for'?: Array<NotificationChannelIsDefaultForEnum>;
    'config'?: { [key: string]: string; };
    /**
     * True iff the channel row currently carries envelope-encrypted credentials. The platform NEVER returns the credential bytes. 
     */
    'credentials_present': boolean;
    'last_rotated_at'?: string;
    'created_at': string;
    'updated_at': string;
    'etag': string;
}

export const NotificationChannelObjectEnum = {
    NotificationChannel: 'notification_channel',
} as const;

export type NotificationChannelObjectEnum = typeof NotificationChannelObjectEnum[keyof typeof NotificationChannelObjectEnum];
export const NotificationChannelProviderEnum = {
    Smtp: 'smtp',
    Sendgrid: 'sendgrid',
    Ses: 'ses',
    InApp: 'in_app',
} as const;

export type NotificationChannelProviderEnum = typeof NotificationChannelProviderEnum[keyof typeof NotificationChannelProviderEnum];
export const NotificationChannelStatusEnum = {
    Active: 'active',
    Disabled: 'disabled',
} as const;

export type NotificationChannelStatusEnum = typeof NotificationChannelStatusEnum[keyof typeof NotificationChannelStatusEnum];
export const NotificationChannelIsDefaultForEnum = {
    Email: 'email',
    InApp: 'in_app',
} as const;

export type NotificationChannelIsDefaultForEnum = typeof NotificationChannelIsDefaultForEnum[keyof typeof NotificationChannelIsDefaultForEnum];


