/* tslint:disable */
/* eslint-disable */
/**
 * SaaS Data Plane API
 * Per-deployment data plane API. One vhost per Deployment under *.saas.omarss.net.
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface Notification {
    'id': string;
    'object': NotificationObjectEnum;
    'tenant_id': string;
    'workflow_name': string;
    'to_user_id': string;
    'status': NotificationStatusEnum;
    'novu_transaction_id'?: string;
    'queued_at': string;
    'sent_at'?: string;
    'delivered_at'?: string;
    'failed_at'?: string;
    'failure_reason'?: string;
}

export const NotificationObjectEnum = {
    Notification: 'notification',
} as const;

export type NotificationObjectEnum = typeof NotificationObjectEnum[keyof typeof NotificationObjectEnum];
export const NotificationStatusEnum = {
    Queued: 'queued',
    Sent: 'sent',
    Delivered: 'delivered',
    Failed: 'failed',
} as const;

export type NotificationStatusEnum = typeof NotificationStatusEnum[keyof typeof NotificationStatusEnum];


