/* tslint:disable */
/* eslint-disable */
/**
 * SaaS Data Plane API
 * Per-deployment data plane API. One vhost per Deployment under *.saas.omarss.net.
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { FieldError } from './field-error';

export interface Problem {
    'type': string;
    'title': string;
    'status': number;
    'detail'?: string;
    'instance'?: string;
    'request_id'?: string;
    'errors'?: Array<FieldError>;
}

