/* tslint:disable */
/* eslint-disable */
/**
 * SaaS Data Plane API
 * Per-deployment data plane API. One vhost per Deployment under *.saas.omarss.net.
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface Role {
    'id': string;
    'object': RoleObjectEnum;
    'tenant_id': string;
    'name': string;
    'description'?: string;
    'is_system': boolean;
    /**
     * Permission ids granted to this role.
     */
    'permissions'?: Array<string>;
    'metadata'?: { [key: string]: string; };
    'created_at': string;
    'updated_at': string;
    'etag': string;
}

export const RoleObjectEnum = {
    Role: 'role',
} as const;

export type RoleObjectEnum = typeof RoleObjectEnum[keyof typeof RoleObjectEnum];


