/* tslint:disable */
/* eslint-disable */
/**
 * SaaS Data Plane API
 * Per-deployment data plane API. One vhost per Deployment under *.saas.omarss.net.
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface Tenant {
    'id': string;
    'object': TenantObjectEnum;
    'slug': string;
    'name': string;
    'status': TenantStatusEnum;
    'default_organization_id'?: string;
    'metadata'?: { [key: string]: string; };
    'created_at': string;
    'updated_at': string;
    'deleted_at'?: string;
    /**
     * Weak ETag, format W/\"v<sequence>\".
     */
    'etag': string;
}

export const TenantObjectEnum = {
    Tenant: 'tenant',
} as const;

export type TenantObjectEnum = typeof TenantObjectEnum[keyof typeof TenantObjectEnum];
export const TenantStatusEnum = {
    Active: 'active',
    Suspended: 'suspended',
    Deleted: 'deleted',
} as const;

export type TenantStatusEnum = typeof TenantStatusEnum[keyof typeof TenantStatusEnum];


