/* tslint:disable */
/* eslint-disable */
/**
 * SaaS Data Plane API
 * Per-deployment data plane API. One vhost per Deployment under *.saas.omarss.net.
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



export interface User {
    'id': string;
    'object': UserObjectEnum;
    'tenant_id': string;
    'email': string;
    'email_verified': boolean;
    'name'?: string;
    'phone'?: string;
    'status': UserStatusEnum;
    'metadata'?: { [key: string]: string; };
    'created_at': string;
    'updated_at': string;
    /**
     * Weak ETag, format W/\"v<sequence>\".
     */
    'etag': string;
}

export const UserObjectEnum = {
    User: 'user',
} as const;

export type UserObjectEnum = typeof UserObjectEnum[keyof typeof UserObjectEnum];
export const UserStatusEnum = {
    Active: 'active',
    Disabled: 'disabled',
    Deleted: 'deleted',
} as const;

export type UserStatusEnum = typeof UserStatusEnum[keyof typeof UserStatusEnum];


